'use es6';

export var BROADCAST_POSTS_FETCH_BEGAN = 'BROADCAST_POSTS_FETCH_BEGAN';
export var BROADCAST_POSTS_FETCH_ERROR = 'BROADCAST_POSTS_FETCH_ERROR';
export var BROADCAST_POSTS_FETCH_SUCCESS = 'BROADCAST_POSTS_FETCH_SUCCESS';
export var BROADCAST_POST_DELETE_BEGAN = 'BROADCAST_POST_DELETE_BEGAN';
export var BROADCAST_POST_DELETE_ERROR = 'BROADCAST_POST_DELETE_ERROR';
export var BROADCAST_POST_DELETE_SUCCESS = 'BROADCAST_POST_DELETE_SUCCESS';