import { DefaultCellHeaderRightAlign } from "../../../../components/React/Table/headerCells/DefaultCellHeaderRightAlign";
import { DefaultCellRightAlign } from "../../../../components/React/Table/cells/DefaultCellRightAlign";

export default [
    {
        fixed: true,
        cellTemp: "index",
        sortable: false,
        width: 65,
        disableHeaderCellHover: true,
    },
    {
        fixed: true,
        name: "Domain",
        title: "category.leaders.table.column.domain",
        type: "string",
        format: "None",
        sortable: "True",
        isSorted: "False",
        sortDirection: "desc",
        groupable: "False",
        cellTemp: "website-tooltip-top-cell",
        headTemp: "",
        totalCount: "True",
        tooltip: "widget.table.tooltip.topsites.domain",
        width: 173,
    },
    {
        name: "Share",
        title: "category.leaders.table.column.trafficshare",
        type: "string",
        format: "percentagesign",
        sortable: "True",
        isSorted: "True",
        sortDirection: "desc",
        groupable: "False",
        cellTemp: "traffic-share",
        headTemp: "",
        totalCount: "False",
        tooltip: "widget.table.tooltip.topsites.share",
        minWidth: 150,
    },
    {
        name: "Change",
        title: "category.leaders.table.column.change",
        type: "double",
        format: "percentagesign",
        sortable: "True",
        isSorted: "False",
        sortDirection: "desc",
        groupable: "False",
        cellTemp: "change-percentage",
        headerComponent: DefaultCellHeaderRightAlign,
        totalCount: "False",
        tooltip: "widget.table.tooltip.topsites.change",
        width: 110,
    },
    {
        name: "Rank",
        title: "category.leaders.table.column.rank",
        type: "long",
        format: "swRank",
        sortable: "True",
        isSorted: "False",
        sortDirection: "asc",
        groupable: "False",
        cellTemp: "rank-cell",
        headerComponent: DefaultCellHeaderRightAlign,
        totalCount: "False",
        tooltip: "widget.table.tooltip.topsites.rank",
        width: 85,
        inverted: "True",
    },
    {
        name: "AvgMonthVisits",
        title: "category.leaders.table.column.monthlyvisits",
        type: "double",
        format: "abbrNumber",
        sortable: "True",
        isSorted: "False",
        sortDirection: "desc",
        groupable: "False",
        cellComponent: DefaultCellRightAlign,
        headerComponent: DefaultCellHeaderRightAlign,
        totalCount: "False",
        tooltip: "widget.table.tooltip.monthlyvisits",
        width: 130,
    },
    {
        name: "AvgVisitDuration",
        title: "category.leaders.table.column.visitduration",
        type: "double",
        format: "number",
        sortable: "True",
        isSorted: "False",
        sortDirection: "desc",
        groupable: "False",
        cellTemp: "time-cell",
        headerComponent: DefaultCellHeaderRightAlign,
        totalCount: "False",
        tooltip: "widget.table.tooltip.topsites.avgvisitduration",
        width: 130,
    },
    {
        name: "PagesPerVisit",
        title: "category.leaders.table.column.pagespervisits",
        type: "double",
        format: "number",
        sortable: "True",
        isSorted: "False",
        sortDirection: "desc",
        groupable: "False",
        cellTemp: "pages-per-visit",
        headerComponent: DefaultCellHeaderRightAlign,
        totalCount: "False",
        tooltip: "widget.table.tooltip.topsites.ppv",
        width: 110,
    },
    {
        name: "BounceRate",
        title: "category.leaders.table.column.bouncerate",
        type: "double",
        format: "number",
        sortable: "True",
        isSorted: "False",
        sortDirection: "asc",
        groupable: "False",
        cellTemp: "bounce-rate",
        headerComponent: DefaultCellHeaderRightAlign,
        totalCount: "False",
        tooltip: "widget.table.tooltip.topsites.bouncerate",
        width: 125,
        inverted: "True",
    },
    {
        name: "HasAdsense",
        title: "category.leaders.table.column.adsense",
        type: "bool",
        format: "None",
        sortable: "True",
        isSorted: "False",
        sortDirection: "desc",
        groupable: "False",
        cellTemp: "adsense-cell",
        headTemp: "",
        totalCount: "False",
        tooltip: true,
        width: 95,
    },
];
