'use es6';

export var FETCH_STAGE_AGGREGATION_STARTED = 'FETCH_STAGE_AGGREGATION_STARTED';
export var FETCH_STAGE_AGGREGATION_SUCCEEDED = 'FETCH_STAGE_AGGREGATION_SUCCEEDED';
export var FETCH_STAGE_AGGREGATION_FAILED = 'FETCH_STAGE_AGGREGATION_FAILED';