export const SUBSCRIBE_FROM_TOP_BUTTON = "SUBSCRIBE_FROM_TOP_BUTTON";
export const SUBSCRIBE_FROM_POP_UP = "SUBSCRIBE_FROM_POP_UP";
export const UNSUBSCRIBE_CANCEL = "UNSUBSCRIBE_CANCEL";
export const UNSUBSCRIBE_CONFIRMED = "UNSUBSCRIBE_CONFIRMED";
export const SUBSCRIBE_SKIP_FROM_POP_UP = "SUBSCRIBE_SKIP_FROM_POP_UP";

export const SAVE_SEARCH_TOOLTIP_MAX_WIDTH = 224;
export const SAVE_SEARCH_RE_RUN_TOOLTIP_MAX_WIDTH = 350;

export const SALES_WORKSPACE_TRANSLATION_PREFIX = "workspace.sales";
export const SALES_WORKSPACE_RESULTS_PAGE_PREFIX = `${SALES_WORKSPACE_TRANSLATION_PREFIX}.leadgenerator.results-page`;

// TODO: Save-search related constants will be moved to "saved-searches" sub-module
export const SAVE_SEARCH_LAST_UPDATE_TEXT = `${SALES_WORKSPACE_RESULTS_PAGE_PREFIX}.last-update.text`;
export const SAVE_SEARCH_BUTTON_TEXT = `${SALES_WORKSPACE_RESULTS_PAGE_PREFIX}.save.btn.title`;
export const SAVE_SEARCH_TOOLTIP_TEXT = `${SALES_WORKSPACE_RESULTS_PAGE_PREFIX}.save.btn.tooltip`;
export const SAVE_SEARCH_RE_RUN_SWITCH_TEXT = `${SALES_WORKSPACE_RESULTS_PAGE_PREFIX}.auto-rerun.text`;
export const SAVE_SEARCH_RE_RUN_TOOLTIP_DESCRIPTION = `${SALES_WORKSPACE_RESULTS_PAGE_PREFIX}.auto-rerun.tooltip.description`;
export const SAVE_SEARCH_RE_RUN_TOOLTIP_DISABLED_TRIAL = `${SALES_WORKSPACE_RESULTS_PAGE_PREFIX}.auto-rerun.disabled.trial`;
export const SAVE_SEARCH_RE_RUN_TOOLTIP_DISABLED_LIMIT = `${SALES_WORKSPACE_RESULTS_PAGE_PREFIX}.auto-rerun.disabled.limit`;

export const SALES_RIGHT_SIDEBAR_TAB = "right_sidebar.tab";

export const SALES_RIGHT_SIDEBAR_TAB_ABOUT_KEY = `${SALES_WORKSPACE_TRANSLATION_PREFIX}.${SALES_RIGHT_SIDEBAR_TAB}.about`;
export const SALES_RIGHT_SIDEBAR_TAB_ANALYSIS_KEY = `${SALES_WORKSPACE_TRANSLATION_PREFIX}.${SALES_RIGHT_SIDEBAR_TAB}.analysis`;
export const SALES_RIGHT_SIDEBAR_TAB_BENCHMARKS_KEY = `${SALES_WORKSPACE_TRANSLATION_PREFIX}.${SALES_RIGHT_SIDEBAR_TAB}.benchmarks`;
export const SALES_RIGHT_SIDEBAR_TAB_BENCHMARKS_BETA = `${SALES_WORKSPACE_TRANSLATION_PREFIX}.${SALES_RIGHT_SIDEBAR_TAB}.benchmarks.beta`;

export const SELECTED_ALL_ID = -1;

export const SALES_RIGHT_SIDEBAR_TAB_SITE_TRENDS_KEY = `${SALES_WORKSPACE_TRANSLATION_PREFIX}.${SALES_RIGHT_SIDEBAR_TAB}.site_trends`;
