'use es6'; // Modals

export var EDIT_COLUMNS_MODAL = 'EDIT_COLUMNS_MODAL';
export var EXPORT_VIEW_MODAL = 'EXPORT_VIEW_MODAL';
export var RENAME_VIEW_MODAL = 'RENAME_VIEW_MODAL';
export var BULK_DELETE_MODAL = 'BULK_DELETE_MODAL';
export var MANAGE_VIEW_SHARING_MODAL = 'MANAGE_VIEW_SHARING_MODAL';
export var BULK_EDIT_MODAL = 'BULK_EDIT_MODAL';
export var DELETE_VIEW_MODAL = 'DELETE_VIEW_MODAL';
export var CLONE_VIEW_MODAL = 'CLONE_VIEW_MODAL';
export var CREATE_VIEW_MODAL = 'CREATE_VIEW_MODAL';
export var BOARD_SORT_MODAL = 'BOARD_SORT_MODAL';
export var EDIT_STAGE_PROPERTIES_MODAL = 'EDIT_STAGE_PROPERTIES_MODAL';