'use es6';

export var FETCH_DOUBLE_OPT_IN_STARTED = 'FETCH_DOUBLE_OPT_IN_STARTED';
export var FETCH_DOUBLE_OPT_IN_SUCCEEDED = 'FETCH_DOUBLE_OPT_IN_SUCCEEDED';
export var FETCH_DOUBLE_OPT_IN_FAILED = 'FETCH_DOUBLE_OPT_IN_FAILED';