export const PAGE_NAME_MAP = {
    "dashboard-exist": "Custom Dashboards",
    "websites-worldwideOverview": "WA Worldwide Overview",
    "websites-audienceOverview": "WA Audience Overview",
    "websites-audienceGeography": "WA Geography",
    "websites-audienceInterests": "WA Audience Interests",
    "websites-trafficOverview": "WA Marketing Mix",
    "websites-trafficReferrals": "WA Referrals",
    "websites-trafficSearch": "WA Search",
    "websites-trafficSocial": "WA Social",
    "websites-trafficDisplay-overview": "WA Display Ads",
    "websites-outgoing": "WA Outgoing Links",
    "websites-paidoutgoing": "WA Outgoing Ads",
    "websites-subdomains": "WA Sub-domains",
    "websites-popular": "WA Popular Pages",
    "websites-similarsites": "WA Similar Sites",
    "websites-competitorsOrganicKeywords": "WA Keyword Competitors - Organic",
    "websites-competitorsPaidKeywords": "WA Keyword Competitors - Paid",
    "industryAnalysis-topSites": "IA Top Sites",
    "industryAnalysis-categoryLeaders": "IA Leaders by Source",
    "industryAnalysis-overview": "IA Overview",
    "industryAnalysis-categoryShare": "IA Category Share",
    "industryAnalysis-trafficSources": "IA Traffic Sources",
    "industryAnalysis-topKeywords": "IA Top Keywords",
    "keywordAnalysis-organic": "KA Organic Competitors",
    "keywordAnalysis-paid": "KA Paid Competitors",
    "apps-ranking": "AA App Ranking",
    "apps-demographics": "AA App Demographics",
    "apps-appaudienceinterests": "AA Audience Intersts",
    "apps-engagementoverview": "AA Engagement Overview",
    "apps-engagementusage": "AA Usage Patterns",
    "apps-engagementretention": "AA Retention",
    "apps-instoretraffic": "AA In-Store Traffic",
    "apps-externaltraffic": "AA External Traffic",
    "apps-instoresearch": "AA In-Store Keywords",
    "apps-websearch": "AA Search Engine Keywords",
    "appcategory-leaderboard": "AC Leaderboard",
    "appcategory-trends": "AC Trends",
    "appcategory-topkeywords": "AC Top Keywords",
    "keywords-analysis": "App Keyword Analysis",
};
