import { IDashboardTemplate } from "../DashboardTemplateService";
import { EFamilyTypes } from "../components/DashboardTemplatesConfig";
import { AssetsService } from "../../../../services/AssetsService";

const dashboard: IDashboardTemplate = {
    id: 7,
    title: "dashboard.templates.organickeywordoptimization.title",
    description: "dashboard.templates.organickeywordoptimization.description",
    descriptionLong: "dashboard.templates.organickeywordoptimization.description.long",
    keyMetrics: "dashboard.templates.organickeywordoptimization.keymetric",
    previewImage: AssetsService.assetUrl(
        "/images/dashboard/templates/OrganicKeywordOptimization-preview.png",
    ),
    thumbnailImage: AssetsService.assetUrl(
        "/images/dashboard/templates/OrganicKeywordOptimization-thumb.png",
    ),
    familyType: EFamilyTypes.Website,
    minItems: 2,
    maxItems: 5,
    widgets: [
        {
            pos: {
                sizeX: 2,
                sizeY: 1,
                maxSizeY: 2,
                minSizeX: 2,
                maxSizeX: 4,
                row: 0,
                col: 0,
            },
            properties: {
                selectedChannel: "Organic Search",
                metric: "ChannelsAnalysisByTrafficShare",
                webSource: "Desktop",
                duration: "1m",
                type: "MmxTrafficShareDashboard",
                filters: {
                    includeSubDomains: "true",
                    timeGranularity: "Daily",
                },
                width: "4",
                customAsset: false,
                options: {},
                family: "Website",
                title: "SEO Traffic | Last Month",
                tooltip: "Traffic Share By Channel Organic Search.tooltip",
                titleTemplate: "custom",
            },
        },
        {
            pos: {
                sizeX: 2,
                maxSizeY: 2,
                minSizeX: 2,
                maxSizeX: 4,
                row: 0,
                col: 2,
                sizeY: 1,
            },
            properties: {
                flexibleDuration: true,
                selectedChannel: "Organic Search",
                metric: "ChannelsAnalysisByTrafficShare",
                webSource: "Desktop",
                duration: "12m",
                type: "MmxTrafficShareDashboard",
                filters: {
                    includeSubDomains: "true",
                    timeGranularity: "Monthly",
                },
                width: "4",
                customAsset: false,
                family: "Website",
                options: {},
                title: "SEO Traffic | Extended Period",
                tooltip: "SEO Traffic.tooltip",
                titleTemplate: "custom",
            },
        },
        {
            pos: {
                sizeX: 2,
                sizeY: 1,
                maxSizeY: 2,
                minSizeX: 2,
                maxSizeX: 4,
                row: 1,
                col: 0,
            },
            properties: {
                flexibleDuration: true,
                selectedChannel: "Organic Search",
                metric: "ChannelsAnalysisByBounceRate",
                webSource: "Desktop",
                duration: "6m",
                type: "MmxBounceRateDashboard",
                filters: {
                    includeSubDomains: "true",
                    timeGranularity: "Monthly",
                },
                width: "4",
                customAsset: false,
                family: "Website",
                options: {},
                title: "Bounce Rate - Organic Search",
                tooltip: "Bounce Rate - Organic Search.tooltip",
            },
        },
        {
            pos: {
                sizeX: 2,
                sizeY: 1,
                maxSizeY: 2,
                minSizeX: 2,
                maxSizeX: 4,
                row: 1,
                col: 2,
            },
            properties: {
                flexibleDuration: true,
                selectedChannel: "Organic Search",
                metric: "ChannelsAnalysisByAverageDuration",
                webSource: "Desktop",
                duration: "6m",
                type: "MmxVisitDurationDashboard",
                filters: {
                    includeSubDomains: "true",
                    timeGranularity: "Monthly",
                },
                width: "4",
                customAsset: false,
                family: "Website",
                options: {},
                title: "Avg. Visit Duration - Organic Search",
                tooltip: "Avg. Visit Durationv - Organic Search.tooltip",
                titleTemplate: "custom",
            },
        },
        {
            pos: {
                sizeX: 2,
                sizeY: 2,
                maxSizeY: 2,
                minSizeX: 2,
                maxSizeX: 4,
                row: 2,
                col: 0,
            },
            properties: {
                selectedChannel: "Direct",
                metric: "NewSearchKeywords",
                webSource: "Desktop",
                duration: "3m",
                type: "TableSearchKeywordsDashboard",
                filters: {
                    includeSubDomains: "true",
                    IncludeBranded: false,
                    IncludeNewKeywords: false,
                    IncludeNoneBranded: true,
                    IncludeOrganic: true,
                    IncludePaid: false,
                    IncludeQuestions: false,
                    IncludeTrendingKeywords: true,
                    filter: "",
                    orderBy: "TotalShare desc",
                    timeGranularity: "Monthly",
                },
                width: "4",
                customAsset: false,
                family: "Website",
                options: {},
                title: "Organic KW - Non-branded & Trending",
                tooltip: "Organic KW - Non-branded & Trending.tooltip",
            },
        },
        {
            pos: {
                sizeX: 2,
                maxSizeY: 2,
                minSizeX: 2,
                maxSizeX: 4,
                row: 2,
                col: 2,
                sizeY: 2,
            },
            properties: {
                breakRowAfterCopies: true,
                multiple: true,
                multipleOverrides: {
                    pos: {
                        sizeY: 1,
                    },
                    properties: {
                        title: "Website Trending Keywords",
                        filters: {
                            IncludeBranded: false,
                            IncludeNewKeywords: true,
                            IncludeNoneBranded: true,
                            IncludeOrganic: true,
                            IncludePaid: false,
                            IncludeQuestions: false,
                            IncludeTrendingKeywords: true,
                            orderBy: "Change desc",
                        },
                    },
                },
                selectedChannel: "Direct",
                metric: "NewSearchKeywords",
                webSource: "Desktop",
                duration: "1m",
                type: "TableSearchKeywordsDashboard",
                filters: {
                    includeSubDomains: "true",
                    IncludeBranded: false,
                    IncludeNewKeywords: false,
                    IncludeNoneBranded: true,
                    IncludeOrganic: true,
                    IncludePaid: false,
                    IncludeQuestions: false,
                    IncludeTrendingKeywords: true,
                    filter: "",
                    orderBy: "TotalShare desc",
                    timeGranularity: "Monthly",
                },
                width: "4",
                customAsset: false,
                options: {},
                family: "Website",
                title: "Organic KW - Non-branded & Trending",
                tooltip: "Organic KW - Non-branded & Trending.tooltip",
            },
        },
        {
            pos: {
                sizeX: 2,
                maxSizeY: 2,
                minSizeX: 2,
                maxSizeX: 4,
                row: 4,
                col: 0,
            },
            singleModeOnly: true,
            properties: {
                selectedChannel: "Direct",
                metric: "KeywordCompetitorsAffinity",
                webSource: "Desktop",
                duration: "1m",
                type: "Table",
                filters: {
                    includeSubDomains: "true",
                    timeGranularity: "Monthly",
                },
                width: "2",
                customAsset: false,
                options: {},
                family: "Website",
                title: "Competitive Overlap | Last Month",
                tooltip: "Search Competitive Overlap.tooltip",
                titleTemplate: "custom",
            },
        },
        {
            pos: {
                sizeX: 2,
                maxSizeY: 2,
                minSizeX: 2,
                maxSizeX: 4,
                row: 4,
                col: 2,
            },
            singleModeOnly: true,
            properties: {
                flexibleDuration: true,
                selectedChannel: "Direct",
                metric: "KeywordCompetitorsAffinity",
                webSource: "Desktop",
                duration: "12m",
                type: "Table",
                filters: {
                    includeSubDomains: "true",
                    timeGranularity: "Monthly",
                },
                width: "2",
                customAsset: false,
                family: "Website",
                options: {},
                title: "Competitive Overlap | Extended Period",
                tooltip: "Competitive Overlap.tooltip",
                titleTemplate: "custom",
            },
        },
    ],
};

export default dashboard;
