import { IDashboardTemplate } from "../DashboardTemplateService";
import { EFamilyTypes } from "../components/DashboardTemplatesConfig";
import { AssetsService } from "../../../../services/AssetsService";

const dashboard: IDashboardTemplate = {
    id: 8,
    title: "dashboard.templates.paidkeywordoptimization.title",
    description: "dashboard.templates.paidkeywordoptimization.description",
    descriptionLong: "dashboard.templates.paidkeywordoptimization.description.long",
    keyMetrics: "dashboard.templates.paidkeywordoptimization.keymetric",
    previewImage: AssetsService.assetUrl(
        "/images/dashboard/templates/PaidKeywordOptimization-preview.png",
    ),
    thumbnailImage: AssetsService.assetUrl(
        "/images/dashboard/templates/PaidKeywordOptimization-thumb.png",
    ),
    familyType: EFamilyTypes.Website,
    minItems: 2,
    maxItems: 5,
    widgets: [
        {
            pos: {
                sizeX: 2,
                sizeY: 1,
                maxSizeY: 2,
                minSizeX: 2,
                maxSizeX: 4,
                row: 0,
                col: 0,
            },
            properties: {
                selectedChannel: "Paid Search",
                metric: "ChannelsAnalysisByTrafficShare",
                webSource: "Desktop",
                duration: "1m",
                type: "MmxTrafficShareDashboard",
                filters: {
                    includeSubDomains: "true",
                    timeGranularity: "Daily",
                },
                width: "4",
                customAsset: false,
                family: "Website",
                options: {},
                title: "Paid Search Traffic | Last Month",
                tooltip: "Paid Search Traffic | Last Month.tooltip",
            },
        },
        {
            pos: {
                sizeX: 2,
                maxSizeY: 2,
                minSizeX: 2,
                maxSizeX: 4,
                row: 0,
                col: 2,
                sizeY: 1,
            },
            properties: {
                flexibleDuration: true,
                selectedChannel: "Paid Search",
                metric: "ChannelsAnalysisByTrafficShare",
                webSource: "Desktop",
                duration: "12m",
                type: "MmxTrafficShareDashboard",
                filters: {
                    includeSubDomains: "true",
                    timeGranularity: "Monthly",
                },
                width: "4",
                customAsset: false,
                family: "Website",
                options: {},
                title: "Paid Search Traffic | Extended Period",
                tooltip: "Paid Search Traffic.tooltip",
            },
        },
        {
            pos: {
                sizeX: 2,
                sizeY: 1,
                maxSizeY: 2,
                minSizeX: 2,
                maxSizeX: 4,
                row: 1,
                col: 0,
            },
            properties: {
                flexibleDuration: true,
                selectedChannel: "Paid Search",
                metric: "ChannelsAnalysisByBounceRate",
                webSource: "Desktop",
                duration: "6m",
                type: "MmxBounceRateDashboard",
                filters: {
                    includeSubDomains: "true",
                    timeGranularity: "Monthly",
                },
                width: "4",
                customAsset: false,
                family: "Website",
                options: {},
                title: "Bounce Rate - Paid Search",
                tooltip: "Bounce Rate - Paid Search.tooltip",
            },
        },
        {
            pos: {
                sizeX: 2,
                sizeY: 1,
                maxSizeY: 2,
                minSizeX: 2,
                maxSizeX: 4,
                row: 1,
                col: 2,
            },
            properties: {
                flexibleDuration: true,
                selectedChannel: "Paid Search",
                metric: "ChannelsAnalysisByAverageDuration",
                webSource: "Desktop",
                duration: "6m",
                type: "MmxVisitDurationDashboard",
                filters: {
                    includeSubDomains: "true",
                    timeGranularity: "Monthly",
                },
                width: "4",
                customAsset: false,
                family: "Website",
                options: {},
                title: "Avg. Visit Duration - Paid Search",
                tooltip: "Avg. Visit Duration - Paid Search.tooltip",
            },
        },
        {
            pos: {
                sizeX: 4,
                sizeY: 2,
                maxSizeY: 2,
                minSizeX: 2,
                maxSizeX: 4,
                row: 2,
                col: 0,
            },
            properties: {
                breakRowAfterCopies: true,
                multiple: true,
                multipleOverrides: {
                    pos: {
                        sizeY: 1,
                        sizeX: 2,
                    },
                    properties: {
                        title: "Website Top Paid Keywords",
                        filters: {
                            includeSubDomains: "true",
                            IncludeBranded: false,
                            IncludeNewKeywords: false,
                            IncludeNoneBranded: false,
                            IncludeOrganic: false,
                            IncludePaid: true,
                            IncludeQuestions: false,
                            IncludeTrendingKeywords: false,
                        },
                    },
                },
                selectedChannel: "Direct",
                metric: "NewSearchKeywords",
                webSource: "Desktop",
                duration: "3m",
                type: "TableSearchKeywordsDashboard",
                filters: {
                    includeSubDomains: "true",
                    IncludeBranded: false,
                    IncludeNewKeywords: false,
                    IncludeNoneBranded: false,
                    IncludeOrganic: false,
                    IncludePaid: true,
                    IncludeQuestions: false,
                    IncludeTrendingKeywords: false,
                    filter: "",
                    orderBy: "TotalShare desc",
                    timeGranularity: "Monthly",
                },
                width: "4",
                customAsset: false,
                family: "Website",
                options: {},
                title: "Competitors Battleground - Paid Keywords",
                tooltip: "",
                titleTemplate: "custom",
            },
        },
        {
            singleModeOnly: true,
            pos: {
                sizeX: 2,
                maxSizeY: 2,
                minSizeX: 2,
                maxSizeX: 4,
                row: 4,
                col: 0,
            },
            properties: {
                selectedChannel: "Direct",
                metric: "KeywordCompetitorsAffinity",
                webSource: "Desktop",
                duration: "1m",
                type: "Table",
                filters: {
                    includeSubDomains: "true",
                    timeGranularity: "Monthly",
                },
                width: "2",
                customAsset: false,
                options: {},
                family: "Website",
                title: "Competitive Overlap | Last Month",
                tooltip: "Search Competitive Overlap.tooltip",
                titleTemplate: "custom",
            },
        },
        {
            singleModeOnly: true,
            pos: {
                sizeX: 2,
                maxSizeY: 2,
                minSizeX: 2,
                maxSizeX: 4,
                row: 4,
                col: 2,
            },
            properties: {
                flexibleDuration: true,
                selectedChannel: "Direct",
                metric: "KeywordCompetitorsAffinity",
                webSource: "Desktop",
                duration: "12m",
                type: "Table",
                filters: {
                    includeSubDomains: "true",
                    timeGranularity: "Monthly",
                },
                width: "2",
                customAsset: false,
                family: "Website",
                options: {},
                title: "Competitive Overlap | Extended Period",
                tooltip: "Competitive Overlap.tooltip",
            },
        },
    ],
};
export default dashboard;
