import { IDashboardTemplate } from "../DashboardTemplateService";
import { EFamilyTypes } from "../components/DashboardTemplatesConfig";
import { AssetsService } from "../../../../services/AssetsService";

const dashboard: IDashboardTemplate = {
    id: 13,
    title: "dashboard.templates.seoperformance.title",
    description: "dashboard.templates.seoperformance.description",
    descriptionLong: "dashboard.templates.seoperformance.description.long",
    keyMetrics: "dashboard.templates.seoperformance.keymetric",
    previewImage: AssetsService.assetUrl("/images/dashboard/templates/SeoPerformance-preview.png"),
    thumbnailImage: AssetsService.assetUrl("/images/dashboard/templates/SeoPerformance-thumb.png"),
    familyType: EFamilyTypes.Website,
    minItems: 2,
    maxItems: 5,
    isNew: true,
    widgets: [
        {
            pos: {
                sizeX: 2,
                sizeY: 1,
                maxSizeY: 2,
                minSizeX: 2,
                maxSizeX: 4,
                row: 0,
                col: 0,
            },
            properties: {
                selectedChannel: "Organic Search",
                metric: "ChannelsAnalysisByTrafficShare",
                webSource: "Desktop",
                duration: "1m",
                type: "MmxTrafficShareDashboard",
                filters: {
                    includeSubDomains: "true",
                    timeGranularity: "Daily",
                },
                width: "4",
                customAsset: false,
                options: {},
                family: "Website",
                title: "SEO Traffic | Last Month",
                tooltip: "Traffic Share By Channel Organic Search.tooltip",
                titleTemplate: "custom",
            },
        },
        {
            pos: {
                sizeX: 2,
                maxSizeY: 2,
                minSizeX: 2,
                maxSizeX: 4,
                row: 0,
                col: 2,
                sizeY: 1,
            },
            properties: {
                flexibleDuration: true,
                selectedChannel: "Organic Search",
                metric: "ChannelsAnalysisByTrafficShare",
                webSource: "Desktop",
                duration: "12m",
                type: "MmxTrafficShareDashboard",
                filters: {
                    includeSubDomains: "true",
                    timeGranularity: "Monthly",
                },
                width: "4",
                customAsset: false,
                family: "Website",
                options: {},
                title: "SEO Traffic | Extended Period",
                tooltip: "SEO Traffic.tooltip",
                titleTemplate: "custom",
            },
        },
        {
            pos: {
                sizeX: 4,
                sizeY: 1,
                maxSizeY: 2,
                minSizeX: 2,
                maxSizeX: 4,
                row: 1,
                col: 0,
            },
            properties: {
                selectedChannel: "Direct",
                metric: "NewSearchKeywords",
                webSource: "Desktop",
                duration: "3m",
                type: "TableSearchKeywordsDashboard",
                filters: {
                    includeSubDomains: "true",
                    IncludeBranded: false,
                    IncludeNewKeywords: false,
                    IncludeNoneBranded: true,
                    IncludeOrganic: true,
                    IncludePaid: false,
                    IncludeQuestions: false,
                    IncludeTrendingKeywords: true,
                    filter: "",
                    orderBy: "TotalShare desc",
                    timeGranularity: "Monthly",
                },
                width: "4",
                customAsset: false,
                family: "Website",
                options: {},
                title: "Organic KW - Non-branded & Trending",
                tooltip: "Organic KW - Non-branded & Trending.tooltip",
                titleTemplate: "custom",
            },
        },
        {
            pos: {
                sizeX: 2,
                maxSizeY: 2,
                minSizeX: 2,
                maxSizeX: 4,
                row: 2,
                col: 0,
                sizeY: 2,
            },
            properties: {
                duration: "3m",
                family: "Website",
                type: "TableSearchKeywordsDashboard",
                webSource: "Desktop",
                metric: "NewSearchKeywords",
                filters: {
                    includeSubDomains: true,
                    timeGranularity: "Monthly",
                    IncludeOrganic: true,
                    IncludePaid: false,
                    IncludeBranded: false,
                    IncludeNoneBranded: true,
                    IncludeNewKeywords: false,
                    IncludeTrendingKeywords: false,
                    IncludeQuestions: false,
                    limits: "0-0.01",
                },
                options: {},
                tooltip: "Keyword Opportunities.tooltip",
                title: "Keyword Opportunities",
                titleTemplate: "custom",
            },
        },
        {
            pos: {
                sizeX: 2,
                maxSizeY: 2,
                minSizeX: 2,
                maxSizeX: 4,
                row: 2,
                col: 2,
                sizeY: 2,
            },
            properties: {
                duration: "3m",
                family: "Website",
                type: "TableSearchKeywordsDashboard",
                webSource: "Desktop",
                metric: "NewSearchKeywords",
                filters: {
                    includeSubDomains: true,
                    timeGranularity: "Monthly",
                    IncludeOrganic: true,
                    IncludePaid: false,
                    IncludeBranded: false,
                    IncludeNoneBranded: true,
                    IncludeNewKeywords: false,
                    IncludeTrendingKeywords: false,
                    IncludeQuestions: false,
                    limits: "0.01-0.2",
                },
                options: {},
                tooltip: "Keyword Losses.tooltip",
                title: "Keyword Losses",
                titleTemplate: "custom",
            },
        },
        {
            pos: {
                sizeX: 2,
                maxSizeY: 2,
                minSizeX: 2,
                maxSizeX: 4,
                row: 4,
                col: 0,
                sizeY: 2,
            },
            properties: {
                duration: "3m",
                family: "Website",
                type: "TableSearchKeywordsDashboard",
                webSource: "Desktop",
                metric: "NewSearchKeywords",
                filters: {
                    includeSubDomains: true,
                    timeGranularity: "Monthly",
                    IncludeOrganic: false,
                    IncludePaid: false,
                    IncludeBranded: false,
                    IncludeNoneBranded: false,
                    IncludeNewKeywords: false,
                    IncludeTrendingKeywords: false,
                    IncludeQuestions: false,
                    limits: "0.8-0.99",
                },
                options: {},
                tooltip: "Keyword Wins.tooltip",
                title: "Keyword Wins",
                titleTemplate: "custom",
            },
        },
        {
            pos: {
                sizeX: 2,
                maxSizeY: 2,
                minSizeX: 2,
                maxSizeX: 4,
                row: 4,
                col: 2,
                sizeY: 2,
            },
            properties: {
                duration: "3m",
                family: "Website",
                type: "TableSearchKeywordsDashboard",
                webSource: "Desktop",
                metric: "NewSearchKeywords",
                filters: {
                    includeSubDomains: true,
                    timeGranularity: "Monthly",
                    IncludeOrganic: false,
                    IncludePaid: false,
                    IncludeBranded: false,
                    IncludeNoneBranded: false,
                    IncludeNewKeywords: false,
                    IncludeTrendingKeywords: false,
                    IncludeQuestions: false,
                    limits: "0.2-0.6;0.2-0.6",
                },
                options: {},
                tooltip: "Highly Competitive Keywords.tooltip",
                title: "Highly Competitive Keywords",
                titleTemplate: "custom",
            },
        },
    ],
};

export default dashboard;
