'use es6';

export var CREATED_CRM_OBJECT = 'CREATED_CRM_OBJECT';
export var FETCH_CRM_OBJECTS_STARTED = 'FETCH_CRM_OBJECTS_STARTED';
export var FETCH_CRM_OBJECTS_SUCCEEDED = 'FETCH_CRM_OBJECTS_SUCCEEDED';
export var FETCH_CRM_OBJECTS_FAILED = 'FETCH_CRM_OBJECTS_FAILED';
export var DELETE_CRM_OBJECTS_STARTED = 'DELETE_CRM_OBJECTS_STARTED';
export var DELETE_CRM_OBJECTS_SUCCEEDED = 'DELETE_CRM_OBJECTS_SUCCEEDED';
export var DELETE_CRM_OBJECTS_FAILED = 'DELETE_CRM_OBJECTS_FAILED';
export var BATCH_DELETE_CRM_OBJECTS_STARTED = 'BATCH_DELETE_CRM_OBJECTS_STARTED';
export var BATCH_DELETE_CRM_OBJECTS_SUCCEEDED = 'BATCH_DELETE_CRM_OBJECTS_SUCCEEDED';
export var BATCH_DELETE_CRM_OBJECTS_FAILED = 'BATCH_DELETE_CRM_OBJECTS_FAILED';
export var UPDATE_CRM_OBJECTS_STARTED = 'UPDATE_CRM_OBJECTS_STARTED';
export var UPDATE_CRM_OBJECTS_SUCCEEDED = 'UPDATE_CRM_OBJECTS_SUCCEEDED';
export var UPDATE_CRM_OBJECTS_FAILED = 'UPDATE_CRM_OBJECTS_FAILED';
export var BATCH_UPDATE_CRM_OBJECTS_STARTED = 'BATCH_UPDATE_CRM_OBJECTS_STARTED';
export var BATCH_UPDATE_CRM_OBJECTS_SUCCEEDED = 'BATCH_UPDATE_CRM_OBJECTS_SUCCEEDED';
export var BATCH_UPDATE_CRM_OBJECTS_FAILED = 'BATCH_UPDATE_CRM_OBJECTS_FAILED';