//@ts-nocheck TS6133
/* eslint-disable @typescript-eslint/no-duplicate-imports */
import * as Types from 'owa-graph-schema';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type ItemRowFragmentFragment = (
  { __typename?: 'ItemRow' }
  & Pick<Types.ItemRow, 'ItemId' | 'AntispamUnauthenticatedSender' | 'Categories' | 'ConversationId' | 'DateTimeReceived' | 'DateTimeSent' | 'DisplayTo' | 'EntityNamesMap' | 'From' | 'HasAttachments' | 'HasProcessedSharepointLink' | 'IconIndex' | 'Importance' | 'InstanceKey' | 'IsDeliveryReceiptRequested' | 'IsDraft' | 'IsRead' | 'IsReadReceiptRequested' | 'IsExternalSender' | 'ItemClass' | 'LastModifiedTime' | 'LikeCount' | 'MentionedMe' | 'Preview' | 'ReceivedOrRenewTime' | 'ReturnTime' | 'Sensitivity' | 'Size' | 'SortOrderSource' | 'SpotlightIsVisible' | 'Subject' | 'SystemCategories'>
  & { Flag?: Types.Maybe<(
    { __typename?: 'Flag' }
    & Pick<Types.Flag, 'FlagStatus' | 'StartDate' | 'DueDate' | 'CompleteDate'>
  )>, ParentFolderId?: Types.Maybe<(
    { __typename?: 'FolderId' }
    & Pick<Types.FolderId, 'Id' | 'ChangeKey'>
  )> }
);

export const ItemRowFragmentFragmentDoc: DocumentNode<ItemRowFragmentFragment, unknown> = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"ItemRowFragment"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"ItemRow"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"ItemId"}},{"kind":"Field","name":{"kind":"Name","value":"AntispamUnauthenticatedSender"}},{"kind":"Field","name":{"kind":"Name","value":"Categories"}},{"kind":"Field","name":{"kind":"Name","value":"ConversationId"}},{"kind":"Field","name":{"kind":"Name","value":"DateTimeReceived"}},{"kind":"Field","name":{"kind":"Name","value":"DateTimeSent"}},{"kind":"Field","name":{"kind":"Name","value":"DisplayTo"}},{"kind":"Field","name":{"kind":"Name","value":"EntityNamesMap"}},{"kind":"Field","name":{"kind":"Name","value":"Flag"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"FlagStatus"}},{"kind":"Field","name":{"kind":"Name","value":"StartDate"}},{"kind":"Field","name":{"kind":"Name","value":"DueDate"}},{"kind":"Field","name":{"kind":"Name","value":"CompleteDate"}}]}},{"kind":"Field","name":{"kind":"Name","value":"From"}},{"kind":"Field","name":{"kind":"Name","value":"HasAttachments"}},{"kind":"Field","name":{"kind":"Name","value":"HasProcessedSharepointLink"}},{"kind":"Field","name":{"kind":"Name","value":"IconIndex"}},{"kind":"Field","name":{"kind":"Name","value":"Importance"}},{"kind":"Field","name":{"kind":"Name","value":"InstanceKey"}},{"kind":"Field","name":{"kind":"Name","value":"IsDeliveryReceiptRequested"}},{"kind":"Field","name":{"kind":"Name","value":"IsDraft"}},{"kind":"Field","name":{"kind":"Name","value":"IsRead"}},{"kind":"Field","name":{"kind":"Name","value":"IsReadReceiptRequested"}},{"kind":"Field","name":{"kind":"Name","value":"IsExternalSender"}},{"kind":"Field","name":{"kind":"Name","value":"ItemClass"}},{"kind":"Field","name":{"kind":"Name","value":"LastModifiedTime"}},{"kind":"Field","name":{"kind":"Name","value":"LikeCount"}},{"kind":"Field","name":{"kind":"Name","value":"MentionedMe"}},{"kind":"Field","name":{"kind":"Name","value":"ParentFolderId"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"Id"}},{"kind":"Field","name":{"kind":"Name","value":"ChangeKey"}}]}},{"kind":"Field","name":{"kind":"Name","value":"Preview"}},{"kind":"Field","name":{"kind":"Name","value":"ReceivedOrRenewTime"}},{"kind":"Field","name":{"kind":"Name","value":"ReturnTime"}},{"kind":"Field","name":{"kind":"Name","value":"Sensitivity"}},{"kind":"Field","name":{"kind":"Name","value":"Size"}},{"kind":"Field","name":{"kind":"Name","value":"SortOrderSource"}},{"kind":"Field","name":{"kind":"Name","value":"SpotlightIsVisible"}},{"kind":"Field","name":{"kind":"Name","value":"Subject"}},{"kind":"Field","name":{"kind":"Name","value":"SystemCategories"}}]}}]};