export const CREATE_PROJECT_MODAL = 'CREATE_PROJECT_MODAL'
export const CREATE_SPACE_MODAL = 'CREATE_SPACE_MODAL'
export const DELETE_PROJECT_MODAL = 'DELETE_PROJECT_MODAL'
export const SPACE_PERMISSIONS_WARNING_MODAL = 'SPACE_PERMISSIONS_WARNING_MODAL'

export const DIALOG_MODALS = [
  CREATE_PROJECT_MODAL,
  DELETE_PROJECT_MODAL
]
