export const PROJECT_COLORS = [
  '#00caff',
  '#00e1db',
  '#7a7cf1',
  '#ffca00'
]

export const PROJECT_SHAPE_NONE = 0
export const PROJECT_SHAPE_SQUARE_UP = 1
export const PROJECT_SHAPE_SQUARE_DOWN = 2
export const PROJECT_SHAPE_CIRCLE_UP = 3
export const PROJECT_SHAPE_CIRCLE_DOWN = 4
export const PROJECT_SHAPE_ARCH_UP = 5
export const PROJECT_SHAPE_ARCH_DOWN = 6

export const PROJECT_SHAPES = [
  PROJECT_SHAPE_NONE,
  PROJECT_SHAPE_SQUARE_UP,
  PROJECT_SHAPE_SQUARE_DOWN,
  PROJECT_SHAPE_CIRCLE_UP,
  PROJECT_SHAPE_CIRCLE_DOWN,
  PROJECT_SHAPE_ARCH_UP,
  PROJECT_SHAPE_ARCH_DOWN
]
