// Home Web BFF (implemented)
export const ACTIVATE_BOARD = '/home/v1/board/:id/activate'
export const ACTIVATE_FREEHAND = '/home/v1/freehand/:id/activate'
export const ACTIVATE_PROTOTYPE = '/home/v1/prototype/:id/activate' // blocked, currently broken
export const ACTIVATE_RHOMBUS = '/home/v1/rhombus/:id/activate'
export const ACTIVATE_SPEC = '/home/v1/spec/:id/activate'
export const ARCHIVE_BOARD = '/home/v1/board/:id/archive'
export const ARCHIVE_FREEHAND = '/home/v1/freehand/:id/archive'
export const ARCHIVE_PRESENTATION = '/home/v1/presentation/:id/archive'
export const ARCHIVE_PROTOTYPE = '/home/v1/prototype/:id/archive'
export const ARCHIVE_RHOMBUS = '/home/v1/rhombus/:id/archive'
export const ARCHIVE_SPEC = '/home/v1/spec/:id/archive'
export const CREATE_BOARD = '/home/v1/board'
export const CREATE_FREEHAND = '/home/v1/freehand'
export const CREATE_PROTOTYPE = '/home/v1/prototype'
export const CREATE_RHOMBUS = '/home/v1/rhombus'
export const CREATE_SPEC = '/home/v1/spec'
export const CREATE_SPACE = '/home/v1/space'
export const DELETE_BOARD = '/home/v1/board/:id'
export const DELETE_FREEHAND = '/home/v1/freehand/:id'
export const DELETE_PRESENTATION = '/home/v1/presentation/:id'
export const DELETE_PROTOTYPE = '/home/v1/prototype/:id'
export const DELETE_SPACE = '/home/v1/space/:cuid'
export const DELETE_SPEC = '/home/v1/spec/:id'
export const GET_ACCOUNT = '/home/v1/account'
export const GET_ACCOUNT_V2 = '/global-navigation-web/v1/account'
export const GET_ACCOUNT_PERMISSIONS = '/global-navigation-web/v1/account/permissions'
export const GET_CONFIG = '/home/v1/config'
export const GET_RECENTS = '/home/v1/recents'
export const ADD_DOCUMENTS_TO_SPACE = '/home/v1/space/:spaceCUID/documents'
export const REMOVE_DOCUMENTS_FROM_SPACE = '/home/v1/space/:spaceCUID/documents'
export const GET_TEAM = '/home/v1/team'
export const SET_ACCESS_MANAGEMENT = '/home/v1/:type/:id/accessSettings'
export const ADD_DOCUMENT_TO_SPACE = '/home/v1/space/:spaceID/documents/move'
export const GET_SUBSCRIPTION = '/global-navigation-web/v1/subscription'

// Space Details
export const GET_SPACE = '/home/v1/space/:id'
export const LEAVE_SPACE = '/home/v1/space/:id/leave'
export const UPDATE_SPACE = '/home/v1/space/:id'
export const VIEW_SPACE = '/home/v1/space/:cuid/view'
export const GET_ARCHIVED_SPACE_DOCUMENTS = '/home/v1/space/:id/archived-documents'

// Projects
export const GET_PROJECT = '/global-navigation-web/v1/project/:id'
export const UPDATE_PROJECT = '/global-navigation-web/v1/project/:id'
export const DELETE_PROJECT = '/global-navigation-web/v1/project/:id'
export const PROJECT_VIEWED = '/global-navigation-web/v1/project/:id/view'

// Discover API
export const DELETE_EXTERNAL = '/global-navigation-web/v1/resource/type/:type/id/:id'
export const DELETE_HARMONY = '/global-navigation-web/v1/harmony/:id'
export const GET_PERMISSIONS = '/global-navigation-web/v1/permissions'
export const GET_RESOURCES = '/global-navigation-web/v1/resources'
export const GET_THUMBNAILS = '/global-navigation-web/v1/assets'
export const SEARCH_RESOURCES = '/global-navigation-web/v2/search'
export const MOVE_DOCUMENTS_TO_SPACE_V2 = '/global-navigation-web/v2/move/documents/space/:spaceID'
export const GET_PROJECTS_DETAIL = '/global-navigation-web/v1/projects/ids'
export const GET_SPACES_DETAILS = '/global-navigation-web/v1/spaces/ids'
export const GET_SPACES_MEMBERS = '/global-navigation-web/v1/space/:spaceID/members'
export const GET_FREEHAND_METADATA = '/global-navigation-web/v1/freehands/metadata'
export const GET_SPACE_V2 = '/global-navigation-web/v2/space/:spaceId'
export const MOVE_DOCUMENTS_V3 = '/global-navigation-web/v3/move/documents'
