export const GET_CONFIG = '/home/v1/config'
export const GET_ACCOUNT = '/global-navigation-web/v1/account'
export const GET_MY_SPACES = '/global-navigation-web/v1/myspaces'
export const GET_PERMISSIONS = '/global-navigation-web/v1/spaces/permissions'
export const GET_SUBSCRIPTION = '/global-navigation-web/v1/subscription'
export const MOVE_DOCUMENTS = '/global-navigation-web/v1/move/documents/space/:id'
export const MOVE_DOCUMENTS_V3 = '/global-navigation-web/v3/move/documents'

export const CREATE_PROJECT = '/global-navigation-web/v1/project'
export const DELETE_PROJECT = '/global-navigation-web/v1/project/:id'
export const GET_PROJECT = '/global-navigation-web/v1/project/:id'
export const UPDATE_PROJECT = '/global-navigation-web/v1/project/:id'
export const CREATE_SPACE = '/global-navigation-web/v1/space'
export const GET_SPACE = '/global-navigation-web/v2/space/:spaceId'
export const GET_RESOURCES = '/global-navigation-web/v1/resources'
export const GET_PROJECTS_DETAIL = '/global-navigation-web/v1/projects/ids'
