'use es6';

export var SET_CALL_DATA = 'SET_CALL_DATA';
export var SET_CLIENT_STATUS = 'SET_CLIENT_STATUS';
export var SET_END_CALL_DATA = 'SET_END_CALL_DATA';
export var SET_SELECTED_FROM_NUMBER = 'SET_SELECTED_FROM_NUMBER';
export var SET_SELECTED_CONNECT_FROM_NUMBER = 'SET_SELECTED_CONNECT_FROM_NUMBER';
export var SET_SELECTED_CALL_METHOD = 'SET_SELECTED_CALL_METHOD';
export var SET_TO_NUMBER_IDENTIFIER = 'SET_TO_NUMBER_IDENTIFIER';
export var SET_CALL_END_STATUS = 'SET_CALL_END_STATUS';
export var RESET_CALL_DATA = 'RESET_CALL_DATA';
export var SET_SUBJECT = 'SET_SUBJECT';
export var SET_IS_QUEUE_TASK = 'SET_IS_QUEUE_TASK';
export var SET_THREAD_ID = 'SET_THREAD_ID';