import * as _ from "lodash";
import { DefaultCellHeaderRightAlign } from "../../../components/React/Table/headerCells";
import { ToggleHeaderCellRightAlign } from "../../../components/React/Table/headerCells/ToggleHeaderCellRightAlign";
import { ChartIds } from "components/Chart/src/components/annotations/Helpers/ChartIdsHelper";
const widgets = {
    single: [
        {
            type: "Custom",
            properties: {
                type: "Custom",
                resource: "sitesResource",
                method: "getSiteInfo",
                params: {
                    mainDomainOnly: false,
                    includeCrossData: true,
                },
                directive: "website-header",
                width: "12",
                height: "auto",
                loadingHeight: "262px",
                preloaderHeight: "262px",
                container: "/app/components/widget/containers/custom-widget-container.html",
                options: {
                    showTitle: false,
                    showTitleTooltip: false,
                    showSubtitle: false,
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    showLegend: false,
                    showOverflow: true,
                    noBoxShadow: true,
                    cssClass: "top-right-left-shadow",
                },
            },
        },
        {
            type: "SingleMetric",
            id: "WWOWebRanks",
            properties: {
                metric: "WebRanks",
                type: "SingleMetric",
                width: "4",
                height: "243px",
                loadingHeight: "246px",
                preloaderHeight: "246px",
                title: "wa.ao.ranks",
                options: {
                    showTitle: false,
                    showTitleTooltip: true,
                    titleType: "text",
                    showSubtitle: false,
                    showLegend: false,
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    widgetColors: "mobileWebColors",
                    titleClass: "page-widget-title",
                    showOverflow: true,
                    noTopPadding: true,
                    noBottomPadding: true,
                    overrideRowHeight: "80px",
                },
            },
        },
        {
            type: "AudienceOverviewVisits",
            properties: {
                metric: "EngagementVisits",
                type: "AudienceOverviewVisits",
                width: "4",
                height: "133px",
                preloaderHeight: "246px",
                title: "wa.ao.totalvisits",
                options: {
                    showTitle: true,
                    showTitleTooltip: true,
                    titleType: "text",
                    showSubtitle: true,
                    showLegend: false,
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    frameClass: "add-padding",
                    titleIcon: true,
                    titlePaddingBottom: "19px",
                    template:
                        "/app/components/single-metric/single-metric-website-overview-change.html",
                },
            },
        },
        {
            type: "PieChart",
            async: "true",
            properties: {
                metric: "EngagementDesktopVsMobileVisits",
                type: "PieChart",
                width: "4",
                height: "133px",
                preloaderHeight: "246px",
                title: "wa.ao.trafficshare",
                options: {
                    showTitle: true,
                    showTitleTooltip: true,
                    titleType: "text",
                    showSubtitle: true,
                    frameClass: "add-padding wwo-traffic-share",
                    showLegend: false,
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    widgetColors: "mobileWebColors",
                    widgetIcons: "mobileWebIcons",
                    titlePaddingBottom: "19px",
                    isMobileOrDesktopOnly: true,
                },
            },
        },
        {
            type: "EngagementOverviewKpi",
            properties: {
                metric: "EngagementOverview",
                type: "EngagementOverviewKpi",
                width: "12",
                height: "290px",
                loadingHeight: "290px",
                preloaderHeight: "290px",
                title: "wa.ao.trafficshare",
                options: {
                    showTitle: false,
                    showTitleTooltip: false,
                    titleType: "text",
                    showSubtitle: false,
                    showLegend: false,
                    showSettings: false,
                    showTopLine: false,
                    hideHeader: true,
                    showFrame: false,
                    canAddToDashboard: false,
                },
            },
        },
        {
            type: "WWOVisitsGraph",
            properties: {
                autoLoadTemplate: false,
                apiController: "WorldwideOverviewVisits",
                metric: "EngagementVisits",
                type: "WWOVisitsGraph",
                width: "12",
                height: "380px",
                graphHeight: "340px",
                preloaderHeight: "580px",
                title: "wwo.visits.graph",
                excelMetric: "EngagementOverview",
                trackName: "Over Time Graph/Engagement Overview",
                options: {
                    showTitle: false,
                    showTitleTooltip: true,
                    showSubtitle: false,
                    showLegend: true,
                    legendAlign: "left",
                    legendTop: -20,
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    noTopPadding: false,
                    floatingLegend: true,
                    legendData: true,
                    sumTooltipValues: true,
                    alignWithLegend: true,
                    titleClass: "page-widget-title",
                    dailyDataSince: "2015-10-01",
                    hideMarkersOnDaily: true,
                    useNewLegends: true,
                    ctaButton: "wwo.visits.over.time.button",
                    addToDashboardIconClass: "wwo-visits-graph-add-to-dashboard",
                    chartIdForAnnotations: ChartIds["WebsitePerformanceVisitsOverTime"],
                },
            },
            utilityGroups: [
                {
                    properties: {
                        className: "absoluteBottom-aline-to-add-to-dashboard",
                    },
                    utilities: [
                        {
                            id: "time-granularity",
                            properties: {},
                        },
                    ],
                },
            ],
        },
        {
            type: "WWOGeography",
            properties: {
                autoLoadTemplate: false,
                metric: "Geography",
                type: "WWOGeography",
                apiController: "WebsiteGeography",
                width: "12",
                height: "310px",
                loadingHeight: "310px",
                preloaderHeight: "430px",
                title: "ia.overview.geography",
                tooltip: "wwo.geography.tooltip",
                apiParams: {
                    pageSize: "5",
                    country: 999,
                },
                trackName: "Geography/Top 5 Countries/see more countries",
                options: {
                    showTitle: false,
                    showTitleTooltip: true,
                    titleType: "text",
                    showSubtitle: false,
                    titleIcon: true,
                    showLegend: false,
                    preserveLegendSpace: false,
                    showSettings: false,
                    showTopLine: false,
                    hideHeader: true,
                    showFrame: true,
                    desktopOnly: true,
                    worldWideOnly: true,
                    hideBorders: true,
                    overrideColumns: true,
                    ctaButton: "wwo.geography.button",
                },
                columns: [
                    {
                        name: "Country",
                        title: "Country",
                        type: "string",
                        format: "None",
                        sortable: "False",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "country-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: false,
                        ppt: {
                            // override the table column format when rendered in ppt
                            overrideFormat: "Country",
                        },
                    },
                    {
                        name: "Share",
                        title: "Traffic Share",
                        type: "double",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "traffic-share",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: "",
                        width: "",
                    },
                    {
                        name: "Change",
                        title: "Change",
                        type: "double",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "change-percentage",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "",
                        width: "80",
                    },
                ],
            },
        },
        {
            type: "WWOTrafficSourcesBar",
            properties: {
                autoLoadTemplate: false,
                metric: "TrafficSourcesOverview",
                type: "WWOTrafficSourcesBar",
                width: "12",
                height: "280px",
                loadingHeight: "306px",
                preloaderHeight: "390px",
                title: "metric.engagementTrafficSourcesOverview.title",
                excelMetric: "TrafficSourcesOverview",
                trackName: "Marketing Mix/Channels Overview",
                options: {
                    legendAlign: "left",
                    showTopLine: false,
                    showFrame: true,
                    showLegend: false,
                    titlePaddingBottom: "19px",
                    showSubtitle: true,
                    desktopOnly: true,
                    showSettings: false,
                    showTitle: true,
                    showTitleTooltip: true,
                    titleType: "text",
                    hideCategoriesIcons: true,
                    ctaButton: "wwo.traffic.sources.button",
                },
            },
        },
        {
            type: "WWOTopReferrals",
            properties: {
                autoLoadTemplate: false,
                metric: "TopReferrals",
                type: "WWOTopReferrals",
                width: "6",
                height: "222px",
                loadingHeight: "222px",
                preloaderHeight: "335px",
                title: "wa.wwo.topreferringwebsites.title",
                apiParams: {
                    pageSize: "5",
                    orderBy: "Share desc",
                },
                trackName: "Marketing Mix/Top Referring Websites",
                options: {
                    showTitle: true,
                    showTitleTooltip: true,
                    titleType: "text",
                    showSubtitle: true,
                    titlePaddingBottom: "19px",
                    desktopOnly: true,
                    showLegend: false,
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    hideHeader: true,
                    hideBorders: true,
                    overrideColumns: true,
                    ctaButton: "wwo.reffering.websites.button",
                },
                columns: [
                    {
                        name: "Domain",
                        title: "Domain",
                        type: "string",
                        format: "None",
                        sortable: "False",
                        isSorted: "False",
                        fixed: true,
                        sortDirection: "desc",
                        groupable: "True",
                        cellTemp: "website-tooltip-top-cell",
                        cellCls: "swTable-content",
                        headTemp: "",
                        totalCount: false,
                        tooltip: "",
                        width: 220,
                    },
                    {
                        name: "Share",
                        title: "Traffic Share",
                        type: "double",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "traffic-share",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: "",
                        minWidth: 150,
                    },
                    {
                        name: "Change",
                        title: "Change",
                        type: "double",
                        format: "percentagesign",
                        sortable: false,
                        isSorted: false,
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "change-percentage",
                        totalCount: false,
                        width: 85,
                    },
                ],
            },
        },
        {
            type: "WWOTopRefCategories",
            properties: {
                autoLoadTemplate: false,
                metric: "TopReferringCategories",
                type: "WWOTopRefCategories",
                width: "6",
                height: "222px",
                loadingHeight: "222px",
                preloaderHeight: "335px",
                title: "wa.wwo.topreferringcategories.title",
                trackName: "Marketing Mix/Top Referring Categories",
                options: {
                    showTitle: true,
                    showTitleTooltip: true,
                    titlePaddingBottom: "19px",
                    titleType: "text",
                    showSubtitle: true,
                    desktopOnly: true,
                    showLegend: false,
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    hideBorders: true,
                    hideHeader: true,
                    overrideColumns: true,
                    ctaButton: "wwo.referring.categories.button",
                },
                columns: [
                    {
                        name: "Category",
                        title: "Category",
                        type: "string",
                        fixed: true,
                        format: "None",
                        sortable: "False",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "referring-category-cell",
                        cellCls: "top-ref-category-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: "",
                        width: "220",
                    },
                    {
                        name: "Share",
                        title: "Traffic Share",
                        type: "double",
                        format: "percentagesign",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "traffic-share",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: "",
                        minWidth: 150,
                    },
                ],
            },
        },
        {
            type: "WWOSearchTraffic",
            async: "true",
            properties: {
                autoLoadTemplate: false,
                metric: "SearchOrganicPaidOverview",
                apiController: "TrafficSourcesSearch",
                type: "WWOSearchTraffic",
                width: "6",
                height: "222px",
                loadingHeight: "222px",
                preloaderHeight: "335px",
                title: "wa.wwo.trafficsourcessearch.title",
                trackName: "Search Traffic/Pie Chart",
                options: {
                    showTitle: true,
                    showTitleTooltip: true,
                    titleType: "text",
                    showSubtitle: true,
                    desktopOnly: true,
                    showLegend: false,
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    titlePaddingBottom: "19px",
                    legendConfig: {
                        align: "right",
                        verticalAlign: "middle",
                    },
                    widgetColors: "mobileWebColors",
                    widgetIcons: "organicPaidIcons",
                    ctaButton: "wwo.search.traffic.button",
                },
            },
        },
        {
            type: "WWOTopKeywordsTable",
            properties: {
                autoLoadTemplate: false,
                metric: "NewSearchKeywordsWebsiteOverview",
                apiController: "SearchKeywords",
                type: "WWOTopKeywordsTable",
                width: "6",
                height: "222px",
                loadingHeight: "222px",
                preloaderHeight: "335px",
                title: "wa.wwo.toporganic.title",
                apiParams: {
                    pageSize: "5",
                },
                trackName: "Marketing Mix/Top Search Terms",
                options: {
                    showTitle: true,
                    showTitleTooltip: false,
                    titleType: "text",
                    showSubtitle: true,
                    desktopOnly: true,
                    showLegend: false,
                    titlePaddingBottom: "19px",
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    hideHeader: true,
                    hideBorders: true,
                    ctaButton: "wwo.search.terms.button",
                },
            },
            utilityGroups: [
                {
                    properties: {
                        className: "titleInlineRow",
                    },
                    utilities: [
                        {
                            id: "dropdown",
                            properties: {
                                chosen: "0",
                                param: "filter",
                                column: "OP",
                                operator: "==",
                                type: "number",
                                trackingName: "Search term toggle",
                                minWidth: "100px",
                                width: "208px",
                                className: "title-dropdown-top-keywords-table",
                                emptySelect: false,
                                placeholder: null,
                                asBorderless: true,
                                keepEnabled: true,
                                values: [
                                    {
                                        disabled: false,
                                        text: "Organic",
                                        id: "0",
                                    },
                                    {
                                        disabled: false,
                                        text: "Paid",
                                        id: "1",
                                    },
                                ],
                            },
                        },
                    ],
                },
            ],
        },
        {
            type: "WWOSocialBar",
            properties: {
                autoLoadTemplate: false,
                metric: "TrafficSourcesSocial",
                type: "WWOSocialBar",
                width: "12",
                height: "280px",
                loadingHeight: "306px",
                preloaderHeight: "390px",
                title: "wa.wwo.social.title",
                excelMetric: "TrafficSourcesOverview",
                trackName: "Bar Chart/Traffic Sources Overview",
                options: {
                    legendAlign: "left",
                    showTopLine: false,
                    titlePaddingBottom: "19px",
                    showFrame: true,
                    showLegend: false,
                    showSubtitle: true,
                    desktopOnly: true,
                    showSettings: false,
                    showTitle: true,
                    showTitleTooltip: true,
                    titleType: "text",
                    hideCategoriesIcons: true,
                    ctaButton: "wwo.social.sources.button",
                },
            },
        },
        {
            type: "WWOTopAdNetwork",
            async: "true",
            properties: {
                autoLoadTemplate: false,
                metric: "TopAdNetworks",
                type: "WWOTopAdNetwork",
                width: "6",
                height: "222px",
                loadingHeight: "222px",
                preloaderHeight: "335px",
                title: "wa.wwo.displayadnetwork.title",
                apiParams: {
                    orderBy: "share desc",
                },
                trackName: "Display Ad Network/Pie Chart",
                options: {
                    showTitle: true,
                    showTitleTooltip: true,
                    titleType: "text",
                    showSubtitle: true,
                    desktopOnly: true,
                    showLegend: false,
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    titlePaddingBottom: "19px",
                    legendConfig: {
                        align: "right",
                        verticalAlign: "middle",
                    },
                    canAddToDashboard: true,
                    ctaButton: "wwo.display.ad.network.button",
                },
            },
        },
        {
            type: "WWOTopPublishersTable",
            properties: {
                autoLoadTemplate: false,
                metric: "TopIncomingAds",
                type: "WWOTopPublishersTable",
                width: "6",
                height: "222px",
                loadingHeight: "222px",
                preloaderHeight: "335px",
                title: "wa.wwo.toppublishers.title",
                apiParams: {
                    orderBy: "share desc",
                    pageSize: "5",
                },
                trackName: "Display Advertising/Top Publishers",
                options: {
                    showTitle: true,
                    showTitleTooltip: true,
                    titleType: "text",
                    showSubtitle: true,
                    desktopOnly: true,
                    showLegend: false,
                    titlePaddingBottom: "19px",
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    hideHeader: true,
                    hideBorders: true,
                    ctaButton: "wwo.top.publishers.button",
                    canAddToDashboard: true,
                },
            },
        },
        {
            type: "WWOTopDestinationReferrals",
            properties: {
                autoLoadTemplate: false,
                metric: "TrafficDestinationReferrals",
                type: "WWOTopDestinationReferrals",
                width: "6",
                height: "222px",
                loadingHeight: "222px",
                preloaderHeight: "335px",
                title: "wa.wwo.trafficdest.referrals.title",
                apiParams: {
                    pageSize: "5",
                },
                trackName: "Traffic Destination/Outgoing Links",
                options: {
                    showTitle: true,
                    showTitleTooltip: true,
                    titleType: "text",
                    showSubtitle: true,
                    showLegend: false,
                    titlePaddingBottom: "19px",
                    desktopOnly: true,
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    hideHeader: true,
                    hideBorders: true,
                    ctaButton: "wwo.trafficdest.referrals.button",
                    canAddToDashboard: true,
                },
            },
        },
        {
            type: "WWOOutgoingAdsTable",
            properties: {
                autoLoadTemplate: false,
                metric: "TrafficDestinationAds",
                type: "WWOOutgoingAdsTable",
                width: "6",
                height: "222px",
                loadingHeight: "222px",
                preloaderHeight: "335px",
                title: "wa.wwo.trafficdest.ads.title",
                apiParams: {
                    pageSize: "5",
                    orderBy: "TotalShare desc",
                },
                trackName: "Traffic Destination/Outgoing Ads",
                options: {
                    showTitle: true,
                    showTitleTooltip: true,
                    titleType: "text",
                    showSubtitle: true,
                    showLegend: false,
                    titlePaddingBottom: "19px",
                    desktopOnly: true,
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    hideHeader: true,
                    hideBorders: true,
                    ctaButton: "wwo.trafficdest.ads.button",
                    canAddToDashboard: true,
                },
            },
        },
    ],
    compare: [
        {
            id: "WebRanksGlobalTable",
            type: "WebRanksGlobalTable",
            properties: {
                metric: "WebRanksGlobal",
                type: "WebRanksGlobalTable",
                width: "4",
                height: "auto",
                loadingHeight: "118px",
                preloaderHeight: "211px",
                title: "wa.ao.ranks.global",
                trackName: "Website Header/Global Ranks",
                options: {
                    showTitle: true,
                    showTitleTooltip: true,
                    showSubtitle: true,
                    subtitleMarginBottom: "0px",
                    showLegend: false,
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    titleClass: "page-widget-title",
                    hideBorders: true,
                    hideDuration: true,
                    hideHeader: true,
                    trackName: "WebRank",
                    tableClass: "web-ranks-table",
                    overrideCountry: "999",
                },
            },
        },
        {
            id: "WebRanksCountryTable",
            type: "WebRanksCountryTable",
            properties: {
                metric: "WebRanksCountry",
                type: "WebRanksCountryTable",
                width: "4",
                height: "auto",
                loadingHeight: "118px",
                preloaderHeight: "211px",
                title: "wa.ao.ranks.country",
                trackName: "Website Header/Country Ranks",
                options: {
                    showTitle: true,
                    showTitleTooltip: true,
                    showSubtitle: true,
                    subtitleMarginBottom: "0px",
                    showLegend: false,
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    titleClass: "page-widget-title",
                    hideBorders: true,
                    hideDuration: true,
                    hideHeader: true,
                    trackName: "WebRank",
                    tableClass: "web-ranks-table",
                },
            },
        },
        {
            id: "WebRanksCategoryTable",
            type: "WebRanksCategoryTable",
            properties: {
                metric: "WebRanksCategory",
                type: "WebRanksCategoryTable",
                width: "4",
                height: "auto",
                loadingHeight: "118px",
                preloaderHeight: "211px",
                title: "wa.ao.ranks.category",
                trackName: "Website Header/Category Ranks",
                options: {
                    showTitle: true,
                    showTitleTooltip: true,
                    showSubtitle: true,
                    subtitleMarginBottom: "0px",
                    showLegend: false,
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    titleClass: "page-widget-title",
                    hideBorders: true,
                    hideDuration: true,
                    hideHeader: true,
                    trackName: "WebRank",
                    tableClass: "web-ranks-table",
                },
            },
        },
        {
            id: "EngagementVisitsTable",
            type: "Table",
            properties: {
                metric: "EngagementVisits",
                type: "Table",
                width: "6",
                height: "auto",
                loadingHeight: "132px",
                preloaderHeight: "241px",
                title: "wa.ao.compare.totalvisits",
                trackName: "Website Audience/Total Visits",
                options: {
                    showTitle: true,
                    showTitleTooltip: true,
                    titleType: "text",
                    showSubtitle: true,
                    showLegend: false,
                    preserveLegendSpace: false,
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    hideBorders: false,
                    hideRowsBorders: true,
                    titleIcon: true,
                },
                columns: [
                    {
                        field: "Domain",
                    },
                    {
                        field: "TotalVisits",
                        cellTemplate: "compare-progressbar",
                        headerComponent: ToggleHeaderCellRightAlign,
                        cellClass: "progress-bar-hide-on-medium-screen",
                        format: "minVisitsAbbr",
                        trackingName: "Website Audience/Total Visits",
                        fields: [
                            {
                                symbol: "widget-toggle-rank",
                                field: "TotalVisits",
                                format: "abbrNumber",
                                isActive: true,
                                trackingValue: "number",
                            },
                            {
                                symbol: "widget-toggle-percentage",
                                field: "ShareOfVisits",
                                format: "percentagesign",
                                isActive: false,
                                trackingValue: "percent",
                            },
                        ],
                    },
                ],
            },
        },
        {
            id: "EngagementDesktopVsMobileVisitsTable",
            type: "DesktopVSMobileWWO",
            properties: {
                metric: "EngagementDesktopVsMobileVisits",
                type: "DesktopVSMobileWWO",
                width: "6",
                loadingHeight: "132px",
                preloaderHeight: "241px",
                height: "auto",
                title: "wa.ao.trafficshare",
                trackName: "Website Audience/Traffic Share",
                options: {
                    showTitle: true,
                    showTitleTooltip: true,
                    titleType: "text",
                    showSubtitle: true,
                    showLegend: false,
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    hideBorders: false,
                    hideRowsBorders: true,
                },
            },
        },
        {
            id: "EngagementOverviewTable",
            type: "Table",
            properties: {
                metric: "EngagementOverview",
                type: "Table",
                width: "12",
                height: "auto",
                loadingHeight: "132px",
                preloaderHeight: "241px",
                title: "wa.ao.engagement",
                apiParams: {
                    includeLeaders: true,
                },
                trackName: "Website Audience/Engagement",
                options: {
                    showTitle: true,
                    showTitleTooltip: true,
                    titleType: "text",
                    showSubtitle: true,
                    showLegend: false,
                    preserveLegendSpace: false,
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    titleClass: "page-widget-title",
                    canAddToDashboard: true,
                },
                columns: [
                    {
                        field: "Domain",
                    },
                    {
                        field: "AvgMonthVisits",
                        cellTemplate: "leader-default-cell",
                        format: "minVisitsAbbr",
                        sortable: true,
                        headerCellTemplate: "leader-default-header-cell",
                        headerCellIconName: "visits",
                        cellClass: "leaders-cell",
                    },
                    {
                        field: "AvgVisitDuration",
                        cellTemplate: "leader-default-cell",
                        format: "time",
                        sortable: true,
                        headerCellTemplate: "leader-default-header-cell",
                        headerCellIconName: "avg-visit-duration",
                        cellClass: "leaders-cell",
                    },
                    {
                        field: "PagesPerVisit",
                        cellTemplate: "leader-default-cell",
                        format: "number:2",
                        sortable: true,
                        headerCellTemplate: "leader-default-header-cell",
                        headerCellIconName: "pages-per-visit",
                        cellClass: "leaders-cell",
                    },
                    {
                        field: "BounceRate",
                        cellTemplate: "leader-default-cell",
                        format: "percentagesign:2",
                        sortable: true,
                        headerCellTemplate: "leader-default-header-cell",
                        headerCellIconName: "bounce-rate-2",
                        inverted: true,
                        cellClass: "leaders-cell",
                    },
                ],
            },
        },
        {
            type: "WWOVisitsGraph",
            properties: {
                autoLoadTemplate: false,
                apiController: "WorldwideOverviewVisits",
                metric: "EngagementVisits",
                type: "WWOVisitsGraph",
                width: "12",
                height: "380px",
                graphHeight: "340px",
                preloaderHeight: "580px",
                title: "Visits over time",
                excelMetric: "EngagementOverview",
                trackName: "Over Time Graph/Engagement Overview",
                options: {
                    showTitle: false,
                    showTitleTooltip: false,
                    showSubtitle: false,
                    showLegend: true,
                    legendAlign: "left",
                    legendTop: -20,
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    noTopPadding: false,
                    floatingLegend: true,
                    legendData: true,
                    sumTooltipValues: true,
                    alignWithLegend: true,
                    titleClass: "page-widget-title",
                    dailyDataSince: "2015-10-01",
                    hideMarkersOnDaily: true,
                    useNewLegends: true,
                    ctaButton: "wwo.visits.over.time.button",
                    addToDashboardIconClass: "wwo-visits-graph-add-to-dashboard",
                    chartIdForAnnotations: ChartIds["WebsitePerformanceVisitsOverTime"],
                },
            },
            utilityGroups: [
                {
                    properties: {
                        className: "absoluteBottom-aline-to-add-to-dashboard",
                    },
                    utilities: [
                        {
                            id: "time-granularity",
                            properties: {},
                        },
                    ],
                },
            ],
        },
        {
            type: "WWOGeographySI",
            properties: {
                autoLoadTemplate: false,
                apiController: "WebsiteGeography",
                metric: "Geography",
                type: "WWOGeographySI",
                width: "12",
                height: "400px",
                loadingHeight: "400px",
                preloaderHeight: "450px",
                title: "ia.overview.geography",
                tooltip: "wwo.geography.tooltip",
                apiParams: {
                    pageSize: "5",
                    country: 999,
                },
                trackName: "Geography/Top 5 Countries/see more countries",
                options: {
                    showTitle: false,
                    showTitleTooltip: false,
                    titleType: "text",
                    showSubtitle: false,
                    showLegend: false,
                    preserveLegendSpace: false,
                    showSettings: false,
                    showTopLine: false,
                    hideHeader: false,
                    showFrame: true,
                    desktopOnly: true,
                    worldWideOnly: true,
                    hideBorders: false,
                    hideRowsBorders: true,
                    overrideColumns: true,
                    ctaButton: "wwo.geography.button",
                },
                columns: [
                    {
                        name: "Country",
                        title: "Country",
                        type: "string",
                        format: "None",
                        sortable: "False",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "country-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: false,
                        width: 230,
                        ppt: {
                            // override the table column format when rendered in ppt
                            overrideFormat: "Country",
                        },
                    },
                    {
                        name: "Share",
                        title: "Traffic Share",
                        type: "double",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "traffic-share",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: "",
                        width: "",
                    },
                    {
                        name: "ShareList",
                        title: "Group Traffic Share Split",
                        type: "double[]",
                        format: "percentagesign",
                        sortable: false,
                        isSorted: false,
                        sortDirection: "desc",
                        groupable: false,
                        cellTemp: "group-traffic-share",
                        headTemp: "",
                        totalCount: false,
                        tooltip: "",
                        width: "",
                    },
                ],
            },
        },
        {
            type: "WWOTrafficSourcesBar",
            properties: {
                autoLoadTemplate: false,
                metric: "TrafficSourcesOverview",
                type: "WWOTrafficSourcesBar",
                width: "12",
                height: "270px",
                loadingHeight: "214px",
                preloaderHeight: "373px",
                title: "metric.engagementTrafficSourcesOverview.title",
                excelMetric: "TrafficSourcesOverview",
                options: {
                    legendAlign: "left",
                    showTopLine: false,
                    showFrame: true,
                    showLegend: true,
                    titlePaddingBottom: "19px",
                    showSubtitle: true,
                    desktopOnly: true,
                    showSettings: false,
                    showTitle: true,
                    showTitleTooltip: true,
                    titleType: "text",
                    hideCategoriesIcons: true,
                    ctaButton: "wwo.traffic.sources.button",
                    useNewLegends: true,
                },
                trackName: "Bar Chart/Traffic Sources Overview",
            },
        },
        {
            type: "WWOTopReferrals",
            properties: {
                autoLoadTemplate: false,
                metric: "TopReferrals",
                type: "WWOTopReferrals",
                width: "12",
                height: "250px",
                loadingHeight: "250px",
                preloaderHeight: "413px",
                title: "wa.wwo.topreferringwebsites.title",
                apiParams: {
                    pageSize: "5",
                    orderBy: "TotalShare desc",
                    IncludeCrossData: true,
                },
                trackName: "Marketing Mix/Top Referring Websites",
                options: {
                    showTitle: true,
                    showTitleTooltip: true,
                    titleType: "text",
                    showSubtitle: true,
                    titlePaddingBottom: "19px",
                    desktopOnly: true,
                    showLegend: true,
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    hideHeader: false,
                    hideBorders: false,
                    hideRowsBorders: true,
                    overrideColumns: true,
                    ctaButton: "wwo.reffering.websites.button",
                    useBulletLegends: true,
                },
                columns: [
                    {
                        name: "Domain",
                        title: "Domain",
                        type: "string",
                        format: "None",
                        sortable: false,
                        isSorted: false,
                        fixed: true,
                        sortDirection: "desc",
                        groupable: false,
                        cellTemp: "website-tooltip-top-cell",
                        cellCls: "swTable-content",
                        totalCount: false,
                        width: 220,
                    },
                    {
                        name: "Category",
                        title: "Category",
                        type: "string",
                        format: "None",
                        sortable: "False",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "category-cell-container",
                        totalCount: "False",
                        tooltip: false,
                        width: 220,
                    },
                    {
                        name: "Share",
                        title: "Traffic Share",
                        type: "double",
                        format: "percentagesign",
                        sortable: false,
                        isSorted: false,
                        sortDirection: "desc",
                        groupable: false,
                        cellTemp: "traffic-share",
                        totalCount: false,
                        minWidth: 150,
                    },
                    {
                        name: "ShareList",
                        title: "Group Traffic Share Split",
                        type: "double[]",
                        format: "percentagesign",
                        sortable: false,
                        isSorted: false,
                        sortDirection: "desc",
                        groupable: false,
                        cellTemp: "group-traffic-share",
                        headTemp: "",
                        totalCount: false,
                        tooltip: "",
                        minWidth: 250,
                    },
                ],
            },
        },
        {
            type: "WWOTopKeywordsTable",
            properties: {
                autoLoadTemplate: false,
                type: "WWOTopKeywordsTable",
                metric: "NewSearchKeywordsWebsiteOverview",
                apiController: "SearchKeywords",
                width: "12",
                height: "250px",
                loadingHeight: "250px",
                preloaderHeight: "413px",
                title: "wa.wwo.toporganic.title",
                apiParams: {
                    pageSize: "5",
                },
                trackName: "Marketing Mix/Top Search Terms",
                options: {
                    showTitle: true,
                    showTitleTooltip: false,
                    titleType: "text",
                    showSubtitle: true,
                    desktopOnly: true,
                    showLegend: true,
                    titlePaddingBottom: "19px",
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    hideHeader: false,
                    hideBorders: false,
                    hideRowsBorders: true,
                    ctaButton: "wwo.search.terms.button",
                    useBulletLegends: true,
                },
            },
            utilityGroups: [
                {
                    properties: {
                        className: "titleInlineRow",
                    },
                    utilities: [
                        {
                            id: "dropdown",
                            properties: {
                                chosen: "0",
                                param: "filter",
                                column: "OP",
                                operator: "==",
                                type: "number",
                                trackingName: "Search term toggle",
                                minWidth: "100px",
                                width: "208px",
                                className: "title-dropdown-top-keywords-table",
                                showSearch: false,
                                emptySelect: false,
                                placeholder: null,
                                asBorderless: true,
                                keepEnabled: true,
                                values: [
                                    {
                                        disabled: false,
                                        // icon: "sw-icon-search",
                                        text: "Organic",
                                        id: "0",
                                    },
                                    {
                                        disabled: false,
                                        // icon: "sw-icon-widget-coins",
                                        text: "Paid",
                                        id: "1",
                                    },
                                ],
                            },
                        },
                    ],
                },
            ],
        },
        {
            type: "WWOSocialBar",
            properties: {
                autoLoadTemplate: false,
                metric: "TrafficSourcesSocial",
                type: "WWOSocialBar",
                width: "12",
                height: "280px",
                loadingHeight: "214px",
                preloaderHeight: "373px",
                title: "wa.wwo.social.title",
                excelMetric: "TrafficSourcesOverview",
                options: {
                    legendAlign: "left",
                    showTopLine: false,
                    titlePaddingBottom: "19px",
                    showFrame: true,
                    showLegend: true,
                    showSubtitle: true,
                    desktopOnly: true,
                    showSettings: false,
                    showTitle: true,
                    showTitleTooltip: true,
                    titleType: "text",
                    hideCategoriesIcons: true,
                    ctaButton: "wwo.social.sources.button",
                    useNewLegends: true,
                },
                trackName: "Bar Chart/Traffic Sources Overview",
            },
        },
        {
            type: "WWOTopPublishersTable",
            properties: {
                autoLoadTemplate: false,
                metric: "TopIncomingAds",
                type: "WWOTopPublishersTable",
                width: "12",
                height: "250px",
                loadingHeight: "250px",
                preloaderHeight: "413px",
                title: "wa.wwo.toppublishers.title",
                apiParams: {
                    orderBy: "share desc",
                    pageSize: "5",
                },
                trackName: "Display Advertising/Top Publishers",
                options: {
                    showTitle: true,
                    showTitleTooltip: true,
                    titleType: "text",
                    showSubtitle: true,
                    desktopOnly: true,
                    showLegend: true,
                    titlePaddingBottom: "19px",
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    hideHeader: false,
                    hideBorders: false,
                    hideRowsBorders: true,
                    ctaButton: "wwo.top.publishers.button",
                    canAddToDashboard: true,
                    useBulletLegends: true,
                },
            },
        },
        {
            type: "WWOTopAdNetworksTable",
            properties: {
                autoLoadTemplate: false,
                metric: "TopAdNetworks",
                type: "WWOTopAdNetworksTable",
                width: "12",
                height: "250px",
                loadingHeight: "250px",
                preloaderHeight: "413px",
                title: "wa.wwo.displayadnetwork.title",
                apiParams: {
                    orderBy: "share desc",
                    pageSize: "5",
                },
                trackName: "Display Ad Network/Table",
                options: {
                    showTitle: true,
                    showTitleTooltip: true,
                    titleType: "text",
                    showSubtitle: true,
                    desktopOnly: true,
                    showLegend: true,
                    titlePaddingBottom: "19px",
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    hideHeader: false,
                    hideBorders: false,
                    hideRowsBorders: true,
                    ctaButton: "wwo.top.displayads.button",
                    canAddToDashboard: true,
                    useBulletLegends: true,
                },
            },
        },
        {
            type: "WWOOutgoingAdsTable",
            properties: {
                autoLoadTemplate: false,
                metric: "TrafficDestinationAds",
                type: "WWOOutgoingAdsTable",
                width: "12",
                height: "250px",
                loadingHeight: "250px",
                preloaderHeight: "413px",
                title: "wa.wwo.trafficdest.ads.title",
                trackName: "Traffic Destination/Top Ads Destination",
                apiParams: {
                    pageSize: "5",
                    orderBy: "TotalShare desc",
                },
                options: {
                    showTitle: true,
                    showTitleTooltip: true,
                    titleType: "text",
                    showSubtitle: true,
                    showLegend: true,
                    titlePaddingBottom: "19px",
                    desktopOnly: true,
                    showSettings: false,
                    showTopLine: false,
                    showFrame: true,
                    hideHeader: false,
                    hideBorders: false,
                    hideRowsBorders: true,
                    ctaButton: "wwo.trafficdest.ads.button",
                    canAddToDashboard: true,
                    useBulletLegends: true,
                },
            },
        },
    ],
};

const augmentWidgetsWithAddToDashboard = (widgets: any[], hideAddToDashboard: boolean) => {
    return widgets.map((widget) => {
        widget.properties.hideAddToDashboard = hideAddToDashboard;
        return widget;
    });
};

const worldWideOverviewWidgets = (mode, reject, hideAddToDashboard) => {
    const widgetsResult = reject
        ? _.cloneDeep(_.reject(widgets[mode], reject))
        : _.cloneDeep(widgets[mode]);

    return augmentWidgetsWithAddToDashboard(widgetsResult, hideAddToDashboard);
};

export default worldWideOverviewWidgets;
