// This is an autogenerated file. Do not manually edit.
// Run `node packages/framework/owa-fluent-icons-svg/updateIcons.js` to update the icons in this package
import * as React from 'react';
import { registerIcons } from '@fluentui/style-utilities';
import { createSvgIcon } from '../createSvgIcon';

export default 'ArrowDownRegular';

const ArrowDownRegular = createSvgIcon({
    Svg: props => (
        <svg {...props} viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
            <path d="M8.5 2.5a.5.5 0 10-1 0v9.7L3.87 8.17a.5.5 0 10-.74.66l4.5 5a.5.5 0 00.74 0l4.5-5a.5.5 0 00-.74-.66L8.5 12.2V2.5z" />
        </svg>
    ),
    displayName: 'ArrowDownRegular',
});

registerIcons({
    icons: {
        ArrowDownRegular: <ArrowDownRegular />,
    },
});
