// This is an autogenerated file. Do not manually edit.
// Run `node packages/framework/owa-fluent-icons-svg/updateIcons.js` to update the icons in this package
import * as React from 'react';
import { registerIcons } from '@fluentui/style-utilities';
import { createSvgIcon } from '../createSvgIcon';

export default 'ArrowCircleRightRegular';

const ArrowCircleRightRegular = createSvgIcon({
    Svg: props => (
        <svg {...props} viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
            <path d="M8.85 10.85l2.5-2.5a.5.5 0 000-.7l-2.5-2.5a.5.5 0 10-.7.7L9.79 7.5H5a.5.5 0 000 1h4.8l-1.65 1.65a.5.5 0 00.7.7zM15 8A7 7 0 111 8a7 7 0 0114 0zm-7 6A6 6 0 108 2a6 6 0 000 12z" />
        </svg>
    ),
    displayName: 'ArrowCircleRightRegular',
});

registerIcons({
    icons: {
        ArrowCircleRightRegular: <ArrowCircleRightRegular />,
    },
});
