// This is an autogenerated file. Do not manually edit.
// Run `node packages/framework/owa-fluent-icons-svg/updateIcons.js` to update the icons in this package
import * as React from 'react';
import { registerIcons } from '@fluentui/style-utilities';
import { createSvgIcon } from '../createSvgIcon';

export default 'AttachRegular';

const AttachRegular = createSvgIcon({
    Svg: props => (
        <svg {...props} viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
            <path d="M3.26 8.7l4.6-4.59a2.5 2.5 0 013.53 3.54l-5.3 5.3a1 1 0 01-1.42-1.41l5.3-5.3a.5.5 0 00-.7-.71l-5.3 5.3a2 2 0 102.82 2.83l5.3-5.3A3.5 3.5 0 007.16 3.4L2.55 8a.5.5 0 10.7.7z" />
        </svg>
    ),
    displayName: 'AttachRegular',
});

registerIcons({
    icons: {
        AttachRegular: <AttachRegular />,
    },
});
