// This is an autogenerated file. Do not manually edit.
// Run `node packages/framework/owa-fluent-icons-svg/updateIcons.js` to update the icons in this package
import * as React from 'react';
import { registerIcons } from '@fluentui/style-utilities';
import { createSvgIcon } from '../createSvgIcon';

export default 'CalendarCheckmarkRegular';

const CalendarCheckmarkRegular = createSvgIcon({
    Svg: props => (
        <svg {...props} viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
            <path d="M11.5 2A2.5 2.5 0 0114 4.5v1.76A5.48 5.48 0 0010.5 5H13v-.5c0-.83-.67-1.5-1.5-1.5h-7C3.67 3 3 3.67 3 4.5V5h7.5c-1.18 0-2.27.37-3.16 1H3v5.5c0 .83.67 1.5 1.5 1.5h1.1c.18.36.4.7.66 1H4.5A2.5 2.5 0 012 11.5v-7A2.5 2.5 0 014.5 2h7z" />
            <path d="M15 10.5a4.5 4.5 0 11-9 0 4.5 4.5 0 019 0zm-2.15-1.85a.5.5 0 00-.7 0L9.5 11.29l-.65-.64a.5.5 0 00-.7.7l1 1c.2.2.5.2.7 0l3-3a.5.5 0 000-.7z" />
        </svg>
    ),
    displayName: 'CalendarCheckmarkRegular',
});

registerIcons({
    icons: {
        CalendarCheckmarkRegular: <CalendarCheckmarkRegular />,
    },
});
