// This is an autogenerated file. Do not manually edit.
// Run `node packages/framework/owa-fluent-icons-svg/updateIcons.js` to update the icons in this package
import * as React from 'react';
import { registerIcons } from '@fluentui/style-utilities';
import { createSvgIcon } from '../createSvgIcon';

export default 'ImportantFilled';

const ImportantFilled = createSvgIcon({
    Svg: props => (
        <svg {...props} viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
            <path d="M5.96 4.46a2.07 2.07 0 114.08 0l-.86 4.56a1.2 1.2 0 01-2.36 0l-.86-4.56z" />
            <path d="M9.5 12.5a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0z" />
        </svg>
    ),
    displayName: 'ImportantFilled',
});

registerIcons({
    icons: {
        ImportantFilled: <ImportantFilled />,
    },
});
