// This is an autogenerated file. Do not manually edit.
// Run `node packages/framework/owa-fluent-icons-svg/updateIcons.js` to update the icons in this package
import * as React from 'react';
import { registerIcons } from '@fluentui/style-utilities';
import { createSvgIcon } from '../createSvgIcon';

export default 'OrganizationRegular';

const OrganizationRegular = createSvgIcon({
    Svg: props => (
        <svg {...props} viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
            <path d="M8 2a1.5 1.5 0 100 3 1.5 1.5 0 000-3zM5.5 3.5a2.5 2.5 0 113 2.45V7.5h2c.83 0 1.5.67 1.5 1.5v1.05a2.5 2.5 0 11-1 0V9a.5.5 0 00-.5-.5h-5A.5.5 0 005 9v1.05a2.5 2.5 0 11-1 0V9c0-.83.67-1.5 1.5-1.5h2V5.95a2.5 2.5 0 01-2-2.45zm-1 7.5a1.5 1.5 0 100 3 1.5 1.5 0 000-3zm7 0a1.5 1.5 0 100 3 1.5 1.5 0 000-3z" />
        </svg>
    ),
    displayName: 'OrganizationRegular',
});

registerIcons({
    icons: {
        OrganizationRegular: <OrganizationRegular />,
    },
});
