// This is an autogenerated file. Do not manually edit.
// Run `node packages/framework/owa-fluent-icons-svg/updateIcons.js` to update the icons in this package
import * as React from 'react';
import { registerIcons } from '@fluentui/style-utilities';
import { createSvgIcon } from '../createSvgIcon';

export default 'ProhibitedRegular';

const ProhibitedRegular = createSvgIcon({
    Svg: props => (
        <svg {...props} viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
            <path d="M8 3a5 5 0 00-3.87 8.16l7.03-7.03A4.98 4.98 0 008 3zm3.87 1.84l-7.03 7.03a5 5 0 007.04-7.04zM2 8a6 6 0 1112 0A6 6 0 012 8z" />
        </svg>
    ),
    displayName: 'ProhibitedRegular',
});

registerIcons({
    icons: {
        ProhibitedRegular: <ProhibitedRegular />,
    },
});
