// This is an autogenerated file. Do not manually edit.
// Run `node packages/framework/owa-fluent-icons-svg/updateIcons.js` to update the icons in this package
import * as React from 'react';
import { registerIcons } from '@fluentui/style-utilities';
import { createSvgIcon } from '../createSvgIcon';

export default 'RibbonRegular';

const RibbonRegular = createSvgIcon({
    Svg: props => (
        <svg {...props} viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
            <path d="M8 1a5 5 0 00-3 9v4.5a.5.5 0 00.76.43L8 13.58l2.24 1.35a.5.5 0 00.76-.43V10a5 5 0 00-3-9zM4 6a4 4 0 118 0 4 4 0 01-8 0zm6 4.58v3.04l-1.74-1.05a.5.5 0 00-.52 0L6 13.62v-3.04a4.98 4.98 0 004 0z" />
        </svg>
    ),
    displayName: 'RibbonRegular',
});

registerIcons({
    icons: {
        RibbonRegular: <RibbonRegular />,
    },
});
