// This is an autogenerated file. Do not manually edit.
// Run `node packages/framework/owa-fluent-icons-svg/updateIcons.js` to update the icons in this package
import * as React from 'react';
import { registerIcons } from '@fluentui/style-utilities';
import { createSvgIcon } from '../createSvgIcon';

export default 'TagFilled';

const TagFilled = createSvgIcon({
    Svg: props => (
        <svg {...props} viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
            <path d="M2.54 7.33L7.29 2.6c.38-.37.89-.58 1.42-.59L11.97 2A2 2 0 0114 4.01l-.03 3.38a2 2 0 01-.59 1.4L8.7 13.44c-.78.78-2.06.78-2.84 0l-3.31-3.28a2 2 0 010-2.83zm7.72-1.67c.3.3.8.3 1.1 0 .3-.3.3-.78 0-1.08a.77.77 0 00-1.1 0c-.3.3-.3.78 0 1.08z" />
        </svg>
    ),
    displayName: 'TagFilled',
});

registerIcons({
    icons: {
        TagFilled: <TagFilled />,
    },
});
