import { getTableBaseClass } from "components/widget/widgetUtils";
import TopPublishersDomainHOC from "../../components/topPublishersDomainHOC";

const getWidgetConfig = (params) => ({
    properties: {
        type: "Table",
        width: "4",
        title: "analysis.source.ads.overview.toppublishers",
        tooltip: "analysis.source.ads.overview.toppublishers.tooltip",
        height: "215px",
        apiController: "WebsiteDisplayAds",
        apiParams: {
            metric: "WebsiteAdsPublishers",
            pageSize: "5",
            orderBy: "TotalShare desc",
        },
        options: {
            noBoxShadow: true,
            showTitle: true,
            showTitleTooltip: true,
            titlePaddingBottom: "0px",
            titleClass: "u-no-margin",
            height: "204px",
            titleType: "text",
            showSubtitle: false,
            showLegend: false,
            showSettings: false,
            showTopLine: false,
            showFrame: true,
            titleIcon: false,
            cssClass: "swTable--simple",
            dashboardSubtitleMarginBottom: "-4",
            hideBorders: true,
            overrideColumns: true,
            frameClass: "responsive",
            trackName: "Top Publishers",
        },
        columns: [
            {
                name: "Domain",
                title: "",
                type: "string",
                format: "None",
                sortable: "False",
                isSorted: "False",
                sortDirection: "desc",
                groupable: "False",
                cellComponent: TopPublishersDomainHOC,
                headTemp: "",
                totalCount: "False",
                width: "",
            },
            {
                name: "Share",
                title: "Traffic Share",
                type: "string",
                format: "percentagesign",
                headerCellClass: "ads-traffic-share-headercell",
                sortable: false,
                isSorted: false,
                isLink: true,
                sortDirection: "desc",
                groupable: false,
                cellTemp: "traffic-share",
                // headTemp: "",
                totalCount: false,
                tooltip: false,
                width: "53%",
            },
        ],
    },
});

export default getTableBaseClass(getWidgetConfig);
