'use es6';

export var FETCH_VIEWS_STARTED = 'FETCH_VIEWS_STARTED';
export var FETCH_VIEWS_SUCCEEDED = 'FETCH_VIEWS_SUCCEEDED';
export var FETCH_VIEWS_FAILED = 'FETCH_VIEWS_FAILED';
export var SAVE_VIEW_STARTED = 'SAVE_VIEW_STARTED';
export var SAVE_VIEW_SUCCEEDED = 'SAVE_VIEW_SUCCEEDED';
export var SAVE_VIEW_FAILED = 'SAVE_VIEW_FAILED';
export var DELETE_VIEW_STARTED = 'DELETE_VIEW_STARTED';
export var DELETE_VIEW_SUCCEEDED = 'DELETE_VIEW_SUCCEEDED';
export var DELETE_VIEW_FAILED = 'DELETE_VIEW_FAILED';
export var CREATE_VIEW_STARTED = 'CREATE_VIEW_STARTED';
export var CREATE_VIEW_SUCCEEDED = 'CREATE_VIEW_SUCCEEDED';
export var CREATE_VIEW_FAILED = 'CREATE_VIEW_FAILED';
export var FILTERS_CHANGED = 'FILTERS_CHANGED';
export var RESET_VIEW = 'RESET_VIEW';
export var COLUMNS_CHANGED = 'COLUMNS_CHANGED';
export var SORT_CHANGED = 'SORT_CHANGED';
export var CACHE_VIEWS = 'CACHE_VIEWS';