import { ViewConfig } from "./predefinedViews";

function createPredefinedView(columns: string[]): ViewConfig {
    return columns.reduce((config, column, index) => {
        return {
            ...config,
            [column]: {
                visible: true,
                index: index + 1,
            },
        };
    }, {});
}

export const defaultView = {
    top_geo_country: { visible: true, index: 1 },
    visits: { visible: true, index: 2 },
    monthly_visits_change_yoy: { visible: true, index: 3 },
    monthly_visits_change_mom: { visible: true, index: 4 },
    trend: { visible: true, index: 5 },
    bounce_rate: { visible: true, index: 6 },
    direct_desktop_visits_share: { visible: true, index: 7 },
    company_country: { visible: true, index: 8 },
    company_name: { visible: true, index: 9 },
    paid_search_desktop_visits_share: { visible: true, index: 10 },
    displayads_desktop_visits_share: { visible: true, index: 11 },
    site_category: { visible: true, index: 12 },
    desktop_vs_mobileweb_visits_share: { visible: true, index: 13 },
    male_vs_female_share: { visible: true, index: 14 },
    age_group_18_24_share: { visible: true, index: 15 },
    age_group_65_share: { visible: true, index: 16 },
};

export const siteOptimizationView = {
    visits: { visible: true, index: 1 },
    monthly_visits_change_mom: { visible: true, index: 2 },
    monthly_visits_change_yoy: { visible: true, index: 3 },
    trend: { visible: true, index: 4 },
    bounce_rate: { visible: true, index: 5 },
    pages_per_visit: { visible: true, index: 6 },
    avg_visit_duration: { visible: true, index: 7 },
    direct_desktop_visits_share: { visible: true, index: 8 },
    company_country: { visible: true, index: 9 },
    desktop_vs_mobileweb_visits_share: { visible: true, index: 10 },
    male_vs_female_share: { visible: true, index: 11 },
    paid_search_desktop_visits_share: { visible: true, index: 12 },
    paid_search_visits_change_yoy: { visible: true, index: 13 },
    displayads_desktop_visits_share: { visible: true, index: 14 },
    display_ads_visits_change_yoy: { visible: true, index: 15 },
    site_category: { visible: true, index: 18 },
};

export const channelOptimizationView = {
    top_geo_country: { visible: true, index: 1 },
    visits: { visible: true, index: 2 },
    monthly_visits_change_yoy: { visible: true, index: 3 },
    trend: { visible: true, index: 4 },
    desktop_vs_mobileweb_visits_share: { visible: true, index: 5 },
    paid_search_desktop_visits_share: { visible: true, index: 6 },
    paid_search_visits_change_yoy: { visible: true, index: 7 },
    displayads_desktop_visits_share: { visible: true, index: 8 },
    display_ads_visits_change_yoy: { visible: true, index: 9 },
    direct_desktop_visits_share: { visible: true, index: 10 },
    direct_visits_change_yoy: { visible: true, index: 11 },
    referrals_desktop_visits_share: { visible: true, index: 12 },
    referrals_visits_change_yoy: { visible: true, index: 13 },
    social_desktop_visits_share: { visible: true, index: 14 },
    organic_search_desktop_visits_share: { visible: true, index: 15 },
    organic_search_visits_change_yoy: { visible: true, index: 16 },
    social_visits_change_yoy: { visible: true, index: 17 },
    mail_desktop_visits_share: { visible: true, index: 18 },
    mail_visits_change_yoy: { visible: true, index: 19 },
    site_category: { visible: true, index: 20 },
    male_vs_female_share: { visible: true, index: 21 },
    age_group_18_24_share: { visible: true, index: 22 },
    age_group_25_34_share: { visible: true, index: 23 },
    age_group_35_44_share: { visible: true, index: 24 },
    age_group_45_54_share: { visible: true, index: 25 },
    age_group_55_64_share: { visible: true, index: 26 },
    age_group_65_share: { visible: true, index: 27 },
    company_country: { visible: true, index: 28 },
};

export const publishersView = {
    top_geo_country: { visible: true, index: 1 },
    pageviews: { visible: true, index: 2 },
    total_page_views_change_mom: { visible: true, index: 3 },
    total_page_views_change_yoy: { visible: true, index: 4 },
    bounce_rate: { visible: true, index: 5 },
    avg_visit_duration: { visible: true, index: 6 },
    pages_per_visit: { visible: true, index: 7 },
    trend: { visible: true, index: 8 },
    site_category: { visible: true, index: 9 },
    direct_desktop_visits_share: { visible: true, index: 10 },
    direct_visits_change_yoy: { visible: true, index: 11 },
    social_desktop_visits_share: { visible: true, index: 12 },
    social_desktop_visits: { visible: true, index: 13 },
    desktop_vs_mobileweb_visits_share: { visible: true, index: 14 },
    male_vs_female_share: { visible: true, index: 15 },
    age_group_18_24_share: { visible: true, index: 16 },
    age_group_25_34_share: { visible: true, index: 17 },
    age_group_35_44_share: { visible: true, index: 18 },
    age_group_45_54_share: { visible: true, index: 19 },
    age_group_55_64_share: { visible: true, index: 20 },
    age_group_65_share: { visible: true, index: 21 },
    company_country: { visible: true, index: 22 },
};

export const nonCountryTrafficView = createPredefinedView([
    "rank",
    "top_geo_country",
    "functionality",
    "site_category",
    "company_country",
    "company_name",
    "company_address",
    "company_city",
    "company_state",
    "company_zip",
    "company_employee_range",
    "company_revenue_range",
    "company_phone",
    "company_email",
]);

// const fullConfig: Record<string, { visible: boolean, index: number }> = {
//     age_group_18_24_share: { visible: false, index: 0 },
//     age_group_25_34_share: { visible: false, index: 0 },
//     age_group_35_44_share: { visible: false, index: 0 },
//     age_group_45_54_share: { visible: false, index: 0 },
//     age_group_55_64_share: { visible: false, index: 0 },
//     age_group_65_share: { visible: false, index: 0 },
//     avg_visit_duration: { visible: false, index: 0 },
//     bounce_rate: { visible: false, index: 0 },
//     category: { visible: false, index: 0 },
//     company_address: { visible: false, index: 0 },
//     company_city: { visible: false, index: 0 },
//     company_country: { visible: false, index: 0 },
//     company_email: { visible: false, index: 0 },
//     company_employee_range: { visible: false, index: 0 },
//     company_name: { visible: false, index: 0 },
//     company_phone: { visible: false, index: 0 },
//     company_revenue_range: { visible: false, index: 0 },
//     company_state: { visible: false, index: 0 },
//     company_zip: { visible: false, index: 0 },
//     country: { visible: false, index: 0 },
//     desktop_avg_visit_duration: { visible: false, index: 0 },
//     desktop_bounce_rate: { visible: false, index: 0 },
//     desktop_monthly_visits_change_mom: { visible: false, index: 0 },
//     desktop_monthly_visits_change_yoy: { visible: false, index: 0 },
//     desktop_pages_per_visit: { visible: false, index: 0 },
//     desktop_pageviews: { visible: false, index: 0 },
//     desktop_total_page_views_change_mom: { visible: false, index: 0 },
//     desktop_total_page_views_change_yoy: { visible: false, index: 0 },
//     desktop_unique_monthly_visitors_change_mom: { visible: false, index: 0 },
//     desktop_unique_monthly_visitors_change_yoy: { visible: false, index: 0 },
//     desktop_visitors: { visible: false, index: 0 },
//     desktop_visits: { visible: false, index: 0 },
//     desktop_vs_mobileweb_visits_share: { visible: false, index: 0 },
//     direct_desktop_visits: { visible: false, index: 0 },
//     direct_desktop_visits_share: { visible: false, index: 0 },
//     direct_visits_change_mom: { visible: false, index: 0 },
//     direct_visits_change_yoy: { visible: false, index: 0 },
//     display_ads_visits_change_mom: { visible: false, index: 0 },
//     display_ads_visits_change_yoy: { visible: false, index: 0 },
//     displayads_desktop_visits: { visible: false, index: 0 },
//     displayads_desktop_visits_share: { visible: false, index: 0 },
//     functionality: { visible: false, index: 0 },
//     has_adsense: { visible: false, index: 0 },
//     mail_desktop_visits: { visible: false, index: 0 },
//     mail_desktop_visits_share: { visible: false, index: 0 },
//     mail_visits_change_mom: { visible: false, index: 0 },
//     mail_visits_change_yoy: { visible: false, index: 0 },
//     male_vs_female_share: { visible: false, index: 0 },
//     mobile_monthly_visits_change_mom: { visible: false, index: 0 },
//     mobile_monthly_visits_change_yoy: { visible: false, index: 0 },
//     mobile_total_page_views_change_mom: { visible: false, index: 0 },
//     mobile_total_page_views_change_yoy: { visible: false, index: 0 },
//     mobile_unique_monthly_visitors_change_mom: { visible: false, index: 0 },
//     mobile_unique_monthly_visitors_change_yoy: { visible: false, index: 0 },
//     mobileweb_avg_visit_duration: { visible: false, index: 0 },
//     mobileweb_bounce_rate: { visible: false, index: 0 },
//     mobileweb_pages_per_visit: { visible: false, index: 0 },
//     mobileweb_pageviews: { visible: false, index: 0 },
//     mobileweb_visitors: { visible: false, index: 0 },
//     mobileweb_visits: { visible: false, index: 0 },
//     monthly_visits_change_mom: { visible: false, index: 0 },
//     monthly_visits_change_yoy: { visible: false, index: 0 },
//     organic_search_desktop_visits: { visible: false, index: 0 },
//     organic_search_desktop_visits_share: { visible: false, index: 0 },
//     organic_search_visits_change_mom: { visible: false, index: 0 },
//     organic_search_visits_change_yoy: { visible: false, index: 0 },
//     pages_per_visit: { visible: false, index: 0 },
//     pageviews: { visible: false, index: 0 },
//     paid_search_desktop_visits: { visible: false, index: 0 },
//     paid_search_desktop_visits_share: { visible: false, index: 0 },
//     paid_search_visits_change_mom: { visible: false, index: 0 },
//     paid_search_visits_change_yoy: { visible: false, index: 0 },
//     rank: { visible: false, index: 0 },
//     referrals_desktop_visits: { visible: false, index: 0 },
//     referrals_desktop_visits_share: { visible: false, index: 0 },
//     referrals_visits_change_mom: { visible: false, index: 0 },
//     referrals_visits_change_yoy: { visible: false, index: 0 },
//     site: { visible: false, index: 0 },
//     site_category: { visible: false, index: 0 },
//     social_desktop_visits: { visible: false, index: 0 },
//     social_desktop_visits_share: { visible: false, index: 0 },
//     social_visits_change_mom: { visible: false, index: 0 },
//     social_visits_change_yoy: { visible: false, index: 0 },
//     top_geo_country: { visible: false, index: 0 },
//     total_page_views_change_mom: { visible: false, index: 0 },
//     total_page_views_change_yoy: { visible: false, index: 0 },
//     trend: { visible: false, index: 0 },
//     unique_monthly_visitors_change_mom: { visible: false, index: 0 },
//     unique_monthly_visitors_change_yoy: { visible: false, index: 0 },
//     visitors: { visible: false, index: 0 },
//     visits: { visible: false, index: 0 },
// };
