'use es6';

export var RECORD_CARD_FETCH_STARTED = 'RECORD_CARD_FETCH_STARTED';
export var RECORD_CARD_FETCH_SUCCEEDED = 'RECORD_CARD_FETCH_SUCCEEDED';
export var RECORD_CARD_FETCH_FAILED = 'RECORD_CARD_FETCH_FAILED';