'use es6';

export var CONSENT_TO_PROCESS = 'CONSENT_TO_PROCESS';
export var CONSENT_TO_PROCESS_SUCCEEDED = 'CONSENT_TO_PROCESS_SUCCEEDED';
export var CONSENT_TO_PROCESS_FAILED = 'CONSENT_TO_PROCESS_FAILED';
export var CONSENT_TO_COMMUNICATE = 'CONSENT_TO_COMMUNICATE';
export var CONSENT_TO_COMMUNICATE_SUCCEEDED = 'CONSENT_TO_COMMUNICATE_SUCCEEDED';
export var CONSENT_TO_COMMUNICATE_FAILED = 'CONSENT_TO_COMMUNICATE_FAILED';
export var DISMISS_CONSENT_TO_COMMUNICATE_ERROR = 'DISMISS_CONSENT_TO_COMMUNICATE_ERROR';