'use es6';

export var ASSOCIATED_COMPANY_ID_PROPERTY = 'associatedcompanyid';
export var CONTACT_TO_PRIMARY_COMPANY_ASSOCIATION_ID = '0-1';
export var PRIMARY_COMPANY_TO_CONTACT_ASSOCIATION_ID = '0-2';
export var GENERAL_CONTACT_TO_DEAL_ASSOCIATION_ID = '0-4';
export var GENERAL_CONTACT_TO_TICKET_ASSOCIATION_ID = '0-15';
export var PRIMARY_COMPANY_TO_DEAL_ASSOCIATION_ID = '0-6';
export var PRIMARY_COMPANY_TO_TICKET_ASSOCIATION_ID = '0-25';
export var GENERAL_DEAL_TO_CONTACT_ASSOCIATION_ID = '0-3';
export var DEAL_TO_PRIMARY_COMPANY_ASSOCIATION_ID = '0-5';
export var GENERAL_DEAL_TO_TICKET_ASSOCIATION_ID = '0-27';
export var GENERAL_TICKET_TO_CONTACT_ASSOCIATION_ID = '0-16';
export var TICKET_TO_PRIMARY_COMPANY_ASSOCIATION_ID = '0-26';
export var GENERAL_TICKET_TO_DEAL_ASSOCIATION_ID = '0-28'; // Associations that are gated behind the flexible-associations gate

export var GENERAL_CONTACT_TO_COMPANY_ASSOCIATION_ID = '0-279';
export var GENERAL_COMPANY_TO_CONTACT_ASSOCIATION_ID = '0-280';
export var GENERAL_COMPANY_TO_DEAL_ASSOCIATION_ID = '0-342';
export var GENERAL_COMPANY_TO_TICKET_ASSOCIATION_ID = '0-340';
export var GENERAL_DEAL_TO_COMPANY_ASSOCIATION_ID = '0-341';
export var GENERAL_TICKET_TO_COMPANY_ASSOCIATION_ID = '0-339';