export enum BlueShirtChatEvents {
    BLUE_SHIRT_AGENT_LAUNCH_CHAT = "BLUE_SHIRT_AGENT_LAUNCH_CHAT",
    BLUE_SHIRT_AGENT_IFRAME_PDP_STYLE = "BLUE_SHIRT_AGENT_IFRAME_PDP_STYLE",
    BLUE_SHIRT_AGENT_UPDATE_CURRENT_CHAT = "BLUE_SHIRT_AGENT_UPDATE_CURRENT_CHAT",
    BLUE_SHIRT_AGENT_CHAT_STATE_CHANGE = "BLUE_SHIRT_AGENT_CHAT_STATE_CHANGE",
    BLUE_SHIRT_AGENT_UPDATE_SALESFORCE_CONFIG = "BLUE_SHIRT_AGENT_UPDATE_SALESFORCE_CONFIG",
    BLUE_SHIRT_AGENT_RESTORE_CHAT = "BLUE_SHIRT_AGENT_RESTORE_CHAT",
    BLUE_SHIRT_AGENT_SYNC_STATE = "BLUE_SHIRT_AGENT_SYNC_STATE",
}

export const blueShirtChatStateSessionKey = "blueShirtChatState";
