'use es6';

export var ATTACHMENT_UPLOAD_PROGRESS = 'ATTACHMENT_UPLOAD_PROGRESS';
export var ATTACHMENT_UPLOAD_START = 'ATTACHMENT_UPLOAD_START';
export var ATTACHMENT_UPLOAD_COMPLETE = 'ATTACHMENT_UPLOAD_COMPLETE';
export var REMOVE_ATTACHMENT = 'REMOVE_ATTACHMENT';
export var CLEAR_ATTACHMENTS = 'CLEAR_ATTACHMENTS';
export var ATTACHMENT_ERROR = 'ATTACHMENT_ERROR';
export var DISMISS_ATTACHMENTS_ERROR = 'DISMISS_ATTACHMENTS_ERROR';