'use es6';

import _defineProperty from "@babel/runtime/helpers/esm/defineProperty";

var _BET_ACTIVITY_TYPE_GR, _BET_ACTIVITY_TYPE_VA;

export var CALL_GROUP = 'CALL_GROUP';
export var CONNECT_CALL_GROUP = 'CONNECT_CALL_GROUP';
export var NON_CALL_GROUP = 'NON_CALL_GROUP';
export var PROSPECTING_CALL_GROUP = 'PROSPECTING_CALL_GROUP';
export var ACCOUNT_ASSIST = 'ACCOUNT_ASSIST';
export var AGENCY_SERVICES = 'AGENCY_SERVICES';
export var BILLING_ISSUE = 'BILLING_ISSUE';
export var BOOKED_MEETING = 'BOOKED_MEETING';
export var BUILD_LEAD_LIST = 'BUILD_LEAD_LIST';
export var BUSINESS_STRATEGY = 'BUSINESS_STRATEGY';
export var CALL = 'CALL';
export var CALL_NO_VOICEMAIL = 'CALL_NO_VOICEMAIL';
export var CANCELLATION = 'CANCELLATION';
export var CLIENT_DELIVERY = 'CLIENT_DELIVERY';
export var CONSULTING = 'CONSULTING';
export var CULTURE = 'CULTURE';
export var DATA_CONSULT = 'DATA_CONSULT';
export var DEAL_COACHING = 'DEAL_COACHING';
export var DEAL_CUSTOMIZATION = 'DEAL_CUSTOMIZATION';
export var DEAL_REVIEW = 'DEAL_REVIEW';
export var DEAL_SPECIFIC_COACHING = 'DEAL_SPECIFIC_COACHING';
export var DEMO = 'DEMO';
export var DEVELOPING_SALES_PLAN = 'DEVELOPING_SALES_PLAN';
export var DISCOVERY = 'DISCOVERY';
export var EMAIL = 'EMAIL';
export var ESCALATION = 'ESCALATION';
export var FOLLOW_UP_CALL_SCHEDULED = 'FOLLOW_UP_CALL_SCHEDULED';
export var FOLLOW_UP_LATER = 'FOLLOW_UP_LATER';
export var FULL_DEMO = 'FULL_DEMO';
export var GOAL_SETTING = 'GOAL_SETTING';
export var GROWTH_PLAN = 'GROWTH_PLAN';
export var IMA = 'IMA';
export var IMPLEMENTATION = 'IMPLEMENTATION';
export var INTERNAL_TRANSITION = 'INTERNAL_TRANSITION';
export var IN_PERSON = 'IN_PERSON';
export var KICK_OFF = 'KICK_OFF';
export var MARKED_DOMAIN_AS_BAD_FIT = 'MARKED_DOMAIN_AS_BAD_FIT';
export var OBJECTION_NO_MEETING = 'OBJECTION_NO_MEETING';
export var OFFICE_HOURS = 'OFFICE_HOURS';
export var OFFLINE_SOLUTION_RESEARCH = 'OFFLINE_SOLUTION_RESEARCH';
export var ONSITE_MEETING = 'ONSITE_MEETING';
export var ONSITE_PREPERATION = 'ONSITE_PREPERATION';
export var PARTIAL_DEMO = 'PARTIAL_DEMO';
export var PBE_REVIEW = 'PBE_REVIEW';
export var POST_SALE_SERVICES_SUPPORT = 'POST_SALE_SERVICES_SUPPORT';
export var PRICING_PACKAGING = 'PRICING_PACKAGING';
export var PROACTIVE_PROSPECTING = 'PROACTIVE_PROSPECTING';
export var PRODUCT_CONSULT = 'PRODUCT_CONSULT';
export var QSR_DELIVERED = 'QSR_DELIVERED';
export var QUARTERLY_REVIEW = 'QUARTERLY_REVIEW';
export var QUESTIONNAIRE_REVIEW_CALL = 'QUESTIONNAIRE_REVIEW_CALL';
export var REFERRAL_TO_ANOTHER_CONTACT = 'REFERRAL_TO_ANOTHER_CONTACT';
export var RESELL_DISCUSSION = 'RESELL_DISCUSSION';
export var RESEARCH_FOLLOW_UP = 'RESEARCH_FOLLOW_UP';
export var RFP = 'RFP';
export var SALES_COACHING = 'SALES_COACHING';
export var SELLING_OPPORTUNITY = 'SELLING_OPPORTUNITY';
export var SE_DISCOVERY = 'SE_DISCOVERY';
export var SMALL_GROUP_COACHING = 'SMALL_GROUP_COACHING';
export var TECH_CONSULT = 'TECH_CONSULT';
export var VOICEMAIL = 'VOICEMAIL';
export var BET_ACTIVITY_TYPE_GROUPS_VALUES = (_BET_ACTIVITY_TYPE_GR = {}, _defineProperty(_BET_ACTIVITY_TYPE_GR, CALL_GROUP, 'Call'), _defineProperty(_BET_ACTIVITY_TYPE_GR, CONNECT_CALL_GROUP, 'Connect Call'), _defineProperty(_BET_ACTIVITY_TYPE_GR, NON_CALL_GROUP, 'Non Call'), _defineProperty(_BET_ACTIVITY_TYPE_GR, PROSPECTING_CALL_GROUP, 'Prospecting Call'), _BET_ACTIVITY_TYPE_GR);
export var BET_ACTIVITY_TYPE_VALUES = (_BET_ACTIVITY_TYPE_VA = {}, _defineProperty(_BET_ACTIVITY_TYPE_VA, ACCOUNT_ASSIST, 'Account assist'), _defineProperty(_BET_ACTIVITY_TYPE_VA, AGENCY_SERVICES, 'Define agency services'), _defineProperty(_BET_ACTIVITY_TYPE_VA, BILLING_ISSUE, 'Billing or contract issue'), _defineProperty(_BET_ACTIVITY_TYPE_VA, BOOKED_MEETING, 'Booked meeting'), _defineProperty(_BET_ACTIVITY_TYPE_VA, BUILD_LEAD_LIST, 'Building a lead list'), _defineProperty(_BET_ACTIVITY_TYPE_VA, BUSINESS_STRATEGY, 'Business strategy'), _defineProperty(_BET_ACTIVITY_TYPE_VA, CALL, 'Call'), _defineProperty(_BET_ACTIVITY_TYPE_VA, CANCELLATION, 'Cancellation/Downgrade'), _defineProperty(_BET_ACTIVITY_TYPE_VA, CLIENT_DELIVERY, 'Client delivery'), _defineProperty(_BET_ACTIVITY_TYPE_VA, CONSULTING, 'Consulting'), _defineProperty(_BET_ACTIVITY_TYPE_VA, CULTURE, 'Hiring/HR/Culture'), _defineProperty(_BET_ACTIVITY_TYPE_VA, DATA_CONSULT, 'Data consult'), _defineProperty(_BET_ACTIVITY_TYPE_VA, DEAL_COACHING, 'Deal coaching'), _defineProperty(_BET_ACTIVITY_TYPE_VA, DEAL_CUSTOMIZATION, 'Deal customization'), _defineProperty(_BET_ACTIVITY_TYPE_VA, DEAL_REVIEW, 'Deal review'), _defineProperty(_BET_ACTIVITY_TYPE_VA, DEAL_SPECIFIC_COACHING, 'Deal specific coaching'), _defineProperty(_BET_ACTIVITY_TYPE_VA, DEMO, 'Demo'), _defineProperty(_BET_ACTIVITY_TYPE_VA, DEVELOPING_SALES_PLAN, 'Developing sales plan'), _defineProperty(_BET_ACTIVITY_TYPE_VA, DISCOVERY, 'Discovery Call'), _defineProperty(_BET_ACTIVITY_TYPE_VA, ESCALATION, 'Escalation'), _defineProperty(_BET_ACTIVITY_TYPE_VA, FOLLOW_UP_CALL_SCHEDULED, 'Follow-up call scheduled'), _defineProperty(_BET_ACTIVITY_TYPE_VA, FOLLOW_UP_LATER, 'Follow up later'), _defineProperty(_BET_ACTIVITY_TYPE_VA, FULL_DEMO, 'Full demo'), _defineProperty(_BET_ACTIVITY_TYPE_VA, GOAL_SETTING, 'Goal Setting'), _defineProperty(_BET_ACTIVITY_TYPE_VA, GROWTH_PLAN, 'Growth Plan Call'), _defineProperty(_BET_ACTIVITY_TYPE_VA, IMA, 'IMA'), _defineProperty(_BET_ACTIVITY_TYPE_VA, IMPLEMENTATION, 'Implementation'), _defineProperty(_BET_ACTIVITY_TYPE_VA, INTERNAL_TRANSITION, 'Internal transition'), _defineProperty(_BET_ACTIVITY_TYPE_VA, IN_PERSON, 'In person'), _defineProperty(_BET_ACTIVITY_TYPE_VA, KICK_OFF, 'Kick-off'), _defineProperty(_BET_ACTIVITY_TYPE_VA, MARKED_DOMAIN_AS_BAD_FIT, 'Marked domain as bad fit'), _defineProperty(_BET_ACTIVITY_TYPE_VA, OBJECTION_NO_MEETING, 'Objection - no meeting'), _defineProperty(_BET_ACTIVITY_TYPE_VA, OFFICE_HOURS, 'Office hours'), _defineProperty(_BET_ACTIVITY_TYPE_VA, OFFLINE_SOLUTION_RESEARCH, 'Offline solution research'), _defineProperty(_BET_ACTIVITY_TYPE_VA, ONSITE_MEETING, 'Onsite meeting'), _defineProperty(_BET_ACTIVITY_TYPE_VA, ONSITE_PREPERATION, 'Onsite preperation'), _defineProperty(_BET_ACTIVITY_TYPE_VA, PARTIAL_DEMO, 'Partial demo'), _defineProperty(_BET_ACTIVITY_TYPE_VA, PBE_REVIEW, 'PBE review'), _defineProperty(_BET_ACTIVITY_TYPE_VA, POST_SALE_SERVICES_SUPPORT, 'Post sale services support'), _defineProperty(_BET_ACTIVITY_TYPE_VA, PRICING_PACKAGING, 'Pricing & packaging'), _defineProperty(_BET_ACTIVITY_TYPE_VA, PROACTIVE_PROSPECTING, 'Proactive prospecting'), _defineProperty(_BET_ACTIVITY_TYPE_VA, PRODUCT_CONSULT, 'Product consult'), _defineProperty(_BET_ACTIVITY_TYPE_VA, QSR_DELIVERED, 'QSR delivered'), _defineProperty(_BET_ACTIVITY_TYPE_VA, QUARTERLY_REVIEW, 'Quarterly business review'), _defineProperty(_BET_ACTIVITY_TYPE_VA, QUESTIONNAIRE_REVIEW_CALL, 'Questionnaire review call'), _defineProperty(_BET_ACTIVITY_TYPE_VA, REFERRAL_TO_ANOTHER_CONTACT, 'Referral to another contact'), _defineProperty(_BET_ACTIVITY_TYPE_VA, RESEARCH_FOLLOW_UP, 'Research/Follow up'), _defineProperty(_BET_ACTIVITY_TYPE_VA, RESELL_DISCUSSION, 'Resell & retainers discussion'), _defineProperty(_BET_ACTIVITY_TYPE_VA, RFP, 'RFP'), _defineProperty(_BET_ACTIVITY_TYPE_VA, SALES_COACHING, 'Sales coaching'), _defineProperty(_BET_ACTIVITY_TYPE_VA, SELLING_OPPORTUNITY, 'Selling opportunity'), _defineProperty(_BET_ACTIVITY_TYPE_VA, SE_DISCOVERY, 'Discovery'), _defineProperty(_BET_ACTIVITY_TYPE_VA, SMALL_GROUP_COACHING, 'Small group coaching'), _defineProperty(_BET_ACTIVITY_TYPE_VA, TECH_CONSULT, 'Tech consult'), _BET_ACTIVITY_TYPE_VA);
export var BDR_CONTACT_ACTIVITY_TYPES = {
  PROSPECTING_CALL_GROUP: [FOLLOW_UP_CALL_SCHEDULED, REFERRAL_TO_ANOTHER_CONTACT, MARKED_DOMAIN_AS_BAD_FIT],
  CONNECT_CALL_GROUP: [BOOKED_MEETING, OBJECTION_NO_MEETING, FOLLOW_UP_LATER]
};
export var SERVICE_ENGINEER_ACTIVITY_TYPES = [ACCOUNT_ASSIST, BILLING_ISSUE, CANCELLATION, CLIENT_DELIVERY, CONSULTING, AGENCY_SERVICES, SE_DISCOVERY, ESCALATION, GROWTH_PLAN, IMPLEMENTATION, INTERNAL_TRANSITION, KICK_OFF, QSR_DELIVERED, RESELL_DISCUSSION, SELLING_OPPORTUNITY];
export var SALES_ENGINEER_ACTIVITY_TYPES = {
  CALL_GROUP: [DEMO, PRODUCT_CONSULT, DATA_CONSULT, ONSITE_MEETING],
  NON_CALL_GROUP: [ONSITE_PREPERATION, RESEARCH_FOLLOW_UP, DEAL_CUSTOMIZATION, DEAL_COACHING, OFFICE_HOURS, RFP]
};
export var AP_ACTIVITY_TYPES = [BUILD_LEAD_LIST, BUSINESS_STRATEGY, AGENCY_SERVICES, DEAL_REVIEW, DEVELOPING_SALES_PLAN, CULTURE, KICK_OFF, PBE_REVIEW, PRICING_PACKAGING, PROACTIVE_PROSPECTING, QUARTERLY_REVIEW, SALES_COACHING, SMALL_GROUP_COACHING];
export var DEAL_DEFAULT_ACTIVITY_TYPES = [CALL, IMA, DEMO, GOAL_SETTING];