import { Fields, Field } from 'Types/types';

export const getProjectStaticFields = (): Fields => {
	const fields: Field[] = [
		{
			add_visible_flag: false,
			bulk_edit_allowed: false,
			details_visible_flag: false,
			edit_flag: false,
			field_type: 'varchar',
			filtering_allowed: true,
			id: 1,
			important_flag: true,
			item_type: 'project',
			key: 'title',
			mandatory_flag: true,
			name: 'Title',
			order_nr: 1,
			searchable_flag: false,
			sortable_flag: true,
			add_time: '',
			update_time: '',
			last_updated_by_user_id: 0,
			options: [],
			is_subfield: false,
		},
		{
			add_visible_flag: false,
			bulk_edit_allowed: false,
			details_visible_flag: false,
			edit_flag: false,
			field_type: 'date',
			filtering_allowed: true,
			id: 2,
			important_flag: false,
			item_type: 'project',
			key: 'start_date',
			mandatory_flag: true,
			name: 'Start date',
			order_nr: 2,
			searchable_flag: false,
			sortable_flag: true,
			add_time: '',
			update_time: '',
			last_updated_by_user_id: 0,
			options: [],
			is_subfield: false,
		},
		{
			add_visible_flag: false,
			bulk_edit_allowed: false,
			details_visible_flag: false,
			edit_flag: false,
			field_type: 'date',
			filtering_allowed: true,
			id: 3,
			important_flag: false,
			item_type: 'project',
			key: 'end_date',
			mandatory_flag: true,
			name: 'End date',
			order_nr: 3,
			searchable_flag: false,
			sortable_flag: true,
			add_time: '',
			update_time: '',
			last_updated_by_user_id: 0,
			options: [],
			is_subfield: false,
		},
		{
			add_visible_flag: false,
			bulk_edit_allowed: false,
			details_visible_flag: false,
			edit_flag: false,
			field_type: 'user',
			filtering_allowed: true,
			id: 4,
			important_flag: false,
			item_type: 'project',
			key: 'owner_id',
			mandatory_flag: true,
			name: 'Owner',
			order_nr: 4,
			searchable_flag: false,
			sortable_flag: true,
			add_time: '',
			update_time: '',
			last_updated_by_user_id: 0,
			options: [],
			is_subfield: false,
		},
		{
			add_visible_flag: false,
			bulk_edit_allowed: true,
			details_visible_flag: true,
			edit_flag: false,
			field_type: 'deal',
			filtering_allowed: true,
			id: 5,
			important_flag: false,
			is_subfield: false,
			key: 'deal_id',
			last_updated_by_user_id: 0,
			mandatory_flag: false,
			name: 'Deal',
			options: [],
			order_nr: 5,
			searchable_flag: false,
			sortable_flag: true,
			add_time: '',
			update_time: '',
			item_type: 'project',
		},
		{
			add_visible_flag: false,
			bulk_edit_allowed: true,
			details_visible_flag: true,
			edit_flag: false,
			field_type: 'person',
			filtering_allowed: true,
			id: 6,
			important_flag: false,
			is_subfield: false,
			key: 'person_id',
			last_updated_by_user_id: 0,
			mandatory_flag: false,
			name: 'Person',
			options: [],
			order_nr: 6,
			searchable_flag: false,
			sortable_flag: true,
			add_time: '',
			update_time: '',
			item_type: 'project',
		},
		{
			add_visible_flag: false,
			bulk_edit_allowed: true,
			details_visible_flag: true,
			edit_flag: false,
			field_type: 'organization',
			filtering_allowed: true,
			id: 7,
			important_flag: false,
			is_subfield: false,
			key: 'org_id',
			last_updated_by_user_id: 0,
			mandatory_flag: false,
			name: 'Organization',
			options: [],
			order_nr: 7,
			searchable_flag: false,
			sortable_flag: true,
			add_time: '',
			update_time: '',
			item_type: 'project',
		},
		{
			add_visible_flag: false,
			bulk_edit_allowed: false,
			details_visible_flag: false,
			edit_flag: false,
			field_type: 'text',
			filtering_allowed: true,
			id: 8,
			important_flag: false,
			item_type: 'project',
			key: 'description',
			mandatory_flag: true,
			name: 'Description',
			order_nr: 8,
			searchable_flag: false,
			sortable_flag: true,
			add_time: '',
			update_time: '',
			last_updated_by_user_id: 0,
			options: [],
			is_subfield: false,
		},
	];

	return {
		allFields: fields,
		visibleFields: fields,
	};
};
