// [InvestorsSeparation] Copy of the original file. Will be removed soon.
export const COMMON_WORKSPACES_FETCH_WORKSPACES = "COPY_COMMON_WORKSPACES_FETCH_WORKSPACES";
export const COMMON_WORKSPACES_SELECT_ACTIVE_WORKSPACE =
    "COPY_COMMON_WORKSPACES_SELECT_ACTIVE_WORKSPACE";
export const COMMON_WORKSPACES_SELECT_ACTIVE_LIST = "COPY_COMMON_WORKSPACES_SELECT_ACTIVE_LIST";
export const COMMON_WORKSPACES_FETCH_LIST_DATA_START =
    "COPY_COMMON_WORKSPACES_FETCH_LIST_DATA_START";
export const COMMON_WORKSPACES_SET_ACTIVE_LIST_DATA_SUCCESS =
    "COPY_COMMON_WORKSPACES_SET_ACTIVE_LIST_DATA_SUCCESS";
export const COMMON_WORKSPACES_FETCH_WORKSPACES_SUCCESS =
    "COPY_COMMON_WORKSPACES_FETCH_WORKSPACES_SUCCESS";
export const COMMON_WORKSPACES_FETCH_WORKSPACES_FAILED =
    "COPY_COMMON_WORKSPACES_FETCH_WORKSPACES_FAILED";
export const COMMON_WORKSPACES_UPDATE_SNAPSHOT_DATE = "COMMON_WORKSPACES_UPDATE_SNAPSHOT_DATE";
export const COMMON_WORKSPACES_OPTIMISTIC_REMOVE_OPPORTUNITIES =
    "COPY_COMMON_WORKSPACES_OPTIMISTIC_REMOVE_OPPORTUNITIES";
export const COMMON_WORKSPACES_CHANGE_ACTIVE_LIST = "COPY_COMMON_WORKSPACES_CHANGE_ACTIVE_LIST";
export const COMMON_WORKSPACES_ADD_WORKSPACE = "COPY_COMMON_WORKSPACES_ADD_WORKSPACE";
export const COMMON_WORKSPACES_ADD_OPPORTUNITY_LIST = "COPY_COMMON_WORKSPACES_ADD_OPPORTUNITY_LIST";
export const COMMON_WORKSPACES_ADD_OPPORTUNITIES_FAIL =
    "COPY_COMMON_WORKSPACES_ADD_OPPORTUNITIES_FAIL";
export const COMMON_WORKSPACES_ADD_OPPORTUNITIES_START =
    "COPY_COMMON_WORKSPACES_ADD_OPPORTUNITIES_START";
export const COMMON_WORKSPACES_ADD_OPPORTUNITIES_SUCCESS =
    "COPY_COMMON_WORKSPACES_ADD_OPPORTUNITIES_SUCCESS";
export const COMMON_WORKSPACES_UPDATE_LIST_INFO_START =
    "COPY_COMMON_WORKSPACES_UPDATE_LIST_INFO_START";
export const COMMON_WORKSPACES_UPDATE_LIST_INFO = "COPY_COMMON_WORKSPACES_UPDATE_LIST_INFO";
export const COMMON_WORKSPACES_DELETE_OPPORTUNITY_LIST =
    "COPY_COMMON_WORKSPACES_DELETE_OPPORTUNITY_LIST";
export const COMMON_WORKSPACES_RESET = "COPY_COMMON_WORKSPACES_RESET";
export const COMMON_WORKSPACES_FETCH_RECOMMENDATIONS =
    "COPY_COMMON_WORKSPACES_FETCH_RECOMMENDATIONS";
export const COMMON_WORKSPACES_UPDATE_RECOMMENDATIONS =
    "COPY_COMMON_WORKSPACES_UPDATE_RECOMMENDATIONS";
export const COMMON_WORKSPACES_REMOVE_RECOMMENDATIONS =
    "COPY_COMMON_WORKSPACES_REMOVE_RECOMMENDATIONS";
export const COMMON_WORKSPACES_CLOSE_RECOMMENDATIONS =
    "COPY_COMMON_WORKSPACES_CLOSE_RECOMMENDATIONS";
export const COMMON_WORKSPACES_TOGGLE_RIGHTBAR = "COPY_COMMON_WORKSPACES_TOGGLE_RIGHTBAR";
export const COMMON_WORKSPACES_TOGGLE_RECOMMENDATIONS =
    "COPY_COMMON_WORKSPACES_TOGGLE_RECOMMENDATIONS";
export const COMMON_WORKSPACES_SELECT_DOMAIN = "COPY_COMMON_WORKSPACES_SELECT_DOMAIN";
export const COMMON_WORKSPACES_FETCH_ENRICHED_DATA = "COPY_COMMON_WORKSPACES_FETCH_ENRICHED_DATA";
export const COMMON_WORKSPACES_SET_ENRICHED_DATA = "COPY_COMMON_WORKSPACES_SET_ENRICHED_DATA";
export const COMMON_WORKSPACES_SELECT_TAB = "COPY_COMMON_WORKSPACES_SELECT_TAB";
export const COMMON_WORKSPACES_FETCH_FEED_DATA = "COPY_COMMON_WORKSPACES_FETCH_FEED_DATA";
export const COMMON_WORKSPACES_SET_FEED_DATA = "COPY_COMMON_WORKSPACES_SET_FEED_DATA";
export const COMMON_WORKSPACES_SET_FEED_ITEMS_SEEN = "COPY_COMMON_WORKSPACES_SET_FEED_ITEMS_SEEN";
export const COMMON_WORKSPACES_SET_FEED_ITEM_FEEDBACK =
    "COPY_COMMON_WORKSPACES_SET_FEED_ITEM_FEEDBACK";
export const COMMON_WORKSPACES_UPDATE_LIST_SETTINGS = "COPY_COMMON_WORKSPACES_UPDATE_LIST_SETTINGS";
export const COMMON_WORKSPACES_SET_UNSUPPORTED_FEATURES =
    "COPY_COMMON_WORKSPACES_SET_UNSUPPORTED_FEATURES";
export const COMMON_WORKSPACE_LIST_SEARCH = "COPY_COMMON_WORKSPACE_LIST_SEARCH";
export const COMMON_WORKSPACES_FETCH_RANKS_DATA = "COPY_COMMON_WORKSPACES_FETCH_RANKS_DATA";
export const COMMON_WORKSPACES_SET_RANKS_DATA = "COPY_COMMON_WORKSPACES_SET_RANKS_DATA";
export const COMMON_WORKSPACES_SET_DESCRIPTION_DATA = "COPY_COMMON_WORKSPACES_SET_DESCRIPTION_DATA";
export const COMMON_WORKSPACE_LIST_SORT = "COPY_COMMON_WORKSPACE_LIST_SORT";
export const COMMON_WORKSPACES_MANIPULATION_WEBSITES_MODAL =
    "COPY_COMMON_WORKSPACES_MANIPULATION_WEBSITES_MODAL";
export const COMMON_WORKSPACES_MANIPULATION_UNLOCK_MODAL =
    "COPY_COMMON_WORKSPACES_MANIPULATION_UNLOCK_MODAL";

/** WORKSPACE SALES */
export const WORKSPACE_SALES_MANIPULATION_EMAIL_DIGEST =
    "WORKSPACE_SALES_MANIPULATION_EMAIL_DIGEST";
export const WORKSPACE_SALES_SELECT_ACTIVE_SAVED_SEARCH_LIST =
    "WORKSPACE_SALES_SELECT_ACTIVE_SAVED_SEARCH_LIST";
export const WORKSPACE_SALES_UNSELECT_ACTIVE_SAVED_SEARCH_LIST =
    "WORKSPACE_SALES_UNSELECT_ACTIVE_SAVED_SEARCH_LIST";
export const WORKSPACE_SALES_ADD_SAVED_SEARCH_LIST = "WORKSPACE_SALES_ADD_SAVED_SEARCH_LIST";
export const WORKSPACE_SALES_UPDATE_SAVED_SEARCH_LIST = "WORKSPACE_SALES_UPDATE_SAVED_SEARCH_LIST";
export const WORKSPACE_SALES_SET_LEADS_GENERATOR_REPORT =
    "WORKSPACE_SALES_SET_LEADS_GENERATOR_REPORT";
export const WORKSPACE_SALES_REMOVE_LEADS_GENERATOR_REPORT =
    "WORKSPACE_SALES_REMOVE_LEADS_GENERATOR_REPORT";
export const WORKSPACE_SALES_MANIPULATION_WEBSITES_WIZARD =
    "WORKSPACE_SALES_MANIPULATION_WEBSITES_WIZARD";
