// This file is autogenerated. Please don't modify it directly. See the README for details
/* tslint:disable */
import type AddinsIcons from './AddinsIcons';

export type AddinsIconsSubset = { [icon in AddinsIcons]: string };

export let AddinsIconsDefinitions: AddinsIconsSubset = {
    AddIn: '\uf775',
    OEM: '\ue74c',
    OfficeAddinsLogo: '\ueec7',
    Pin: '\ue718',
};

export default {
    fontFileName: 'addinsIcons',
    icons: AddinsIconsDefinitions,
};
