import { RankCell } from "components/React/Table/cells/RankCell";
import { ChangePercentage } from "components/React/Table/cells/ChangePercentage";
import { AdsenseCell } from "components/React/Table/cells/AdsenseCell";
import { i18nFilter } from "filters/ngFilters";
import {
    DefaultCellRightAlign,
    TrafficShare,
    WebsiteTooltipTopCell,
} from "components/React/Table/cells";
import { DefaultCellHeaderRightAlign } from "components/React/Table/headerCells/DefaultCellHeaderRightAlign";
import selectionColumn from "./selectionColumn";
import { TableMetaDataConfig } from "../types";

const i18n = i18nFilter();
// Attention, necessary fields are:
// cellComponent, visible, sortable, field and sortDirection
export const emailLeaders = [
    selectionColumn,
    {
        name: "Domain",
        title: "Domain",
        field: "Domain",
        type: "string",
        format: "None",
        sortDirection: "asc",
        groupable: false,
        isSorted: false,
        showTotalCount: true,
        visible: true,
        fixed: true,
        displayName: i18nFilter()("Websites"),
        tooltip: i18nFilter()("analysis.dest.out.table.columns.domain.title.tooltip"),
        cellComponent: WebsiteTooltipTopCell,
        sortable: true,
        width: 270,
    },
    {
        field: "Share",
        name: "Share",
        title: "Traffic Share",
        isSorted: true,
        sortDirection: "desc",
        visible: true,
        displayName: i18nFilter()("analysis.dest.out.table.columns.share.title"),
        tooltip: i18nFilter()("analysis.dest.out.table.columns.share.title.tooltip"),
        cellComponent: TrafficShare,
        sortable: true,
        minWidth: 150,
    },
    {
        name: "Change",
        field: "Change",
        title: "Change",
        sortDirection: "asc",
        sortable: true,
        isSorted: false,
        visible: true,
        displayName: i18nFilter()("analysis.dest.out.table.columns.change.title"),
        tooltip: i18nFilter()("analysis.dest.out.table.columns.change.title.tooltipSimple"),
        cellComponent: ChangePercentage,
        width: 110,
    },
    {
        name: "Rank",
        title: "Rank",
        sortDirection: "desc",
        field: "Rank",
        displayName: i18nFilter()("analysis.dest.out.table.columns.rank.title"),
        tooltip: i18nFilter()("analysis.dest.out.table.columns.rank.title.tooltip"),
        cellComponent: RankCell,
        format: "rank",
        sortable: true,
        width: 120,
        visible: true,
        isSorted: false,
    },
    {
        visible: true,
        name: "AvgMonthVisits",
        field: "AvgMonthVisits",
        title: "Monthly Visits",
        displayName: "Monthly Visits",
        type: "double",
        format: "minVisitsAbbr",
        sortable: true,
        isSorted: false,
        sortDirection: "desc",
        groupable: false,
        cellComponent: DefaultCellRightAlign,
        headerComponent: DefaultCellHeaderRightAlign,
        totalCount: false,
        tooltip: "widget.table.tooltip.monthlyvisits",
        width: 130,
    },
    {
        visible: true,
        name: "AvgVisitDuration",
        field: "AvgVisitDuration",
        title: "Visit Duration",
        displayName: i18n("Visit Duration"),
        type: "double",
        format: "time",
        sortable: true,
        isSorted: false,
        sortDirection: "desc",
        groupable: false,
        cellTemp: "time-cell",
        headerComponent: DefaultCellHeaderRightAlign,
        cellComponent: DefaultCellRightAlign,
        totalCount: false,
        tooltip: "widget.table.tooltip.topsites.avgvisitduration",
        width: 130,
    },
    {
        visible: true,
        name: "PagesPerVisit",
        field: "PagesPerVisit",
        displayName: i18n("Pages/Visit"),
        title: "Pages/Visit",
        type: "double",
        format: "number",
        sortable: true,
        isSorted: false,
        sortDirection: "desc",
        groupable: false,
        cellTemp: "pages-per-visit",
        cellComponent: DefaultCellRightAlign,
        headerComponent: DefaultCellHeaderRightAlign,
        totalCount: false,
        tooltip: "widget.table.tooltip.topsites.ppv",
        width: 110,
    },
    {
        visible: true,
        name: "BounceRate",
        field: "BounceRate",
        title: "Bounce Rate",
        displayName: i18n("Bounce Rate"),
        type: "double",
        format: "percentagesign",
        sortable: true,
        isSorted: false,
        sortDirection: "asc",
        groupable: false,
        cellTemp: "bounce-rate",
        headerComponent: DefaultCellHeaderRightAlign,
        cellComponent: DefaultCellRightAlign,
        totalCount: false,
        tooltip: "widget.table.tooltip.topsites.bouncerate",
        width: 125,
        inverted: true,
    },
    {
        name: "HasAdsense",
        field: "HasAdsense",
        title: "Has Adsense",
        sortDirection: "asc",
        visible: true,
        sortable: true,
        isSorted: false,
        displayName: i18nFilter()("analysis.all.table.columns.googleAds.title"),
        tooltip: i18nFilter()("analysis.all.table.columns.googleAds.title.tooltip"),
        cellComponent: AdsenseCell,
        width: 95,
    },
];

export const emailLeadersMetaData: TableMetaDataConfig = {
    tableApi: `/widgetApi/CategoryLeaders/CategoryLeadersMail/Table`,
    excelApi: `/widgetApi/CategoryLeaders/CategoryLeadersMail/Excel`,
    i18nPrefix: `analysis.competitors.search.organic.table`,
    metric: `KeywordCompetitorsOrganicTable`,
    tableSelectionTracking: `Outbound Traffic`,
    tableSelectionKey: "KeywordCompetitorsOrganicTable",
    a2dMetric: `TopOrganicSearchCompetitors`,
    searchTypeFilterPlaceholder: "analysis.competitors.search.organic.table.filters.searchtype",
    searchTypeParam: "",
    searchTypes: [
        {
            id: null,
            text: "analysis.competitors.search.organic.table.searchtype.all",
            tooltipText: "analysis.competitors.search.organic.table.searchtype.all.tooltip",
        },
        {
            id: "IsRelatedQuestions",
            text: "analysis.competitors.search.organic.table.searchtype.questions",
            tooltipText: "analysis.competitors.search.organic.table.searchtype.questions.tooltip",
        },
        {
            id: "IsNews",
            text: "analysis.competitors.search.organic.table.searchtype.news",
            tooltipText: "analysis.competitors.search.organic.table.searchtype.news.tooltip",
        },
    ],
    title: "",
};

export const emailLeadersFilters = {
    showWebsiteFilter: false,
    showCategoryFilter: false,
    showSearchTypeFilter: false,
};
