export const PANEL_VISIBLE_COUNTRIES_COUNT = 3;
export const PANEL_CUSTOM_SITES_LIMIT = 5;
export const PANEL_SITES_PER_PROSPECT_LIMIT = 10;
export const PANEL_DOMAIN_COLUMN_WIDTH = "56%";
export const PANEL_SIMILARITY_COLUMN_WIDTH = "44%";
