export const FORM_CONTROL_STATUS = {
  INDETERMINATE: 'FORM_CONTROL_STATUS.INDETERMINATE',
  REQUEST: 'FORM_CONTROL_STATUS.REQUEST',
  FAILURE: 'FORM_CONTROL_STATUS.FAILURE',
  SUCCESS: 'FORM_CONTROL_STATUS.SUCCESS',
  SUBMITTED: 'FORM_CONTROL_STATUS.SUBMITTED',
}

export const REQUEST_STATUS = {
  NOT_ASKED: 'REQUEST_STATUS.NOT_ASKED',
  LOADING: 'REQUEST_STATUS.LOADING',
  FAILURE: 'REQUEST_STATUS.FAILURE',
  SUCCESS: 'REQUEST_STATUS.SUCCESS',
}

export default FORM_CONTROL_STATUS
