'use es6';

import uniqueActionTypes from 'crm_data/flux/uniqueActionTypes';
var GridUIActionTypes = uniqueActionTypes({
  GRID_NUMBER_EDITABLE_UPDATED: 'GRID_NUMBER_EDITABLE_UPDATED',
  GRID_CHECKED: 'GRID_CHECKED',
  GRID_ALL_SELECTED: 'GRID_ALL_SELECTED',
  GRID_SEARCH_UPDATED: 'GRID_SEARCH_UPDATED',
  GRID_SEARCH_QUERY_UPDATED: 'GRID_SEARCH_QUERY_UPDATED',
  GRID_SELECTED_CLEARED: 'GRID_SELECTED_CLEARED',
  GRID_SHOWING_CHANGED: 'GRID_SHOWING_CHANGED',
  GRID_RESET: 'GRID_RESET',
  GRID_CLEANUP_SELECTED: 'GRID_CLEANUP_SELECTED',
  GRID_TEMPORARY_EXCLUDE_IDS: 'GRID_TEMPORARY_EXCLUDE_IDS',
  GRID_TEMPORARY_INCLUDE_ID: 'GRID_TEMPORARY_INCLUDE_ID',
  GRID_TEMPORARY_RESET: 'GRID_TEMPORARY_RESET',
  GRID_TEMPORARY_SET: 'GRID_TEMPORARY_SET',
  GRID_SAVED_FILTER_CHANGED: 'GRID_SAVED_FILTER_CHANGED',
  UPDATE_GRID_SEARCH_QUERIES: 'UPDATE_GRID_SEARCH_QUERIES'
});
export var GRID_NUMBER_EDITABLE_UPDATED = GridUIActionTypes.GRID_NUMBER_EDITABLE_UPDATED;
export var GRID_CHECKED = GridUIActionTypes.GRID_CHECKED;
export var GRID_ALL_SELECTED = GridUIActionTypes.GRID_ALL_SELECTED;
export var GRID_SEARCH_UPDATED = GridUIActionTypes.GRID_SEARCH_UPDATED;
export var GRID_SEARCH_QUERY_UPDATED = GridUIActionTypes.GRID_SEARCH_QUERY_UPDATED;
export var GRID_SELECTED_CLEARED = GridUIActionTypes.GRID_SELECTED_CLEARED;
export var GRID_SHOWING_CHANGED = GridUIActionTypes.GRID_SHOWING_CHANGED;
export var GRID_RESET = GridUIActionTypes.GRID_RESET;
export var GRID_CLEANUP_SELECTED = GridUIActionTypes.GRID_CLEANUP_SELECTED;
export var GRID_TEMPORARY_EXCLUDE_IDS = GridUIActionTypes.GRID_TEMPORARY_EXCLUDE_IDS;
export var GRID_TEMPORARY_INCLUDE_ID = GridUIActionTypes.GRID_TEMPORARY_INCLUDE_ID;
export var GRID_TEMPORARY_RESET = GridUIActionTypes.GRID_TEMPORARY_RESET;
export var GRID_TEMPORARY_SET = GridUIActionTypes.GRID_TEMPORARY_SET;
export var GRID_SAVED_FILTER_CHANGED = GridUIActionTypes.GRID_SAVED_FILTER_CHANGED;
export var UPDATE_GRID_SEARCH_QUERIES = GridUIActionTypes.UPDATE_GRID_SEARCH_QUERIES;
/* eslint-env commonjs */
// This temporary hack ensures module system compatibility.
// Read more at go/treeshaking

if (!!module && !!module.exports) {
  module.exports.default = Object.assign({}, module.exports);
}