import React from "react";
import { TranslateFunction } from "app/@types/I18nInterfaces";
import { FlexTableColumnType } from "pages/sales-intelligence/types";
import { DefaultCellHeaderRightAlign } from "components/React/Table/headerCells";
import { RowSelectionConsumer } from "components/React/Table/cells/RowSelection";
import { ITableCellProps } from "components/React/Table/interfaces/ITableCellProps";
import { DefaultCellHeader } from "components/React/Table/headerCells/DefaultCellHeader";
import { Container, LeadLabel } from "pages/lead-generator/lead-generator-exist/components/styles";
import { categoryIconFilter, parentCategoryFilter, subCategoryFilter } from "filters/ngFilters";
import { LeadGeneratorChangePercentage } from "pages/lead-generator/lead-generator-exist/components/LeadGeneratorChangePercentage";
import {
    RankCell,
    TimeCell,
    DefaultCell,
    CountryCell,
    PagesPerVisit,
    VisitsThreshHoldCell,
    DefaultCellRightAlign,
    PercentageBarCellRounded,
    BounceRate,
    AdsenseCell,
    DemographicsShare,
    TrafficShare,
} from "components/React/Table/cells";

export const getSearchResultsTableColumnPickerGroups = (
    translate: TranslateFunction,
    isDesktopOnly = false,
) => {
    return [
        {
            key: "rank",
            displayName: translate("grow.lead_generator.exist.table.toggle.rank"),
        },
        {
            key: "siteCategory",
            displayName: translate("grow.lead_generator.exist.table.toggle.site_category"),
        },
        {
            key: "totalEngagement",
            displayName: translate("grow.lead_generator.exist.table.toggle.total_engagement"),
            disabled: isDesktopOnly,
            disabledText: translate("grow.lead_generator.exist.table.toggle.desktop_only_tooltip"),
        },
        {
            key: "desktopEngagement",
            displayName: translate("grow.lead_generator.exist.table.toggle.desktop_engagement"),
        },
        {
            key: "mobileWebEngagement",
            displayName: translate("grow.lead_generator.exist.table.toggle.mobile_web_engagement"),
            disabled: isDesktopOnly,
            disabledText: translate("grow.lead_generator.exist.table.toggle.desktop_only_tooltip"),
        },
        {
            key: "trafficSourcesShare",
            displayName: translate("grow.lead_generator.exist.table.toggle.traffic_sources_share"),
        },
        {
            key: "trafficSourcesVisits",
            displayName: translate("grow.lead_generator.exist.table.toggle.traffic_sources_visits"),
        },
        {
            key: "companyInformation",
            displayName: translate("grow.lead_generator.exist.table.toggle.company_information"),
        },
        {
            key: "demographics",
            displayName: translate("grow.lead_generator.exist.table.toggle.demographics"),
        },
        {
            key: "adSense",
            displayName: translate("grow.lead_generator.exist.table.toggle.ad_sense"),
        },
    ];
};

export const getSearchResultsTableColumns = (translate: TranslateFunction) => {
    return [
        {
            width: 48,
            fixed: true,
            visible: true,
            sortable: false,
            isCheckBox: true,
            cellComponent(props: ITableCellProps) {
                return (
                    <div className="u-alignCenter">
                        <RowSelectionConsumer {...props} />
                    </div>
                );
            },
            headerComponent() {
                return null;
            },
        },
        {
            width: 260,
            fixed: true,
            visible: true,
            field: "site",
            type: "string",
            format: "None",
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            cellComponent(props: ITableCellProps) {
                const { row } = props;

                return (
                    <Container isNew={row.is_new} isReturning={row.is_returning}>
                        <div className="cell-padding escape-max-width">
                            <img
                                src={row.favicon}
                                alt={row.site}
                                className="favicon swTable-websiteTooltipCell-favicon"
                            />
                            <div className="swTable-content-large text">
                                <span>{row.site}</span>
                            </div>
                        </div>
                        {row.is_new && (
                            <LeadLabel width={30}>
                                {translate("si.savedSearch.table.domainCell.tag.new")}
                            </LeadLabel>
                        )}
                        {row.is_returning && (
                            <LeadLabel width={30}>
                                {translate("si.savedSearch.table.domainCell.tag.new")}
                            </LeadLabel>
                        )}
                    </Container>
                );
            },
            headerComponent: DefaultCellHeader,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.site"),
            displayName: translate("grow.lead_generator.exist.table.column.site"),
        },
        {
            width: 152,
            fixed: true,
            visible: true,
            type: "string",
            format: "None",
            sortable: true,
            isSorted: false,
            field: "country",
            sortDirection: "desc",
            cellComponent: CountryCell,
            headerComponent: DefaultCellHeader,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.country"),
            displayName: translate("grow.lead_generator.exist.table.column.country"),
            ppt: {
                overrideFormat: "Country",
            },
        },
        {
            width: 85,
            type: "long",
            field: "rank",
            visible: false,
            sortable: true,
            inverted: true,
            isSorted: false,
            groupKey: "rank",
            format: "swRank",
            sortDirection: "asc",
            cellComponent: RankCell,
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.rank"),
            displayName: translate("grow.lead_generator.exist.table.column.rank"),
        },
        /** START SiteCategory */
        {
            width: 185,
            type: "string",
            format: "None",
            visible: true,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            field: "site_category",
            groupKey: "siteCategory",
            ppt: {
                overrideFormat: "Category",
            },
            headerComponent: DefaultCellHeader,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.site_category"),
            displayName: translate("grow.lead_generator.exist.table.column.site_category"),
            cellComponent({ value }: ITableCellProps) {
                return (
                    <div className="swTable-categoryCell">
                        <i
                            className={`sprite-category u-right-padding-6 ${categoryIconFilter()(
                                parentCategoryFilter()(value),
                            )}`}
                        />
                        <span>{subCategoryFilter()(value)}</span>
                    </div>
                );
            },
        },
        /** END SiteCategory */
        /** START TotalEngagement */
        {
            width: 130,
            type: "double",
            visible: true,
            sortable: true,
            isSorted: false,
            field: "visits",
            sortDirection: "desc",
            format: "minVisitsAbbr",
            groupKey: "totalEngagement",
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.visits"),
            displayName: translate("grow.lead_generator.exist.table.column.visits"),
            cellComponent(props: ITableCellProps) {
                return (
                    <VisitsThreshHoldCell
                        value={props.value}
                        tooltip={translate(
                            "grow.lead_generator.exist.table.column.visits.threshhold.tooltip",
                        )}
                    />
                );
            },
        },
        {
            width: 165,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "totalEngagement",
            field: "monthly_visits_change_mom",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.monthly_visits_change_mom",
            ),
            tooltip: translate("grow.lead_generator.exist.table.tooltip.monthly_visits_change_mom"),
        },
        {
            width: 165,
            type: "string",
            format: "None",
            visible: true,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "totalEngagement",
            field: "monthly_visits_change_yoy",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.monthly_visits_change_yoy",
            ),
            tooltip: translate("grow.lead_generator.exist.table.tooltip.monthly_visits_change_yoy"),
        },
        {
            width: 130,
            type: "double",
            sortable: true,
            isSorted: false,
            field: "visitors",
            sortDirection: "desc",
            visible: false,
            format: "minVisitsAbbr",
            groupKey: "totalEngagement",
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.visitors"),
            displayName: translate("grow.lead_generator.exist.table.column.visitors"),
            cellComponent(props: ITableCellProps) {
                return (
                    <VisitsThreshHoldCell
                        value={props.value}
                        tooltip={translate(
                            "grow.lead_generator.exist.table.column.visitors.threshhold.tooltip",
                        )}
                    />
                );
            },
        },
        {
            width: 95,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "totalEngagement",
            field: "unique_monthly_visitors_change_mom",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.unique_monthly_visitors_change_mom",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.unique_monthly_visitors_change_mom",
            ),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "totalEngagement",
            field: "unique_monthly_visitors_change_yoy",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.unique_monthly_visitors_change_yoy",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.unique_monthly_visitors_change_yoy",
            ),
        },
        {
            width: 190,
            type: "string",
            visible: false,
            sortable: false,
            isSorted: false,
            sortDirection: "desc",
            format: "percentagesign",
            groupKey: "totalEngagement",
            headerComponent: DefaultCellHeader,
            cellComponent: PercentageBarCellRounded,
            field: "desktop_vs_mobileweb_visits_share",
            displayName: translate(
                "grow.lead_generator.exist.table.column.desktop_vs_mobileweb_visits_share",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.desktop_vs_mobileweb_visits_share",
            ),
        },
        {
            width: 130,
            type: "double",
            sortable: true,
            visible: false,
            isSorted: false,
            format: "number",
            sortDirection: "desc",
            cellComponent: TimeCell,
            groupKey: "totalEngagement",
            field: "avg_visit_duration",
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.avg_visit_duration"),
            displayName: translate("grow.lead_generator.exist.table.column.avg_visit_duration"),
        },
        {
            width: 110,
            type: "double",
            sortable: true,
            visible: false,
            isSorted: false,
            format: "number",
            sortDirection: "desc",
            field: "pages_per_visit",
            groupKey: "totalEngagement",
            cellComponent: PagesPerVisit,
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.pages_per_visit"),
            displayName: translate("grow.lead_generator.exist.table.column.pages_per_visit"),
        },
        {
            width: 150,
            type: "double",
            visible: true,
            sortable: true,
            isSorted: false,
            field: "pageviews",
            sortDirection: "desc",
            format: "minVisitsAbbr",
            groupKey: "totalEngagement",
            cellComponent: DefaultCellRightAlign,
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.pageviews"),
            displayName: translate("grow.lead_generator.exist.table.column.pageviews"),
        },
        {
            width: 145,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "totalEngagement",
            field: "total_page_views_change_mom",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.total_page_views_change_mom",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.total_page_views_change_mom",
            ),
        },
        {
            width: 145,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "totalEngagement",
            field: "total_page_views_change_yoy",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.total_page_views_change_yoy",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.total_page_views_change_yoy",
            ),
        },
        {
            width: 125,
            type: "double",
            sortable: true,
            visible: false,
            isSorted: false,
            format: "number",
            field: "bounce_rate",
            sortDirection: "desc",
            cellComponent: BounceRate,
            groupKey: "totalEngagement",
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.bounce_rate"),
            displayName: translate("grow.lead_generator.exist.table.column.bounce_rate"),
        },
        /** END TotalEngagement */
        /** START DesktopEngagement */
        {
            width: 130,
            type: "double",
            sortable: true,
            visible: false,
            isSorted: false,
            sortDirection: "desc",
            field: "desktop_visits",
            format: "minVisitsAbbr",
            groupKey: "desktopEngagement",
            headerComponent: DefaultCellHeaderRightAlign,
            cellComponent({ value }: ITableCellProps) {
                return (
                    <VisitsThreshHoldCell
                        value={value}
                        tooltip={translate(
                            "grow.lead_generator.exist.table.column.desktop_visits.threshhold.tooltip",
                        )}
                    />
                );
            },
            displayName: translate("grow.lead_generator.exist.table.column.desktop_visits"),
            tooltip: translate("grow.lead_generator.exist.table.tooltip.desktop_visits"),
        },
        {
            width: 145,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "desktopEngagement",
            field: "desktop_monthly_visits_change_mom",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.desktop_monthly_visits_change_mom",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.desktop_monthly_visits_change_mom",
            ),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "desktopEngagement",
            field: "desktop_monthly_visits_change_yoy",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.desktop_monthly_visits_change_yoy",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.desktop_monthly_visits_change_yoy",
            ),
        },
        {
            width: 130,
            type: "double",
            sortable: true,
            visible: false,
            isSorted: false,
            sortDirection: "desc",
            format: "minVisitsAbbr",
            field: "desktop_visitors",
            groupKey: "desktopEngagement",
            headerComponent: DefaultCellHeaderRightAlign,
            cellComponent({ value }: ITableCellProps) {
                return (
                    <VisitsThreshHoldCell
                        value={value}
                        tooltip={translate(
                            "grow.lead_generator.exist.table.column.desktop_visitors.threshhold.tooltip",
                        )}
                    />
                );
            },
            displayName: translate("grow.lead_generator.exist.table.column.desktop_visitors"),
            tooltip: translate("grow.lead_generator.exist.table.tooltip.desktop_visitors"),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "desktopEngagement",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            field: "desktop_unique_monthly_visitors_change_mom",
            displayName: translate(
                "grow.lead_generator.exist.table.column.desktop_unique_monthly_visitors_change_mom",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.desktop_unique_monthly_visitors_change_mom",
            ),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "desktopEngagement",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            field: "desktop_unique_monthly_visitors_change_yoy",
            displayName: translate(
                "grow.lead_generator.exist.table.column.desktop_unique_monthly_visitors_change_yoy",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.desktop_unique_monthly_visitors_change_yoy",
            ),
        },
        {
            width: 130,
            type: "double",
            sortable: true,
            visible: false,
            isSorted: false,
            format: "number",
            sortDirection: "desc",
            cellComponent: TimeCell,
            groupKey: "desktopEngagement",
            field: "desktop_avg_visit_duration",
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.desktop_avg_visit_duration",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.desktop_avg_visit_duration",
            ),
        },
        {
            width: 130,
            type: "double",
            format: "number",
            sortable: true,
            visible: false,
            isSorted: false,
            sortDirection: "desc",
            cellComponent: PagesPerVisit,
            groupKey: "desktopEngagement",
            field: "desktop_pages_per_visit",
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.desktop_pages_per_visit",
            ),
            tooltip: translate("grow.lead_generator.exist.table.tooltip.desktop_pages_per_visit"),
        },
        {
            width: 130,
            type: "double",
            sortable: true,
            visible: false,
            isSorted: false,
            sortDirection: "desc",
            format: "minVisitsAbbr",
            field: "desktop_pageviews",
            groupKey: "desktopEngagement",
            cellComponent: DefaultCellRightAlign,
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.desktop_pageviews"),
            displayName: translate("grow.lead_generator.exist.table.column.desktop_pageviews"),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            field: "desktop_total_page_views_change_mom",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            groupKey: "desktopEngagement",
            displayName: translate(
                "grow.lead_generator.exist.table.column.desktop_total_page_views_change_mom",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.desktop_total_page_views_change_mom",
            ),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "desktopEngagement",
            field: "desktop_total_page_views_change_yoy",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.desktop_total_page_views_change_yoy",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.desktop_total_page_views_change_yoy",
            ),
        },
        {
            width: 130,
            type: "double",
            sortable: true,
            visible: false,
            isSorted: false,
            format: "number",
            sortDirection: "desc",
            cellComponent: BounceRate,
            field: "desktop_bounce_rate",
            groupKey: "desktopEngagement",
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.desktop_bounce_rate"),
            displayName: translate("grow.lead_generator.exist.table.column.desktop_bounce_rate"),
        },
        /** END DesktopEngagement */
        /** START MobileWebEngagement */
        {
            width: 130,
            type: "double",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            format: "minVisitsAbbr",
            field: "mobileweb_visits",
            groupKey: "mobileWebEngagement",
            headerComponent: DefaultCellHeaderRightAlign,
            cellComponent({ value }: ITableCellProps) {
                return (
                    <VisitsThreshHoldCell
                        tooltip={translate(
                            "grow.lead_generator.exist.table.column.mobileweb_visits.threshhold.tooltip",
                        )}
                        value={value}
                    />
                );
            },
            displayName: translate("grow.lead_generator.exist.table.column.mobileweb_visits"),
            tooltip: translate("grow.lead_generator.exist.table.tooltip.mobileweb_visits"),
        },
        {
            width: 145,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "mobileWebEngagement",
            field: "mobile_monthly_visits_change_mom",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.mobile_monthly_visits_change_mom",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.mobile_monthly_visits_change_mom",
            ),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "mobileWebEngagement",
            field: "mobile_monthly_visits_change_yoy",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.mobile_monthly_visits_change_yoy",
            ),
            displayName: translate(
                "grow.lead_generator.exist.table.column.mobile_monthly_visits_change_yoy",
            ),
        },
        {
            width: 130,
            type: "double",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            format: "minVisitsAbbr",
            field: "mobileweb_visitors",
            groupKey: "mobileWebEngagement",
            headerComponent: DefaultCellHeaderRightAlign,
            cellComponent({ value }: ITableCellProps) {
                return (
                    <VisitsThreshHoldCell
                        tooltip={translate(
                            "grow.lead_generator.exist.table.column.mobileweb_visitors.threshhold.tooltip",
                        )}
                        value={value}
                    />
                );
            },
            tooltip: translate("grow.lead_generator.exist.table.tooltip.mobileweb_visitors"),
            displayName: translate("grow.lead_generator.exist.table.column.mobileweb_visitors"),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "mobileWebEngagement",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            field: "mobile_unique_monthly_visitors_change_mom",
            displayName: translate(
                "grow.lead_generator.exist.table.column.mobile_unique_monthly_visitors_change_mom",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.mobile_unique_monthly_visitors_change_mom",
            ),
        },
        {
            width: 95,
            visible: false,
            type: "string",
            format: "None",
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "mobileWebEngagement",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            field: "mobile_unique_monthly_visitors_change_yoy",
            displayName: translate(
                "grow.lead_generator.exist.table.column.mobile_unique_monthly_visitors_change_yoy",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.mobile_unique_monthly_visitors_change_yoy",
            ),
        },
        {
            width: 130,
            visible: false,
            type: "double",
            sortable: true,
            isSorted: false,
            format: "number",
            sortDirection: "desc",
            cellComponent: TimeCell,
            groupKey: "mobileWebEngagement",
            field: "mobileweb_avg_visit_duration",
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.mobileweb_avg_visit_duration",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.mobileweb_avg_visit_duration",
            ),
        },
        {
            width: 130,
            type: "double",
            visible: false,
            sortable: true,
            isSorted: false,
            format: "number",
            sortDirection: "desc",
            cellComponent: PagesPerVisit,
            groupKey: "mobileWebEngagement",
            field: "mobileweb_pages_per_visit",
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.mobileweb_pages_per_visit"),
            displayName: translate(
                "grow.lead_generator.exist.table.column.mobileweb_pages_per_visit",
            ),
        },
        {
            width: 130,
            type: "double",
            sortable: true,
            visible: false,
            isSorted: false,
            sortDirection: "desc",
            format: "minVisitsAbbr",
            field: "mobileweb_pageviews",
            groupKey: "mobileWebEngagement",
            cellComponent: DefaultCellRightAlign,
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.mobileweb_pageviews"),
            displayName: translate("grow.lead_generator.exist.table.column.mobileweb_pageviews"),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "mobileWebEngagement",
            field: "mobile_total_page_views_change_mom",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.mobile_total_page_views_change_mom",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.mobile_total_page_views_change_mom",
            ),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "mobileWebEngagement",
            field: "mobile_total_page_views_change_yoy",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.mobile_total_page_views_change_yoy",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.mobile_total_page_views_change_yoy",
            ),
        },
        {
            width: 130,
            type: "double",
            visible: false,
            sortable: true,
            isSorted: false,
            format: "number",
            sortDirection: "desc",
            cellComponent: BounceRate,
            field: "mobileweb_bounce_rate",
            groupKey: "mobileWebEngagement",
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.mobileweb_bounce_rate"),
            displayName: translate("grow.lead_generator.exist.table.column.mobileweb_bounce_rate"),
        },
        /** END MobileWebEngagement */
        /** START TrafficSourcesVisits */
        {
            width: 130,
            type: "string",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            format: "percentagesign",
            cellComponent: TrafficShare,
            groupKey: "trafficSourcesShare",
            headerComponent: DefaultCellHeader,
            field: "direct_desktop_visits_share",
            tooltip: translate("grow.lead_generator.exist.table.tooltip.direct_visits_share"),
            displayName: translate("grow.lead_generator.exist.table.column.direct_visits_share"),
        },
        {
            width: 130,
            type: "string",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            format: "percentagesign",
            cellComponent: TrafficShare,
            groupKey: "trafficSourcesShare",
            field: "mail_desktop_visits_share",
            headerComponent: DefaultCellHeader,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.mail_visits_share"),
            displayName: translate("grow.lead_generator.exist.table.column.mail_visits_share"),
        },
        {
            width: 130,
            visible: false,
            inverted: true,
            sortable: true,
            type: "string",
            isSorted: false,
            sortDirection: "desc",
            format: "percentagesign",
            cellComponent: TrafficShare,
            groupKey: "trafficSourcesShare",
            headerComponent: DefaultCellHeader,
            field: "referrals_desktop_visits_share",
            tooltip: translate("grow.lead_generator.exist.table.tooltip.referrals_visits_share"),
            displayName: translate("grow.lead_generator.exist.table.column.referrals_visits_share"),
        },
        {
            width: 130,
            inverted: true,
            visible: false,
            sortable: true,
            type: "string",
            isSorted: false,
            sortDirection: "desc",
            format: "percentagesign",
            cellComponent: TrafficShare,
            groupKey: "trafficSourcesShare",
            headerComponent: DefaultCellHeader,
            field: "social_desktop_visits_share",
            tooltip: translate("grow.lead_generator.exist.table.tooltip.social_visits_share"),
            displayName: translate("grow.lead_generator.exist.table.column.social_visits_share"),
        },
        {
            width: 130,
            visible: false,
            type: "string",
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            format: "percentagesign",
            cellComponent: TrafficShare,
            groupKey: "trafficSourcesShare",
            headerComponent: DefaultCellHeader,
            field: "organic_search_desktop_visits_share",
            displayName: translate(
                "grow.lead_generator.exist.table.column.organic_search_visits_share",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.organic_search_visits_share",
            ),
        },
        {
            width: 130,
            type: "string",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            format: "percentagesign",
            cellComponent: TrafficShare,
            groupKey: "trafficSourcesShare",
            headerComponent: DefaultCellHeader,
            field: "paid_search_desktop_visits_share",
            tooltip: translate("grow.lead_generator.exist.table.tooltip.paid_search_visits_share"),
            displayName: translate(
                "grow.lead_generator.exist.table.column.paid_search_visits_share",
            ),
        },
        {
            width: 130,
            type: "string",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            format: "percentagesign",
            cellComponent: TrafficShare,
            groupKey: "trafficSourcesShare",
            headerComponent: DefaultCellHeader,
            field: "displayads_desktop_visits_share",
            tooltip: translate("grow.lead_generator.exist.table.tooltip.displayads_visits_share"),
            displayName: translate(
                "grow.lead_generator.exist.table.column.displayads_visits_share",
            ),
        },
        {
            width: 130,
            type: "double",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            format: "minVisitsAbbr",
            field: "direct_desktop_visits",
            groupKey: "trafficSourcesVisits",
            cellComponent: DefaultCellRightAlign,
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.direct_visits"),
            displayName: translate("grow.lead_generator.exist.table.column.direct_visits"),
        },
        {
            width: 95,
            visible: false,
            type: "string",
            format: "None",
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "trafficSourcesVisits",
            field: "direct_visits_change_mom",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.direct_visits_change_mom"),
            displayName: translate(
                "grow.lead_generator.exist.table.column.direct_visits_change_mom",
            ),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "trafficSourcesVisits",
            field: "direct_visits_change_yoy",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.direct_visits_change_yoy"),
            displayName: translate(
                "grow.lead_generator.exist.table.column.direct_visits_change_yoy",
            ),
        },
        {
            width: 130,
            type: "double",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            format: "minVisitsAbbr",
            field: "mail_desktop_visits",
            groupKey: "trafficSourcesVisits",
            cellComponent: DefaultCellRightAlign,
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.mail_visits"),
            displayName: translate("grow.lead_generator.exist.table.column.mail_visits"),
        },
        {
            width: 165,
            type: "string",
            format: "None",
            sortable: true,
            visible: false,
            isSorted: false,
            sortDirection: "desc",
            field: "mail_visits_change_mom",
            groupKey: "trafficSourcesVisits",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.mail_visits_change_mom"),
            displayName: translate("grow.lead_generator.exist.table.column.mail_visits_change_mom"),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            sortable: true,
            visible: false,
            isSorted: false,
            sortDirection: "desc",
            field: "mail_visits_change_yoy",
            groupKey: "trafficSourcesVisits",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.mail_visits_change_yoy"),
            displayName: translate("grow.lead_generator.exist.table.column.mail_visits_change_yoy"),
        },
        {
            width: 130,
            type: "double",
            sortable: true,
            visible: false,
            isSorted: false,
            sortDirection: "desc",
            format: "minVisitsAbbr",
            groupKey: "trafficSourcesVisits",
            field: "referrals_desktop_visits",
            cellComponent: DefaultCellRightAlign,
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.referrals_visits"),
            displayName: translate("grow.lead_generator.exist.table.column.referrals_visits"),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "trafficSourcesVisits",
            field: "referrals_visits_change_mom",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.referrals_visits_change_mom",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.referrals_visits_change_mom",
            ),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "trafficSourcesVisits",
            field: "referrals_visits_change_yoy",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.referrals_visits_change_yoy",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.referrals_visits_change_yoy",
            ),
        },
        {
            width: 130,
            type: "double",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            format: "minVisitsAbbr",
            field: "social_desktop_visits",
            groupKey: "trafficSourcesVisits",
            cellComponent: DefaultCellRightAlign,
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.social_visits"),
            displayName: translate("grow.lead_generator.exist.table.column.social_visits"),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "trafficSourcesVisits",
            field: "social_visits_change_mom",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.social_visits_change_mom",
            ),
            tooltip: translate("grow.lead_generator.exist.table.tooltip.social_visits_change_mom"),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "trafficSourcesVisits",
            field: "social_visits_change_yoy",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.social_visits_change_yoy",
            ),
            tooltip: translate("grow.lead_generator.exist.table.tooltip.social_visits_change_yoy"),
        },
        {
            width: 150,
            visible: false,
            type: "double",
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            format: "minVisitsAbbr",
            groupKey: "trafficSourcesVisits",
            cellComponent: DefaultCellRightAlign,
            field: "organic_search_desktop_visits",
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.organic_search_visits"),
            displayName: translate("grow.lead_generator.exist.table.column.organic_search_visits"),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "trafficSourcesVisits",
            field: "organic_search_visits_change_mom",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.organic_search_visits_change_mom",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.organic_search_visits_change_mom",
            ),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "trafficSourcesVisits",
            field: "organic_search_visits_change_yoy",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.organic_search_visits_change_yoy",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.organic_search_visits_change_yoy",
            ),
        },
        {
            width: 130,
            type: "double",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            format: "minVisitsAbbr",
            groupKey: "trafficSourcesVisits",
            field: "paid_search_desktop_visits",
            cellComponent: DefaultCellRightAlign,
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.paid_search_visits"),
            displayName: translate("grow.lead_generator.exist.table.column.paid_search_visits"),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "trafficSourcesVisits",
            field: "paid_search_visits_change_mom",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.paid_search_visits_change_mom",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.paid_search_visits_change_mom",
            ),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "trafficSourcesVisits",
            field: "paid_search_visits_change_yoy",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.paid_search_visits_change_yoy",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.paid_search_visits_change_yoy",
            ),
        },
        {
            width: 130,
            type: "double",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            format: "minVisitsAbbr",
            groupKey: "trafficSourcesVisits",
            field: "displayads_desktop_visits",
            cellComponent: DefaultCellRightAlign,
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.displayads_visits"),
            displayName: translate("grow.lead_generator.exist.table.column.displayads_visits"),
        },
        {
            width: 95,
            format: "None",
            type: "string",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "trafficSourcesVisits",
            field: "display_ads_visits_change_mom",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.display_ads_visits_change_mom",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.display_ads_visits_change_mom",
            ),
        },
        {
            width: 95,
            format: "None",
            type: "string",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "trafficSourcesVisits",
            field: "display_ads_visits_change_yoy",
            cellComponent: LeadGeneratorChangePercentage,
            headerComponent: DefaultCellHeaderRightAlign,
            displayName: translate(
                "grow.lead_generator.exist.table.column.display_ads_visits_change_yoy",
            ),
            tooltip: translate(
                "grow.lead_generator.exist.table.tooltip.display_ads_visits_change_yoy",
            ),
        },
        /** END TrafficSourcesVisits */
        /** START CompanyInformation */
        {
            width: 95,
            type: "string",
            format: "None",
            sortable: true,
            visible: false,
            isSorted: false,
            field: "company_name",
            sortDirection: "desc",
            cellComponent: DefaultCell,
            groupKey: "companyInformation",
            headerComponent: DefaultCellHeader,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.company_name"),
            displayName: translate("grow.lead_generator.exist.table.column.company_name"),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            sortable: true,
            visible: false,
            isSorted: false,
            sortDirection: "desc",
            field: "company_address",
            cellComponent: DefaultCell,
            groupKey: "companyInformation",
            headerComponent: DefaultCellHeader,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.company_address"),
            displayName: translate("grow.lead_generator.exist.table.column.company_address"),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            sortable: true,
            visible: false,
            isSorted: false,
            sortDirection: "desc",
            field: "company_city",
            cellComponent: DefaultCell,
            groupKey: "companyInformation",
            headerComponent: DefaultCellHeader,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.company_city"),
            displayName: translate("grow.lead_generator.exist.table.column.company_city"),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            sortable: true,
            visible: false,
            isSorted: false,
            sortDirection: "desc",
            field: "company_state",
            cellComponent: DefaultCell,
            groupKey: "companyInformation",
            headerComponent: DefaultCellHeader,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.company_state"),
            displayName: translate("grow.lead_generator.exist.table.column.company_state"),
        },
        {
            width: 145,
            visible: true,
            type: "string",
            format: "None",
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            field: "company_country",
            cellComponent: DefaultCell,
            groupKey: "companyInformation",
            headerComponent: DefaultCellHeader,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.company_country"),
            displayName: translate("grow.lead_generator.exist.table.column.company_country"),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            sortable: true,
            visible: false,
            isSorted: false,
            field: "company_zip",
            sortDirection: "desc",
            groupKey: "companyInformation",
            cellComponent: DefaultCellRightAlign,
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.company_zip"),
            displayName: translate("grow.lead_generator.exist.table.column.company_zip"),
        },
        {
            width: 95,
            visible: true,
            type: "string",
            format: "None",
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "companyInformation",
            field: "company_employee_range",
            cellComponent: DefaultCellRightAlign,
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.company_employee_range"),
            displayName: translate("grow.lead_generator.exist.table.column.company_employee_range"),
        },
        {
            width: 95,
            visible: true,
            type: "string",
            format: "None",
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            field: "company_revenue_range",
            groupKey: "companyInformation",
            cellComponent: DefaultCellRightAlign,
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.company_revenue_range"),
            displayName: translate("grow.lead_generator.exist.table.column.company_revenue_range"),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            sortable: true,
            visible: false,
            isSorted: false,
            sortDirection: "desc",
            field: "company_phone",
            groupKey: "companyInformation",
            cellComponent: DefaultCellRightAlign,
            headerComponent: DefaultCellHeaderRightAlign,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.company_phone"),
            displayName: translate("grow.lead_generator.exist.table.column.company_phone"),
        },
        {
            width: 95,
            type: "string",
            format: "None",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            field: "company_email",
            cellComponent: DefaultCell,
            groupKey: "companyInformation",
            headerComponent: DefaultCellHeader,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.company_email"),
            displayName: translate("grow.lead_generator.exist.table.column.company_email"),
        },
        /** END CompanyInformation */
        /** START Demographics */
        {
            width: 190,
            type: "string",
            visible: false,
            sortable: false,
            isSorted: false,
            sortDirection: "desc",
            format: "percentagesign",
            groupKey: "demographics",
            field: "male_vs_female_share",
            headerComponent: DefaultCellHeader,
            cellComponent: PercentageBarCellRounded,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.male_vs_female_share"),
            displayName: translate("grow.lead_generator.exist.table.column.male_vs_female_share"),
        },
        {
            width: 130,
            type: "string",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            format: "percentagesign",
            groupKey: "demographics",
            field: "age_group_18_24_share",
            cellComponent: DemographicsShare,
            headerComponent: DefaultCellHeader,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.age_group_18_24_share"),
            displayName: translate("grow.lead_generator.exist.table.column.age_group_18_24_share"),
        },
        {
            width: 130,
            type: "string",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            format: "percentagesign",
            groupKey: "demographics",
            field: "age_group_25_34_share",
            cellComponent: DemographicsShare,
            headerComponent: DefaultCellHeader,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.age_group_25_34_share"),
            displayName: translate("grow.lead_generator.exist.table.column.age_group_25_34_share"),
        },
        {
            width: 130,
            visible: false,
            type: "string",
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "demographics",
            format: "percentagesign",
            field: "age_group_35_44_share",
            cellComponent: DemographicsShare,
            headerComponent: DefaultCellHeader,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.age_group_35_44_share"),
            displayName: translate("grow.lead_generator.exist.table.column.age_group_35_44_share"),
        },
        {
            width: 130,
            type: "string",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            format: "percentagesign",
            groupKey: "demographics",
            field: "age_group_45_54_share",
            cellComponent: DemographicsShare,
            headerComponent: DefaultCellHeader,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.age_group_45_54_share"),
            displayName: translate("grow.lead_generator.exist.table.column.age_group_45_54_share"),
        },
        {
            width: 130,
            visible: false,
            type: "string",
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            format: "percentagesign",
            groupKey: "demographics",
            field: "age_group_55_64_share",
            cellComponent: DemographicsShare,
            headerComponent: DefaultCellHeader,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.age_group_55_64_share"),
            displayName: translate("grow.lead_generator.exist.table.column.age_group_55_64_share"),
        },
        {
            width: 130,
            type: "string",
            visible: false,
            sortable: true,
            isSorted: false,
            sortDirection: "desc",
            groupKey: "demographics",
            format: "percentagesign",
            field: "age_group_65_share",
            cellComponent: DemographicsShare,
            headerComponent: DefaultCellHeader,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.age_group_65_share"),
            displayName: translate("grow.lead_generator.exist.table.column.age_group_65_share"),
        },
        /** END Demographics */
        {
            width: 95,
            type: "bool",
            visible: false,
            format: "None",
            sortable: true,
            isSorted: false,
            groupKey: "adSense",
            field: "has_adsense",
            sortDirection: "desc",
            cellComponent: AdsenseCell,
            headerComponent: DefaultCellHeader,
            tooltip: translate("grow.lead_generator.exist.table.tooltip.has_adsense"),
            displayName: translate("grow.lead_generator.exist.table.column.has_adsense"),
        },
    ] as FlexTableColumnType[];
};
