'use es6';

export var RECENTLY_USED_PROPERTIES_LOAD_STARTED = 'RECENTLY_USED_PROPERTIES_LOAD_STARTED';
export var RECENTLY_USED_PROPERTIES_LOAD_SUCCEEDED = 'RECENTLY_USED_PROPERTIES_LOAD_SUCCEEDED';
export var RECENTLY_USED_PROPERTIES_LOAD_FAILED = 'RECENTLY_USED_PROPERTIES_LOAD_FAILED';
export var RECENTLY_USED_PROPERTIES_SET_STARTED = 'RECENTLY_USED_PROPERTIES_SET_STARTED';
export var RECENTLY_USED_PROPERTIES_SET_SUCCEEDED = 'RECENTLY_USED_PROPERTIES_SET_SUCCEEDED';
export var RECENTLY_USED_PROPERTIES_SET_FAILED = 'RECENTLY_USED_PROPERTIES_SET_FAILED';