export enum HELP_ARTICLE_IDS {
    CREATE_ARENA_ONBOARDING = "CREATE_ARENA_ONBOARDING",
    ARENA_STRATEGIC_OVERVIEW = "ARENA_STRATEGIC_OVERVIEW",
    ARENA_ORGANIC_SEARCH_OVERVIEW = "ARENA_ORGANIC_SEARCH_OVERVIEW",
    ARENA_REFERRALS_OVERVIEW = "ARENA_REFERRALS_OVERVIEW",
    WEBSITE_PERFORMANCE = "WEBSITE_PERFORMANCE",
    INCOMING_TRAFFIC = "INCOMING_TRAFFIC",
    TRAFFIC_DISPLAY_VIDEOS = "TRAFFIC_DISPLAY_VIDEOS",
}
