'use es6';

export var APP_STARTED = 'APP_STARTED';
export var INITIALIZE_AUTH = 'INITIALIZE_AUTH';
export var REQUEST_UPDATE = 'REQUEST_UPDATE';
export var CHANNELS_FETCH = 'CHANNELS_FETCH';
export var CHANNEL_ANALYTICS_FETCH_BEGAN = 'CHANNEL_ANALYTICS_FETCH_BEGAN';
export var CHANNEL_ANALYTICS_FETCH_ERROR = 'CHANNEL_ANALYTICS_FETCH_ERROR';
export var CHANNEL_ANALYTICS_FETCH_SUCCESS = 'CHANNEL_ANALYTICS_FETCH_SUCCESS';
export var SET_CHANNEL_ID = 'SET_CHANNEL_ID';
export var SET_DATE_RANGE = 'SET_DATE_RANGE';
export var SET_REPORT_DATA = 'SET_REPORT_DATA';
export var DATAFILTER_UPDATE = 'DATAFILTER_UPDATE';
export var TOP_POSTS_FILTER_UPDATE = 'TOP_POSTS_FILTER_UPDATE';