import { SWSettings } from "common/services/swSettings";
import { DefaultCellRightAlign } from "../../../React/Table/cells/DefaultCellRightAlign";
import { DefaultCellHeaderRightAlign } from "../../../React/Table/headerCells/DefaultCellHeaderRightAlign";

const isLeaderMetricHidden = (swSettings: SWSettings) => {
    // All legacy users have the leader metrics
    const isLegacyUser = !swSettings.user.hasSolution2;
    if (isLegacyUser) return false;

    // For solutions 2.0 users - we show leaders metrics only for
    // Market intelligence users
    const hasMarketIntelligence = swSettings.user.hasMR;
    return !hasMarketIntelligence;
};

export const CategoryLeadersAds = {
    id: "CategoryLeadersAds",
    properties: {
        component: "CategoryLeaders",
        state: "marketresearch_webmarketanalysis_rankings",
        dashboard: "true",
        title: "dashboard.categoryLeaders.table.title.ads",
        family: "Industry",
        apiController: "CategoryLeaders",
        disableDatepicker: true,
        viewPermissions: {
            trafficSources: ["Desktop"],
        },
        availabilityComponent: "WsWebCategoryDisplayLeaders",
        isHidden: isLeaderMetricHidden,
    },
    widgets: {
        single: {
            LeaderBySourceTable: {
                properties: {
                    showMoreButtonItems: 6,
                    apiParams: {
                        tab: "CategoryLeadersAds",
                    },
                    options: {
                        sortedColumnAddedWidth: true,
                        showLegend: false,
                        dashboardSubtitleMarginBottom: 25,
                        showFrame: true,
                        showOverflow: true,
                        desktopOnly: true,
                    },
                },
                columns: [
                    {
                        fixed: true,
                        name: "Domain",
                        title: "Domain",
                        type: "string",
                        format: "None",
                        sortable: "False",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "website-tooltip-top-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.domain",
                        width: 173,
                    },
                    {
                        name: "Share",
                        title: "Traffic Share",
                        type: "string",
                        format: "smallNumbersPercentage:2",
                        sortable: "False",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "default-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.share",
                        width: "150px",
                    },
                    {
                        name: "Change",
                        title: "Change",
                        type: "double",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "change-percentage",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.change",
                        width: 110,
                        ppt: {
                            overrideFormat: "smallNumbersPercentage:2",
                        },
                    },
                    {
                        name: "Rank",
                        title: "Rank",
                        type: "long",
                        format: "swRank",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "asc",
                        groupable: "False",
                        cellTemp: "rank-cell",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.rank",
                        width: 85,
                        inverted: "True",
                    },
                    {
                        name: "AvgMonthVisits",
                        title: "Monthly Visits",
                        type: "double",
                        format: "abbrNumber",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "default-cell",
                        cellComponent: DefaultCellRightAlign,
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.monthlyvisits",
                        width: 130,
                    },
                    {
                        name: "AvgVisitDuration",
                        title: "Visit Duration",
                        type: "double",
                        format: "number",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "time-cell",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.avgvisitduration",
                        width: 130,
                    },
                    {
                        name: "PagesPerVisit",
                        title: "Pages/Visit",
                        type: "double",
                        format: "number",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "pages-per-visit",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.ppv",
                        width: 110,
                    },
                    {
                        name: "BounceRate",
                        title: "Bounce Rate",
                        type: "double",
                        format: "number",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "asc",
                        groupable: "False",
                        cellTemp: "bounce-rate",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.bouncerate",
                        width: 125,
                        inverted: "True",
                    },
                    {
                        name: "HasAdsense",
                        title: "Adsense",
                        type: "bool",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "adsense-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: true,
                        width: 95,
                    },
                ],
            },
        },
        compare: {},
    },
};

export const CategoryLeadersDirect = {
    id: "CategoryLeadersDirect",
    properties: {
        component: "CategoryLeaders",
        state: "marketresearch_webmarketanalysis_rankings",
        dashboard: "true",
        title: "dashboard.categoryLeaders.table.title.direct",
        family: "Industry",
        apiController: "CategoryLeaders",
        disableDatepicker: true,
        availabilityComponent: "WsWebCategoryDirectLeaders",
        isHidden: isLeaderMetricHidden,
    },
    widgets: {
        single: {
            LeaderBySourceTable: {
                properties: {
                    showMoreButtonItems: 6,
                    apiParams: {
                        tab: "CategoryLeadersDirect",
                    },
                    options: {
                        sortedColumnAddedWidth: true,
                        showLegend: false,
                        dashboardSubtitleMarginBottom: 25,
                        showFrame: true,
                        showOverflow: true,
                        desktopOnly: true,
                    },
                },
                columns: [
                    {
                        fixed: true,
                        name: "Domain",
                        title: "Domain",
                        type: "string",
                        format: "None",
                        sortable: "False",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "website-tooltip-top-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.domain",
                        width: 173,
                    },
                    {
                        name: "Share",
                        title: "Traffic Share",
                        type: "string",
                        format: "smallNumbersPercentage:2",
                        sortable: "False",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "default-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.share",
                        width: "150px",
                    },
                    {
                        name: "Change",
                        title: "Change",
                        type: "double",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "change-percentage",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.change",
                        width: 110,
                        ppt: {
                            overrideFormat: "smallNumbersPercentage:2",
                        },
                    },
                    {
                        name: "Rank",
                        title: "Rank",
                        type: "long",
                        format: "swRank",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "asc",
                        groupable: "False",
                        cellTemp: "rank-cell",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.rank",
                        width: 85,
                        inverted: "True",
                    },
                    {
                        name: "AvgMonthVisits",
                        title: "Monthly Visits",
                        type: "double",
                        format: "abbrNumber",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellComponent: DefaultCellRightAlign,
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.monthlyvisits",
                        width: 130,
                    },
                    {
                        name: "AvgVisitDuration",
                        title: "Visit Duration",
                        type: "double",
                        format: "number",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "time-cell",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.avgvisitduration",
                        width: 130,
                    },
                    {
                        name: "PagesPerVisit",
                        title: "Pages/Visit",
                        type: "double",
                        format: "number",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "pages-per-visit",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.ppv",
                        width: 110,
                    },
                    {
                        name: "BounceRate",
                        title: "Bounce Rate",
                        type: "double",
                        format: "number",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "asc",
                        groupable: "False",
                        cellTemp: "bounce-rate",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.bouncerate",
                        width: 125,
                        inverted: "True",
                    },
                    {
                        name: "HasAdsense",
                        title: "Adsense",
                        type: "bool",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "adsense-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: true,
                        width: 95,
                    },
                ],
            },
        },
        compare: {},
    },
};

export const CategoryLeadersMail = {
    id: "CategoryLeadersMail",
    properties: {
        component: "CategoryLeaders",
        state: "marketresearch_webmarketanalysis_rankings",
        dashboard: "true",
        title: "dashboard.categoryLeaders.table.title.mail",
        family: "Industry",
        apiController: "CategoryLeaders",
        disableDatepicker: true,
        availabilityComponent: "WsWebCategoryEmailLeaders",
        isHidden: isLeaderMetricHidden,
    },
    widgets: {
        single: {
            LeaderBySourceTable: {
                properties: {
                    showMoreButtonItems: 6,
                    apiParams: {
                        tab: "CategoryLeadersMail",
                    },
                    options: {
                        sortedColumnAddedWidth: true,
                        showLegend: false,
                        dashboardSubtitleMarginBottom: 25,
                        showFrame: true,
                        showOverflow: true,
                        desktopOnly: true,
                    },
                },
                columns: [
                    {
                        fixed: true,
                        name: "Domain",
                        title: "Domain",
                        type: "string",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "website-tooltip-top-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.domain",
                        width: 173,
                    },
                    {
                        name: "Share",
                        title: "Traffic Share",
                        type: "string",
                        format: "smallNumbersPercentage:2",
                        sortable: "False",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "default-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.share",
                        width: "150px",
                    },
                    {
                        name: "Change",
                        title: "Change",
                        type: "double",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "change-percentage",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.change",
                        width: 110,
                        ppt: {
                            overrideFormat: "smallNumbersPercentage:2",
                        },
                    },
                    {
                        name: "Rank",
                        title: "Rank",
                        type: "long",
                        format: "swRank",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "asc",
                        groupable: "False",
                        cellTemp: "rank-cell",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.rank",
                        width: 85,
                        inverted: "True",
                    },
                    {
                        name: "AvgMonthVisits",
                        title: "Monthly Visits",
                        type: "double",
                        format: "abbrNumber",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellComponent: DefaultCellRightAlign,
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.monthlyvisits",
                        width: 130,
                    },
                    {
                        name: "AvgVisitDuration",
                        title: "Visit Duration",
                        type: "double",
                        format: "number",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "time-cell",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.avgvisitduration",
                        width: 130,
                    },
                    {
                        name: "PagesPerVisit",
                        title: "Pages/Visit",
                        type: "double",
                        format: "number",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "pages-per-visit",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.ppv",
                        width: 110,
                    },
                    {
                        name: "BounceRate",
                        title: "Bounce Rate",
                        type: "double",
                        format: "number",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "asc",
                        groupable: "False",
                        cellTemp: "bounce-rate",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.bouncerate",
                        width: 125,
                        inverted: "True",
                    },
                    {
                        name: "HasAdsense",
                        title: "Adsense",
                        type: "bool",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "adsense-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: true,
                        width: 95,
                    },
                ],
            },
        },
        compare: {},
    },
};

export const CategoryLeadersReferrals = {
    id: "CategoryLeadersReferrals",
    properties: {
        component: "CategoryLeaders",
        state: "marketresearch_webmarketanalysis_rankings",
        dashboard: "true",
        title: "dashboard.categoryLeaders.table.title.referrals",
        family: "Industry",
        apiController: "CategoryLeaders",
        disableDatepicker: true,
        availabilityComponent: "WsWebCategoryReferralLeaders",
        isHidden: isLeaderMetricHidden,
    },
    widgets: {
        single: {
            LeaderBySourceTable: {
                properties: {
                    showMoreButtonItems: 6,
                    apiParams: {
                        tab: "CategoryLeadersReferrals",
                    },
                    options: {
                        sortedColumnAddedWidth: true,
                        showLegend: false,
                        dashboardSubtitleMarginBottom: 25,
                        showFrame: true,
                        showOverflow: true,
                        desktopOnly: true,
                    },
                },
                columns: [
                    {
                        fixed: true,
                        name: "Domain",
                        title: "Domain",
                        type: "string",
                        format: "None",
                        sortable: "False",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "website-tooltip-top-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.domain",
                        width: 173,
                    },
                    {
                        name: "Share",
                        title: "Traffic Share",
                        type: "string",
                        format: "smallNumbersPercentage:2",
                        sortable: "False",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "default-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.share",
                        width: "150px",
                    },
                    {
                        name: "Change",
                        title: "Change",
                        type: "double",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "change-percentage",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.change",
                        width: 110,
                        ppt: {
                            overrideFormat: "smallNumbersPercentage:2",
                        },
                    },
                    {
                        name: "Rank",
                        title: "Rank",
                        type: "long",
                        format: "swRank",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "asc",
                        groupable: "False",
                        cellTemp: "rank-cell",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.rank",
                        width: 85,
                        inverted: "True",
                    },
                    {
                        name: "AvgMonthVisits",
                        title: "Monthly Visits",
                        type: "double",
                        format: "abbrNumber",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellComponent: DefaultCellRightAlign,
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.monthlyvisits",
                        width: 130,
                    },
                    {
                        name: "AvgVisitDuration",
                        title: "Visit Duration",
                        type: "double",
                        format: "number",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "time-cell",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.avgvisitduration",
                        width: 130,
                    },
                    {
                        name: "PagesPerVisit",
                        title: "Pages/Visit",
                        type: "double",
                        format: "number",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "pages-per-visit",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.ppv",
                        width: 110,
                    },
                    {
                        name: "BounceRate",
                        title: "Bounce Rate",
                        type: "double",
                        format: "number",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "asc",
                        groupable: "False",
                        cellTemp: "bounce-rate",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.bouncerate",
                        width: 125,
                        inverted: "True",
                    },
                    {
                        name: "HasAdsense",
                        title: "Adsense",
                        type: "bool",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "adsense-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: true,
                        width: 95,
                    },
                ],
            },
        },
        compare: {},
    },
};

export const CategoryLeadersSearch = {
    id: "CategoryLeadersSearch",
    properties: {
        component: "CategoryLeaders",
        state: "marketresearch_webmarketanalysis_rankings",
        dashboard: "true",
        title: "dashboard.categoryLeaders.table.title.search",
        family: "Industry",
        apiController: "CategoryLeaders",
        disableDatepicker: true,
        availabilityComponent: "WsWebCategorySearchLeaders",
        isHidden: isLeaderMetricHidden,
    },
    widgets: {
        single: {
            LeaderBySourceTable: {
                properties: {
                    showMoreButtonItems: 6,
                    apiParams: {
                        tab: "CategoryLeadersSearch",
                    },
                    options: {
                        sortedColumnAddedWidth: true,
                        showLegend: false,
                        dashboardSubtitleMarginBottom: 25,
                        showFrame: true,
                        showOverflow: true,
                        desktopOnly: true,
                    },
                },
                columns: [
                    {
                        fixed: true,
                        name: "Domain",
                        title: "Domain",
                        type: "string",
                        format: "None",
                        sortable: "False",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "website-tooltip-top-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.domain",
                        width: 173,
                    },
                    {
                        name: "Share",
                        title: "Traffic Share",
                        type: "string",
                        format: "smallNumbersPercentage:2",
                        sortable: "False",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "default-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.share",
                        width: "150px",
                    },
                    {
                        name: "Change",
                        title: "Change",
                        type: "double",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "change-percentage",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.change",
                        width: 110,
                        ppt: {
                            overrideFormat: "smallNumbersPercentage:2",
                        },
                    },
                    {
                        name: "Rank",
                        title: "Rank",
                        type: "long",
                        format: "swRank",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "asc",
                        groupable: "False",
                        cellTemp: "rank-cell",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.rank",
                        width: 85,
                        inverted: "True",
                    },
                    {
                        name: "AvgMonthVisits",
                        title: "Monthly Visits",
                        type: "double",
                        format: "abbrNumber",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellComponent: DefaultCellRightAlign,
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.monthlyvisits",
                        width: 130,
                    },
                    {
                        name: "AvgVisitDuration",
                        title: "Visit Duration",
                        type: "double",
                        format: "number",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "time-cell",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.avgvisitduration",
                        width: 130,
                    },
                    {
                        name: "PagesPerVisit",
                        title: "Pages/Visit",
                        type: "double",
                        format: "number",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "pages-per-visit",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.ppv",
                        width: 110,
                    },
                    {
                        name: "BounceRate",
                        title: "Bounce Rate",
                        type: "double",
                        format: "number",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "asc",
                        groupable: "False",
                        cellTemp: "bounce-rate",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.bouncerate",
                        width: 125,
                        inverted: "True",
                    },
                    {
                        name: "HasAdsense",
                        title: "Adsense",
                        type: "bool",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "adsense-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: true,
                        width: 95,
                    },
                ],
            },
        },
        compare: {},
    },
};

export const CategoryLeadersSocial = {
    id: "CategoryLeadersSocial",
    properties: {
        component: "CategoryLeaders",
        state: "marketresearch_webmarketanalysis_rankings",
        dashboard: "true",
        title: "dashboard.categoryLeaders.table.title.social",
        family: "Industry",
        apiController: "CategoryLeaders",
        disableDatepicker: true,
        availabilityComponent: "WsWebCategorySocialLeaders",
        isHidden: isLeaderMetricHidden,
    },
    widgets: {
        single: {
            LeaderBySourceTable: {
                properties: {
                    showMoreButtonItems: 6,
                    apiParams: {
                        tab: "CategoryLeadersSocial",
                    },
                    options: {
                        sortedColumnAddedWidth: true,
                        showLegend: false,
                        dashboardSubtitleMarginBottom: 25,
                        showFrame: true,
                        showOverflow: true,
                        desktopOnly: true,
                    },
                },
                columns: [
                    {
                        fixed: true,
                        name: "Domain",
                        title: "Domain",
                        type: "string",
                        format: "None",
                        sortable: "False",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "website-tooltip-top-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.domain",
                        width: 173,
                    },
                    {
                        name: "Share",
                        title: "Traffic Share",
                        type: "string",
                        format: "smallNumbersPercentage:2",
                        sortable: "False",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "default-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.share",
                        width: "150px",
                    },
                    {
                        name: "Change",
                        title: "Change",
                        type: "double",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "change-percentage",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.change",
                        width: 110,
                        ppt: {
                            overrideFormat: "smallNumbersPercentage:2",
                        },
                    },
                    {
                        name: "Rank",
                        title: "Rank",
                        type: "long",
                        format: "swRank",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "asc",
                        groupable: "False",
                        cellTemp: "rank-cell",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.rank",
                        width: 85,
                        inverted: "True",
                    },
                    {
                        name: "AvgMonthVisits",
                        title: "Monthly Visits",
                        type: "double",
                        format: "abbrNumber",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellComponent: DefaultCellRightAlign,
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.monthlyvisits",
                        width: 130,
                    },
                    {
                        name: "AvgVisitDuration",
                        title: "Visit Duration",
                        type: "double",
                        format: "number",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "time-cell",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.avgvisitduration",
                        width: 130,
                    },
                    {
                        name: "PagesPerVisit",
                        title: "Pages/Visit",
                        type: "double",
                        format: "number",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "pages-per-visit",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.ppv",
                        width: 110,
                    },
                    {
                        name: "BounceRate",
                        title: "Bounce Rate",
                        type: "double",
                        format: "percentagesign:2",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "asc",
                        groupable: "False",
                        cellTemp: "default-cell",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: "widget.table.tooltip.topsites.bouncerate",
                        width: 125,
                        inverted: "True",
                    },
                    {
                        name: "HasAdsense",
                        title: "Adsense",
                        type: "bool",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "adsense-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: true,
                        width: 95,
                    },
                ],
            },
        },
        compare: {},
    },
};

export const Subcategories = {
    id: "Subcategories",
    properties: {
        component: "IndustryAnalysis",
        state: "websites-worldwideOverview",
        dashboard: "false",
        hasWebSource: false,
        modules: {
            Industry: {
                component: "IndustryAnalysis",
                family: "Industry",
                state: "industryAnalysis-overview",
                dashboard: "true",
                title: "ia.overview.subcategories",
                apiController: "IndustryAnalysis",
                availabilityComponent: "WsWebCategoryPerformance",
            },
        },
    },
    widgets: {
        single: {
            RelatedCategoriesTable: {
                properties: {
                    options: {
                        desktopOnly: true,
                        showLegend: false,
                        dashboardSubtitleMarginBottom: 15,
                    },
                    showMoreButtonItems: 5,
                },
                columns: [
                    {
                        name: "Category",
                        title: "Category",
                        type: "string",
                        format: "None",
                        sortable: "False",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "category-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: false,
                        minWidth: 230,
                        ppt: {
                            overrideFormat: "Category",
                        },
                    },
                    {
                        name: "TotalVisits",
                        title: "Total Visits",
                        type: "double",
                        format: "abbrNumber",
                        sortable: "False",
                        isSorted: "False",
                        isLink: true,
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "subcategories-share",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: false,
                        width: "",
                    },
                ],
            },
            CustomCategoriesTable: {
                properties: {
                    options: {
                        desktopOnly: true,
                        showLegend: false,
                        dashboardSubtitleMarginBottom: 15,
                    },
                    showMoreButtonItems: 5,
                },
                columns: [
                    {
                        name: "Category",
                        title: "Category",
                        type: "string",
                        format: "None",
                        sortable: "False",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "category-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: true,
                        minWidth: 230,
                        ppt: {
                            overrideFormat: "Category",
                        },
                    },
                    {
                        name: "TotalVisits",
                        title: "Total Visits",
                        type: "double",
                        format: "abbrNumber",
                        sortable: "False",
                        isSorted: "False",
                        isLink: true,
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "subcategories-share",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: true,
                        width: "",
                    },
                ],
            },
        },
    },
};
