import { DefaultCellRightAlign } from "../../../React/Table/cells/DefaultCellRightAlign";
import { DefaultCellHeaderRightAlign } from "../../../React/Table/headerCells/DefaultCellHeaderRightAlign";

export const KeywordAnalysisCPC = {
    id: "KeywordAnalysisCPC",
    properties: {
        component: "KeywordAnalysisOPTotal",
        family: "Keyword",
        dashboard: "true",
        state: "keywordAnalysis-organic",
        title: "KeywordAnalysis.organic.widgets.cpc",
        webSource: "Desktop",
        subtitle: "KeywordAnalysis.organic.cpc.subtitle",
        apiController: "KeywordAnalysisOP",
        availabilityComponent: "WsPaidKeywords",
    },
    widgets: {
        single: {
            SingleMetric: {
                properties: {
                    headTemp: "",
                    options: {
                        showLegend: false,
                        showSettings: true,
                        showFrame: true,
                        showOverflow: true,
                        template: "/app/pages/keyword-analysis/templates/cpc-dashboard.html",
                    },
                },
                objects: {
                    TotalVisits: {
                        name: "CPC",
                        title: "",
                        type: "double",
                        format: "abbrNumber",
                        cellTemp: "large-number",
                        ppt: {
                            overrideFormat: "cpc",
                        },
                    },
                },
            },
        },
        compare: {},
    },
};

export const KeywordAnalysisOrganic = {
    id: "KeywordAnalysisOrganic",
    properties: {
        component: "KeywordAnalysisOP",
        family: "Keyword",
        dashboard: "true",
        state: "websites-trafficSearch",
        titleState: "keywordAnalysis-organic",
        mobileState: "keywordAnalysis-mobileweb",
        title: "keywordAnalysis.organic.traffic.title",
        viewPermissions: {
            trafficSources: ["MobileWeb", "Desktop"],
        },
        hasWebSource: true,
        apiController: "KeywordAnalysisOP",
        availabilityComponent: "WsOverviewKeywords",
    },
    widgets: {
        single: {
            KeywordsTable: {
                properties: {},
                columns: [
                    {
                        fixed: true,
                        name: "row-selection",
                        cellTemp: "row-selection",
                        sortable: false,
                        width: 33,
                        disableHeaderCellHover: true,
                    },
                    {
                        fixed: true,
                        cellTemp: "index",
                        sortable: false,
                        width: 65,
                        disableHeaderCellHover: true,
                    },
                    {
                        name: "Domain",
                        fixed: true,
                        title: "Domain",
                        type: "string",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "True",
                        cellTemp: "keyword-analysis-traffic-source",
                        headTemp: "grouped-header-cell",
                        totalCount: "True",
                        tooltip: true,
                        width: 220,
                    },
                    {
                        name: "Share",
                        title: "Traffic Share",
                        type: "string",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "True",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "traffic-share",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: true,
                        width: 200,
                    },
                    {
                        name: "Change",
                        title: "Change",
                        type: "double",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "change-percentage",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: true,
                        width: 110,
                        ppt: {
                            overrideFormat: "smallNumbersPercentage:2",
                        },
                    },
                    {
                        name: "Position",
                        title: "Position",
                        type: "int",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "asc",
                        groupable: "False",
                        cellTemp: "keyword-analysis-position",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: true,
                        width: 80,
                    },
                    {
                        name: "Url",
                        title: "Destination URL",
                        type: "string",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "keyword-analysis-url",
                        cellCls: "url-cell",
                        cellClass: "url-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: true,
                        width: 275,
                    },
                    {
                        name: "Category",
                        title: "dropdown.category",
                        type: "string",
                        format: "prettifyCategory",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "default-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: true,
                        width: 220,
                    },
                    {
                        name: `Serp`,
                        trackingName: `Serp`,
                        title: "analysis.source.search.all.table.columns.featured.title",
                        tooltip: "analysis.source.search.all.table.columns.featured.title.tooltip",
                        cellTemp: "adsense-cell",
                        sortable: true,
                        width: 95,
                    },
                ],
                filters: {},
            },
            KeywordsDashboardTable: {
                properties: {
                    apiParams: {
                        pageSize: "10",
                    },
                    showMoreButtonItems: 5,
                    options: {
                        showFrame: true,
                        showLegend: false,
                        showOverflow: true,
                        dashboardSubtitleMarginBottom: 15,
                    },
                },
                columns: [
                    {
                        name: "Domain",
                        fixed: true,
                        title: "Domain",
                        type: "string",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "website-tooltip-top-no-expand-cell",
                        headTemp: "grouped-header-cell",
                        totalCount: "False",
                        tooltip: true,
                        minWidth: 220,
                    },
                    {
                        name: "Share",
                        title: "Traffic Share",
                        type: "string",
                        format: "percentagesign",
                        sortable: "False",
                        isSorted: "True",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "traffic-share-dashboard",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: true,
                        width: "115px",
                    },
                    {
                        name: "Change",
                        title: "Change",
                        type: "double",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "Change-percentage-dashboard",
                        headerComponent: "",
                        totalCount: "False",
                        tooltip: true,
                        minWidth: 110,
                        ppt: {
                            overrideFormat: "smallNumbersPercentage:2",
                        },
                    },
                    {
                        name: "Position",
                        title: "Pos.",
                        type: "int",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "asc",
                        groupable: "False",
                        cellTemp: "default-cell",
                        headerComponent: "",
                        totalCount: "False",
                        tooltip: true,
                        minWidth: 70,
                    },
                    {
                        name: "Url",
                        title: "Destination URL",
                        type: "string",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "keyword-analysis-url",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: true,
                        minWidth: 150,
                    },
                ],
                filters: {
                    orderBy: [
                        {
                            value: "TotalShare desc",
                            title: "Traffic Share",
                        },
                    ],
                },
            },
            KeywordsGraph: {
                properties: {
                    stacked: true,
                    options: {
                        showMarkersOnSingle: true,
                    },
                },
                x_axis: {
                    title: "Date",
                    type: "date",
                    format: "None",
                    name: "Date",
                    reversed: "False",
                },
                y_axis: {
                    title: "Visits",
                    type: "long",
                    format: "percentagesign",
                    formatParameter: 2,
                    name: "Visits",
                    reversed: "False",
                    yAxisMax: 1,
                },
                filters: {},
            },
            KeywordsGraphDashboard: {
                properties: {
                    stacked: true,
                    showMoreButton: true,
                    apiParams: {
                        pageSize: "10",
                    },
                    options: {
                        showMarkersOnSingle: true,
                    },
                },
                x_axis: {
                    title: "Date",
                    type: "date",
                    format: "None",
                    name: "Date",
                    reversed: "False",
                },
                y_axis: {
                    title: "Visits",
                    type: "long",
                    format: "percentagesign",
                    formatParameter: 2,
                    name: "Visits",
                    reversed: "False",
                    yAxisMax: 1,
                },
                filters: {},
            },
        },
        compare: {},
    },
};

export const KeywordAnalysisTotal = {
    ...KeywordAnalysisOrganic,
    id: "KeywordAnalysisTotal",
    properties: {
        component: "KeywordAnalysisTotal",
        family: "Keyword",
        dashboard: "true",
        state: "keywordAnalysis-total",
        titleState: "keywordAnalysis-total",
        title: "KeywordAnalysis.total.traffic.title",
        viewPermissions: {
            trafficSources: ["Total"],
        },
        hasWebSource: true,
        apiController: "KeywordAnalysisOP",
        availabilityComponent: "WsTotalKeywords",
    },
};

export const KeywordAnalysisGroupOrganic = {
    id: "KeywordAnalysisGroupOrganic",
    properties: {
        component: "KeywordAnalysisOP",
        family: "Keyword",
        dashboard: "true",
        state: "keywordAnalysis-organic",
        mobileState: "keywordAnalysis-mobileweb",
        title: "keywordAnalysis.organic.group.breakdown",
        viewPermissions: {
            trafficSources: ["MobileWeb", "Desktop"],
        },
        hasWebSource: true,
        apiController: "KeywordAnalysisOP",
        availabilityComponent: "WsOverviewKeywords",
    },
    widgets: {
        single: {
            defaultType: "KeywordsDashboardTable",
            KeywordsDashboardTable: {
                properties: {
                    showMoreButtonItems: 5,
                    options: {
                        showFrame: true,
                        showLegend: false,
                        showOverflow: true,
                        dashboardSubtitleMarginBottom: 15,
                    },
                },
                columns: [
                    {
                        name: "Keyword",
                        title: "Keyword",
                        type: "string",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "True",
                        cellTemp: "cell-keyword-dashboard",
                        headTemp: "grouped-header-cell",
                        totalCount: "True",
                        tooltip: true,
                        minWidth: 300,
                    },
                    {
                        name: "Share",
                        title: "Traffic Share",
                        type: "string",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "True",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "traffic-share",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: true,
                        minWidth: 100,
                    },
                    {
                        name: "Change",
                        title: "Change",
                        type: "double",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "change-percentage",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: true,
                        minWidth: 50,
                        ppt: {
                            overrideFormat: "smallNumbersPercentage:2",
                        },
                    },

                    {
                        name: "Cpc",
                        title: "CPC",
                        trackingName: "CPC",
                        displayName: "CPC",
                        tooltip: true,
                        headerComponent: DefaultCellHeaderRightAlign,
                        cellComponent: DefaultCellRightAlign,
                        format: "CPC",
                        sortable: true,
                        minWidth: 50,
                    },
                    {
                        name: "Volume",
                        title: "Volume",
                        displayName: "Volume",
                        tooltip: true,
                        cellTemplate: "default-cell",
                        trackingName: "Volume",
                        format: "abbrNumber",
                        sortable: true,
                        sortDirection: "desc",
                        headerComponent: DefaultCellHeaderRightAlign,
                        cellComponent: DefaultCellRightAlign,
                        minWidth: 50,
                    },
                ],
                filters: {
                    orderBy: [
                        {
                            value: "Share desc",
                            title: "Traffic Share",
                        },
                    ],
                },
            },
            KeywordsTable: {
                properties: {},
                columns: [
                    {
                        fixed: true,
                        cellTemp: "index",
                        sortable: false,
                        width: 65,
                        disableHeaderCellHover: true,
                    },
                    {
                        name: "Keyword",
                        title: "Keyword",
                        type: "string",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "True",
                        cellTemp: "keywordcell",
                        cellComponent: "keywordcell",
                        headTemp: "grouped-header-cell",
                        totalCount: "True",
                        tooltip: true,
                        minWidth: 300,
                    },
                    {
                        name: "Share",
                        title: "Traffic Share",
                        type: "string",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "True",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "traffic-share",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: true,
                        minWidth: 300,
                    },
                    {
                        name: "Change",
                        title: "Change",
                        type: "double",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "change-percentage",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: true,
                        minWidth: 150,
                        ppt: {
                            overrideFormat: "smallNumbersPercentage:2",
                        },
                    },

                    {
                        name: "Cpc",
                        title: "CPC",
                        trackingName: "CPC",
                        displayName: "CPC",
                        tooltip: true,
                        headerComponent: DefaultCellHeaderRightAlign,
                        cellComponent: DefaultCellRightAlign,
                        format: "CPC",
                        sortable: true,
                        minWidth: 150,
                    },
                    {
                        name: "Volume",
                        title: "Volume",
                        displayName: "Volume",
                        tooltip: true,
                        cellTemplate: "default-cell",
                        trackingName: "Volume",
                        format: "abbrNumber",
                        sortable: true,
                        sortDirection: "desc",
                        minWidth: 150,
                    },
                ],
                filters: {},
            },
        },
        compare: {},
    },
};

export const KeywordAnalysisGroupPaid = {
    id: "KeywordAnalysisGroupPaid",
    properties: {
        component: "KeywordAnalysisOP",
        family: "Keyword",
        dashboard: "true",
        state: "keywordAnalysis-paid",
        title: "keywordAnalysis.paid.group.breakdown",
        viewPermissions: {
            trafficSources: ["Desktop"],
        },
        apiController: "KeywordAnalysisOP",
        availabilityComponent: "WsPaidKeywords",
    },
    widgets: {
        single: {
            defaultType: "KeywordsDashboardTable",
            KeywordsTable: {
                properties: {},
                columns: [
                    {
                        fixed: true,
                        cellTemp: "index",
                        sortable: false,
                        width: 65,
                        disableHeaderCellHover: true,
                    },
                    {
                        name: "Keyword",
                        title: "Keyword",
                        type: "string",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "True",
                        cellTemp: "keywordcell",
                        cellComponent: "keywordcell",
                        headTemp: "grouped-header-cell",
                        totalCount: "True",
                        tooltip: true,
                        minWidth: 300,
                    },
                    {
                        name: "Share",
                        title: "Traffic Share",
                        type: "string",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "True",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "traffic-share",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: true,
                        minWidth: 300,
                    },
                    {
                        name: "Change",
                        title: "Change",
                        type: "double",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "change-percentage",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: true,
                        minWidth: 150,
                        ppt: {
                            overrideFormat: "smallNumbersPercentage:2",
                        },
                    },

                    {
                        name: "Cpc",
                        title: "CPC",
                        trackingName: "CPC",
                        displayName: "CPC",
                        tooltip: true,
                        headerComponent: DefaultCellHeaderRightAlign,
                        cellComponent: DefaultCellRightAlign,
                        format: "CPC",
                        sortable: true,
                        minWidth: 150,
                    },
                    {
                        name: "Volume",
                        title: "Volume",
                        displayName: "Volume",
                        tooltip: true,
                        cellTemplate: "default-cell",
                        trackingName: "Volume",
                        format: "abbrNumber",
                        sortable: true,
                        sortDirection: "desc",
                        minWidth: 150,
                    },
                ],
                filters: {},
            },
            KeywordsDashboardTable: {
                properties: {
                    showMoreButtonItems: 5,
                    options: {
                        showFrame: true,
                        showLegend: false,
                        showOverflow: true,
                        dashboardSubtitleMarginBottom: 15,
                    },
                },
                columns: [
                    {
                        name: "Keyword",
                        title: "Keyword",
                        type: "string",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "True",
                        cellTemp: "cell-keyword-dashboard",
                        headTemp: "grouped-header-cell",
                        totalCount: "True",
                        tooltip: true,
                        minWidth: 300,
                    },
                    {
                        name: "Share",
                        title: "Traffic Share",
                        type: "string",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "True",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "traffic-share",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: true,
                        minWidth: 100,
                    },
                    {
                        name: "Change",
                        title: "Change",
                        type: "double",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "change-percentage",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: true,
                        minWidth: 50,
                        ppt: {
                            overrideFormat: "smallNumbersPercentage:2",
                        },
                    },

                    {
                        name: "Cpc",
                        title: "CPC",
                        trackingName: "CPC",
                        displayName: "CPC",
                        tooltip: true,
                        headerComponent: DefaultCellHeaderRightAlign,
                        cellComponent: DefaultCellRightAlign,
                        format: "CPC",
                        sortable: true,
                        minWidth: 50,
                    },
                    {
                        name: "Volume",
                        title: "Volume",
                        displayName: "Volume",
                        tooltip: true,
                        cellTemplate: "default-cell",
                        trackingName: "Volume",
                        format: "abbrNumber",
                        sortable: true,
                        sortDirection: "desc",
                        headerComponent: DefaultCellHeaderRightAlign,
                        cellComponent: DefaultCellRightAlign,
                        minWidth: 50,
                    },
                ],
                filters: {},
            },
        },
        compare: {},
    },
};

export const KeywordAnalysisGroupTotal = {
    id: "KeywordAnalysisGroupTotal",
    properties: {
        component: "KeywordAnalysisOP",
        family: "Keyword",
        dashboard: "true",
        state: "keywordAnalysis-total",
        title: "keywordAnalysis.total.group.breakdown",
        viewPermissions: {
            trafficSources: ["Desktop"],
        },
        apiController: "KeywordAnalysisOP",
        availabilityComponent: "WsTotalKeywords",
    },
    widgets: {
        single: {
            defaultType: "KeywordsDashboardTable",
            KeywordsTable: {
                properties: {},
                columns: [
                    {
                        fixed: true,
                        cellTemp: "index",
                        sortable: false,
                        width: 65,
                        disableHeaderCellHover: true,
                    },
                    {
                        name: "Keyword",
                        title: "Keyword",
                        type: "string",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "True",
                        cellTemp: "keywordcell",
                        cellComponent: "keywordcell",
                        headTemp: "grouped-header-cell",
                        totalCount: "True",
                        tooltip: true,
                        minWidth: 300,
                    },
                    {
                        name: "Share",
                        title: "Traffic Share",
                        type: "string",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "True",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "traffic-share",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: true,
                        minWidth: 300,
                    },
                    {
                        name: "Change",
                        title: "Change",
                        type: "double",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "change-percentage",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: true,
                        minWidth: 150,
                        ppt: {
                            overrideFormat: "smallNumbersPercentage:2",
                        },
                    },
                    {
                        name: "Volume",
                        title: "Volume",
                        displayName: "Volume",
                        tooltip: true,
                        cellTemplate: "default-cell",
                        trackingName: "Volume",
                        format: "abbrNumber",
                        sortable: true,
                        sortDirection: "desc",
                        minWidth: 150,
                    },
                ],
                filters: {},
            },
            KeywordsDashboardTable: {
                properties: {
                    showMoreButtonItems: 5,
                    options: {
                        showFrame: true,
                        showLegend: false,
                        showOverflow: true,
                        dashboardSubtitleMarginBottom: 15,
                    },
                },
                columns: [
                    {
                        name: "Keyword",
                        title: "Keyword",
                        type: "string",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "True",
                        cellTemp: "cell-keyword-dashboard",
                        headTemp: "grouped-header-cell",
                        totalCount: "True",
                        tooltip: true,
                        minWidth: 300,
                    },
                    {
                        name: "Share",
                        title: "Traffic Share",
                        type: "string",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "True",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "traffic-share",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: true,
                        minWidth: 100,
                    },
                    {
                        name: "Change",
                        title: "Change",
                        type: "double",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "change-percentage",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: true,
                        minWidth: 50,
                        ppt: {
                            overrideFormat: "smallNumbersPercentage:2",
                        },
                    },
                    {
                        name: "Volume",
                        title: "Volume",
                        displayName: "Volume",
                        tooltip: true,
                        cellTemplate: "default-cell",
                        trackingName: "Volume",
                        format: "abbrNumber",
                        sortable: true,
                        sortDirection: "desc",
                        headerComponent: DefaultCellHeaderRightAlign,
                        cellComponent: DefaultCellRightAlign,
                        minWidth: 50,
                    },
                ],
                filters: {},
            },
        },
        compare: {},
    },
};

export const KeywordAnalysisPaid = {
    id: "KeywordAnalysisPaid",
    properties: {
        component: "KeywordAnalysisOP",
        dashboard: "true",
        state: "websites-trafficSearch",
        titleState: "keywordAnalysis-paid",
        title: "KeywordAnalysis.paid.traffic.title",
        family: "Keyword",
        webSource: "Desktop",
        apiController: "KeywordAnalysisOP",
        availabilityComponent: "WsPaidKeywords",
    },
    widgets: {
        single: {
            KeywordsTable: {
                properties: {},
                columns: [
                    {
                        fixed: true,
                        name: "row-selection",
                        cellTemp: "row-selection",
                        sortable: false,
                        width: 33,
                        disableHeaderCellHover: true,
                    },
                    {
                        fixed: true,
                        cellTemp: "index",
                        sortable: false,
                        width: 65,
                        disableHeaderCellHover: true,
                    },
                    {
                        name: "Domain",
                        fixed: true,
                        title: "Domain",
                        type: "string",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "True",
                        cellTemp: "keyword-analysis-traffic-source",
                        headTemp: "grouped-header-cell",
                        totalCount: "True",
                        tooltip: true,
                        width: 220,
                    },
                    {
                        name: "Share",
                        title: "Traffic Share",
                        type: "string",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "True",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "traffic-share",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: true,
                        width: 275,
                    },
                    {
                        name: "Change",
                        title: "Change",
                        type: "double",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "change-percentage",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: true,
                        width: 110,
                        ppt: {
                            overrideFormat: "smallNumbersPercentage:2",
                        },
                    },
                    {
                        name: "Position",
                        title: "Position",
                        type: "int",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "asc",
                        groupable: "False",
                        cellTemp: "keyword-analysis-position",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        tooltip: true,
                        width: 90,
                    },
                    {
                        name: "Url",
                        title: "Destination URL",
                        type: "string",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "keyword-analysis-url",
                        cellCls: "url-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: true,
                        width: 275,
                    },
                    {
                        name: "Category",
                        title: "dropdown.category",
                        type: "string",
                        format: "prettifyCategory",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "default-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: true,
                        minWidth: 220,
                    },
                ],
                filters: {},
            },
            KeywordsDashboardTable: {
                properties: {
                    apiParams: {
                        pageSize: "10",
                    },
                    showMoreButtonItems: 5,
                    options: {
                        showFrame: true,
                        showLegend: false,
                        showOverflow: true,
                        dashboardSubtitleMarginBottom: 15,
                    },
                },
                columns: [
                    {
                        name: "Domain",
                        fixed: true,
                        title: "Domain",
                        type: "string",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "website-tooltip-top-no-expand-cell",
                        headTemp: "grouped-header-cell",
                        totalCount: "False",
                        tooltip: true,
                        minWidth: 220,
                    },
                    {
                        name: "Share",
                        title: "Traffic Share",
                        type: "string",
                        format: "percentagesign",
                        sortable: "False",
                        isSorted: "True",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "traffic-share-dashboard",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: true,
                        width: "115px",
                    },
                    {
                        name: "Change",
                        title: "Change",
                        type: "double",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "Change-percentage-dashboard",
                        headerComponent: "",
                        totalCount: "False",
                        tooltip: true,
                        minWidth: 110,
                        ppt: {
                            overrideFormat: "smallNumbersPercentage:2",
                        },
                    },
                    {
                        name: "Position",
                        title: "Pos.",
                        type: "int",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "asc",
                        groupable: "False",
                        cellTemp: "default-cell",
                        headerComponent: "",
                        totalCount: "False",
                        tooltip: true,
                        minWidth: 70,
                    },
                    {
                        name: "Url",
                        title: "Destination URL",
                        type: "string",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "keyword-analysis-url",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: true,
                        minWidth: 150,
                    },
                ],
                filters: {
                    orderBy: [
                        {
                            value: "TotalShare desc",
                            title: "Traffic Share",
                        },
                    ],
                },
            },
            KeywordsGraph: {
                properties: {
                    hideMarkersOnDaily: false,
                    stacked: true,
                },
                x_axis: {
                    title: "Date",
                    type: "date",
                    format: "None",
                    name: "Date",
                    reversed: "False",
                },
                y_axis: {
                    title: "Visits",
                    type: "long",
                    format: "percentagesign",
                    formatParameter: 2,
                    name: "Visits",
                    reversed: "False",
                    yAxisMax: 1,
                },
                filters: {},
            },
            KeywordsGraphDashboard: {
                properties: {
                    hideMarkersOnDaily: false,
                    showMoreButton: true,
                    stacked: true,
                    apiParams: {
                        pageSize: "10",
                    },
                },
                x_axis: {
                    title: "Date",
                    type: "date",
                    format: "None",
                    name: "Date",
                    reversed: "False",
                },
                y_axis: {
                    title: "Visits",
                    type: "long",
                    format: "percentagesign",
                    formatParameter: 2,
                    name: "Visits",
                    reversed: "False",
                    yAxisMax: 1,
                },
                filters: {},
            },
        },
        compare: {},
    },
};

export const KeywordAnalysisTrafficShare = {
    id: "KeywordAnalysisTrafficShare",
    properties: {
        component: "KeywordAnalysisOP",
        family: "Keyword",
        dashboard: "true",
        state: "keywordAnalysis-organic",
        mobileState: "keywordAnalysis-mobileweb",
        title: "keywordAnalysis.organic.widgets.trafficshare",
        apiController: "KeywordAnalysisOP",
        availabilityComponent: "WsWebSearchCompetitors",
    },
    widgets: {
        single: {
            PieChart: {
                properties: {
                    options: {
                        showLegend: false,
                        dashboardSubtitleMarginBottom: 15,
                    },
                },
                objects: {
                    Organic: {
                        name: "Organic",
                        title: "Organic",
                        type: "double",
                        format: "None",
                        cellTemp: "",
                    },
                    Paid: {
                        name: "Paid",
                        title: "Paid",
                        type: "double",
                        format: "None",
                        cellTemp: "",
                    },
                },
            },
        },
        compare: {},
    },
};

export const KeywordAnalysisTrafficShareOverTime = {
    id: "KeywordAnalysisTrafficShareOverTime",
    properties: {
        component: "KeywordAnalysisOPTotal",
        family: "Keyword",
        dashboard: "true",
        state: "keywordAnalysis-organic",
        mobileState: "keywordAnalysis-mobileweb",
        title: "keywordAnalysis.organic.widgets.totalsearchvisits",
        apiController: "KeywordAnalysisOP",
        disableWindowInDatepicker: false,
        availabilityComponent: "WsWebSearchCompetitors",
    },
    widgets: {
        single: {
            defaultType: "KeywordAnalysisTotalVisits",
            KeywordAnalysisTotalVisits: {
                properties: {
                    options: {
                        showLegend: false,
                        dashboardSubtitleMarginBottom: 15,
                    },
                },
            },
        },
        compare: {},
    },
};

export const KeywordAnalysisVolumes = {
    id: "KeywordAnalysisVolumes",
    properties: {
        component: "KeywordAnalysisOPTotal",
        family: "Keyword",
        dashboard: "true",
        state: "keywordAnalysis-organic",
        title: "KeywordAnalysis.organic.widgets.searches",
        webSource: "Desktop",
        subtitle: "KeywordAnalysis.organic.searchVolume.subtitle",
        apiController: "KeywordAnalysisOP",
        availabilityComponent: "WsPaidKeywords",
    },
    widgets: {
        single: {
            SingleMetric: {
                properties: {
                    apiController: "KeywordAnalysisOP",
                    height: 82,
                    loadingHeight: "87px",
                    family: "Keyword",
                    options: {
                        showTitleTooltip: false,
                        showOverflow: true,
                        showLegend: false,
                        showSettings: true,
                        showTopLine: false,
                        titleIcon: false,
                        template: "/app/pages/keyword-analysis/templates/searches-dashboard.html",
                    },
                },
                objects: {
                    Volume: {
                        name: "Volume",
                        title: "",
                        type: "double",
                        format: "abbrNumber",
                        cellTemp: "large-number",
                    },
                    VolumesMonthly: {
                        name: "VolumesMonthly",
                        title: "",
                        type: "long[]",
                        format: "None",
                        cellTemp: "large-number",
                        ppt: {
                            ignoreRow: true,
                        },
                    },
                },
            },
        },
        compare: {},
    },
};
