/**
 * Created by liorb on 12/18/2016.
 */
import { DefaultCellHeaderRightAlign } from "../../../React/Table/headerCells/DefaultCellHeaderRightAlign";

export const SimilarSites = {
    id: "SimilarSites",
    properties: {
        component: "WebsiteCompetitors",
        title: "analysis.common.competitors.similar.title",
        family: "Website",
        order: "1",
        keyPrefix: "$",
        state: "websites-worldwideOverview",
        forceState: true,
    },
    widgets: {
        single: {
            Table: {
                properties: {},
                columns: [
                    {
                        fixed: true,
                        cellTemp: "index",
                        sortable: false,
                        width: 40,
                        disableHeaderCellHover: true,
                    },
                    {
                        fixed: true,
                        name: "Domain",
                        title: "analysis.competitors.similar.table.columns.domain.title",
                        type: "string",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "website-tooltip-top-cell",
                        tooltip: "analysis.competitors.similar.table.columns.domain.title.tooltip",
                        headTemp: "",
                        totalCount: "True",
                        width: 304,
                    },
                    {
                        name: "Category",
                        title: "analysis.competitors.similar.table.columns.category.title",
                        type: "string",
                        sortable: true,
                        isSorted: false,
                        sortDirection: "desc",
                        groupable: false,
                        cellTemp: "category-filter-cell",
                        tooltip:
                            "analysis.competitors.similar.table.columns.category.title.tooltip",
                        headTemp: "",
                        totalCount: false,
                        isResizable: true,
                        minWidth: 304,
                    },
                    {
                        name: "Rank",
                        title: "analysis.competitors.similar.table.columns.rank.title",
                        type: "long",
                        format: "swRank",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "asc",
                        groupable: "False",
                        cellTemp: "rank-cell",
                        tooltip: "analysis.competitors.similar.table.columns.rank.title.tooltip",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        isResizable: true,
                        minWidth: 108,
                    },
                    {
                        name: "Affinity",
                        title: "analysis.competitors.similar.table.columns.share.title",
                        type: "string",
                        format: "percentagesign",
                        sortable: true,
                        isSorted: true,
                        sortDirection: "desc",
                        groupable: false,
                        cellTemp: "traffic-share",
                        tooltip: "analysis.competitors.similar.table.columns.share.title.tooltip",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: false,
                        isResizable: true,
                        minWidth: 180,
                    },
                    {
                        name: "HasAdsense",
                        title: "analysis.all.table.columns.googleAds.title",
                        type: "bool",
                        format: "None",
                        sortable: true,
                        isSorted: false,
                        sortDirection: "desc",
                        groupable: false,
                        cellTemp: "adsense-cell",
                        tooltip: "analysis.all.table.columns.googleAds.title.tooltip",
                        headTemp: "",
                        totalCount: false,
                        width: 77,
                    },
                ],
                filters: {
                    orderBy: [
                        {
                            value: "Affinity desc",
                            title: "Affinity",
                        },
                    ],
                },
            },
        },
        compare: {
            Table: {
                properties: {},
                columns: [
                    {
                        fixed: true,
                        cellTemp: "index",
                        sortable: false,
                        width: 65,
                        disableHeaderCellHover: true,
                    },
                    {
                        fixed: true,
                        name: "Domain",
                        title: "analysis.competitors.similar.table.columns.domain.title",
                        type: "string",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "website-tooltip-top-cell",
                        tooltip: "analysis.competitors.similar.table.columns.domain.title.tooltip",
                        headTemp: "",
                        totalCount: "True",
                        width: 173,
                    },
                    {
                        name: "Category",
                        title: "analysis.competitors.similar.table.columns.category.title",
                        type: "string",
                        format: "prettifyCategory",
                        sortable: true,
                        isSorted: false,
                        sortDirection: "desc",
                        groupable: false,
                        cellTemp: "category-filter-cell",
                        tooltip:
                            "analysis.competitors.similar.table.columns.category.title.tooltip",
                        headTemp: "",
                        totalCount: false,
                        minWidth: 150,
                    },
                    {
                        name: "Rank",
                        title: "analysis.competitors.similar.table.columns.rank.title",
                        type: "long",
                        format: "swRank",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "asc",
                        groupable: "False",
                        cellTemp: "rank-cell",
                        tooltip: "analysis.competitors.similar.table.columns.rank.title.tooltip",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: "False",
                        width: 280,
                    },
                    {
                        name: "Affinity",
                        title: "analysis.competitors.similar.table.columns.share.title",
                        type: "string",
                        format: "percentagesign",
                        sortable: true,
                        isSorted: true,
                        sortDirection: "desc",
                        groupable: false,
                        cellTemp: "traffic-share",
                        tooltip: "analysis.competitors.similar.table.columns.share.title.tooltip",
                        headerComponent: DefaultCellHeaderRightAlign,
                        totalCount: false,
                        width: 285,
                    },
                    {
                        name: "HasAdsense",
                        title: "analysis.all.table.columns.googleAds.title",
                        type: "bool",
                        format: "None",
                        sortable: true,
                        isSorted: false,
                        sortDirection: "desc",
                        groupable: false,
                        cellTemp: "adsense-cell",
                        tooltip: "analysis.all.table.columns.googleAds.title.tooltip",
                        headTemp: "",
                        totalCount: false,
                        maxWidth: 120,
                    },
                ],
                filters: {
                    orderBy: [
                        {
                            value: "Affinity desc",
                            title: "Affinity",
                        },
                    ],
                },
            },
        },
    },
};

export const PopularPages = {
    id: "PopularPages",
    properties: {
        title: "analysis.common.content.pop.pages",
        family: "Website",
        component: "PopularPages",
        hasWebSource: true,
        apiController: "PopularPages",
        order: "1",
        androidOnly: "true",
        state: "websites-popular",
        dashboard: "true",
        viewPermissions: {
            trafficSources: ["Total"],
        },
        noCompare: true,
        customFetcherFactory: {
            path: "popularPages.popularPagesFiltersState",
            factoryName: "PopularPagesDataFetcherFactory",
        },
        availabilityComponent: "WsWebContentPages",
    },
    widgets: {
        single: {
            defaultType: "PopularPagesTable",
            PopularPagesTable: {
                properties: {
                    showMoreButtonItems: 5,
                    options: {
                        showFrame: true,
                        showLegend: false,
                        showOverflow: true,
                        dashboardSubtitleMarginBottom: 15,
                    },
                },
                columns: [
                    {
                        name: "Page",
                        title: "URL",
                        type: "string",
                        format: "None",
                        sortable: false,
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "link-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: "analysis.content.pop.pages.table.columns.domain.title.tooltip",
                        minWidth: 300,
                    },
                    {
                        name: "Share",
                        title: "analysis.content.pop.pages.table.columns.share.title",
                        type: "string",
                        format: "smallNumbersPercentage:2",
                        sortable: "False",
                        isSorted: "True",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "default-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: "analysis.content.pop.pages.table.columns.share.title.tooltip",
                        width: "115px",
                    },
                    {
                        name: "ChangeInShare",
                        title: "global.change",
                        type: "double",
                        format: "percentagesign",
                        sortable: true,
                        isSorted: false,
                        sortDirection: "desc",
                        groupable: false,
                        cellTemp: "change-percentage",
                        totalCount: false,
                        tooltip: "widget.table.tooltip.searchkeywordsabb.change",
                        width: 110,
                    },
                ],
                filters: {
                    orderBy: [
                        {
                            value: "Share desc",
                            title: "Share",
                        },
                    ],
                },
            },
        },
    },
};
export const LeadingFolders = {
    id: "LeadingFolders",
    properties: {
        title: "analysis.common.content.pop.folders",
        dashboard: "true",
        hasWebSource: true,
        family: "Website",
        component: "PopularPages",
        apiController: "LeadingFolders",
        order: "1",
        androidOnly: "true",
        state: "websites-folders",
        stateParams: {
            selectedTab: "folders",
        },
        noCompare: true,
        viewPermissions: {
            trafficSources: ["Toal"],
        },
        availabilityComponent: "WsWebContentFolders",
    },
    widgets: {
        single: {
            defaultType: "LeadingFoldersTable",
            LeadingFoldersTable: {
                properties: {
                    showMoreButtonItems: 5,
                    options: {
                        showLegend: false,
                        dashboardSubtitleMarginBottom: 15,
                    },
                },
                columns: [
                    {
                        name: "Folder",
                        title: "Folder",
                        type: "string",
                        format: "None",
                        sortable: false,
                        isSorted: false,
                        sortDirection: "desc",
                        groupable: false,
                        cellTemp: "link-cell",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: false,
                        width: "",
                    },
                    {
                        name: "Share",
                        title: "analysis.content.pop.pages.table.columns.share.title",
                        type: "string",
                        format: "percentagesign",
                        sortable: false,
                        isSorted: true,
                        sortDirection: "desc",
                        groupable: false,
                        cellTemp: "traffic-share",
                        headTemp: "",
                        totalCount: false,
                        tooltip: "analysis.content.pop.folders.table.columns.share.title.tooltip",
                        minWidth: 300,
                    },
                ],
                filters: {
                    orderBy: [
                        {
                            value: "Share desc",
                            title: "Share",
                        },
                    ],
                },
            },
        },
    },
};

export const SubDomains = {
    id: "SubDomains",
    properties: {
        title: "analysis.common.content.sub.title",
        family: "Website",
        component: "SubDomains",
        order: "1",
        androidOnly: "true",
        state: "websites-worldwideOverview",
    },
    widgets: {
        single: {
            Table: {
                properties: {},
                columns: [
                    {
                        // fixed: true,
                        cellTemp: "index",
                        sortable: false,
                        width: 65,
                        disableHeaderCellHover: true,
                    },
                    {
                        name: "Domain",
                        title: "Domain",
                        type: "string",
                        format: "None",
                        sortable: true,
                        isSorted: false,
                        sortDirection: "desc",
                        groupable: false,
                        cellTemp: "website-tooltip-top-cell",
                        headTemp: "",
                        totalCount: true,
                        tooltip: "analysis.content.sub.table.columns.domain.title.tooltip",
                        minWidth: 500,
                    },
                    {
                        name: "Share",
                        title: "Traffic Share",
                        type: "string",
                        format: "percentagesign",
                        sortable: true,
                        isSorted: true,
                        sortDirection: "desc",
                        groupable: false,
                        cellTemp: "traffic-share",
                        headTemp: "",
                        totalCount: false,
                        tooltip: "analysis.content.sub.table.columns.share.title.tooltip",
                        minWidth: 300,
                    },
                ],
                filters: {
                    orderBy: [],
                },
            },
        },
        compare: {
            Table: {
                properties: {},
                columns: [
                    {
                        // fixed: true,
                        cellTemp: "index",
                        sortable: false,
                        width: 65,
                        disableHeaderCellHover: true,
                    },
                    {
                        name: "Domain",
                        title: "Domain",
                        type: "string",
                        format: "None",
                        sortable: "True",
                        isSorted: "False",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "website-tooltip-top-cell",
                        headTemp: "",
                        totalCount: "True",
                        tooltip: "analysis.content.sub.table.columns.domain.title.tooltip",
                        minWidth: 500,
                    },
                    {
                        name: "Share",
                        title: "Traffic Share",
                        type: "string",
                        format: "percentagesign",
                        sortable: "True",
                        isSorted: "True",
                        sortDirection: "desc",
                        groupable: "False",
                        cellTemp: "traffic-share",
                        headTemp: "",
                        totalCount: "False",
                        tooltip: "analysis.content.sub.table.columns.share.title.tooltip",
                        minWidth: 300,
                    },
                ],
                filters: {},
            },
        },
    },
};
