export const SYNC_CONFLICT_HEADER_MODEL = 'model',
      SYNC_CONFLICT_HEADER_ID = 'id',
      SYNC_CONFLICT_HEADER_NAME = 'nameOrId',
      SYNC_CONFLICT_HEADER_KEY = 'key',
      SYNC_CONFLICT_HEADER_SERVER_VALUE = 'serverValue',
      SYNC_CONFLICT_HEADER_LOCAL_VALUE = 'localValue',
      SYNC_CONFLICT_HEADER_IS_LOCAL_SELECTED = 'isLocalSelected',
      SYNC_CONFLICT_HEADER_IS_SERVER_SELECTED = 'isServerSelected';
