import { SYNC_CONFLICT_HEADER_MODEL,
         SYNC_CONFLICT_HEADER_ID,
         SYNC_CONFLICT_HEADER_NAME,
         SYNC_CONFLICT_HEADER_KEY,
         SYNC_CONFLICT_HEADER_SERVER_VALUE,
         SYNC_CONFLICT_HEADER_LOCAL_VALUE,
         SYNC_CONFLICT_HEADER_IS_LOCAL_SELECTED,
         SYNC_CONFLICT_HEADER_IS_SERVER_SELECTED } from './SyncConflictsHeaderKeys';

let SYNC_CONFLICT_HEADER_VALUE_MAP = {};

SYNC_CONFLICT_HEADER_VALUE_MAP[SYNC_CONFLICT_HEADER_MODEL] = 'Item Type';
SYNC_CONFLICT_HEADER_VALUE_MAP[SYNC_CONFLICT_HEADER_ID] = 'Item Id';
SYNC_CONFLICT_HEADER_VALUE_MAP[SYNC_CONFLICT_HEADER_NAME] = 'Item Id / Item Name';
SYNC_CONFLICT_HEADER_VALUE_MAP[SYNC_CONFLICT_HEADER_KEY] = 'Property Name';
SYNC_CONFLICT_HEADER_VALUE_MAP[SYNC_CONFLICT_HEADER_SERVER_VALUE] = 'Server Value';
SYNC_CONFLICT_HEADER_VALUE_MAP[SYNC_CONFLICT_HEADER_LOCAL_VALUE] = 'Local Value';


export default SYNC_CONFLICT_HEADER_VALUE_MAP;
