import React from 'react';
import _t from 'i18n!nls/asset-admin';
import CdsMigrationTypography from 'bundles/authoring/common/components/cds/CdsMigrationTypography';
import { SvgFlashFilled } from '@coursera/coursera-ui/svg';
import { FormattedMessage } from 'js/lib/coursera.react-intl';
import TooltipWrapper from 'bundles/authoring/common/components/TooltipWrapper';
import { color } from '@coursera/coursera-ui';
import { getReadableConfidenceLevel } from 'bundles/asset-admin/utils/AutoGeneratedTagUtils';

import 'css!./__styles__/AutoGeneratedImageAssetTableTag';

type InputProps = {
  confidenceLevel?: number;
  description: string;
};

const AutoGeneratedImageAssetTableTag: React.FC<InputProps> = ({ confidenceLevel, description }) => {
  const readableConfidenceLevel = getReadableConfidenceLevel(confidenceLevel);

  return (
    <div className="rc-AutoGeneratedImageAssetTableTag">
      <div className="flex-container">
        <TooltipWrapper tooltipId="auto-generated-accurary-level" message={description} placement="top">
          <div className="flash-icon">
            <SvgFlashFilled size={16} color={color.success} />
          </div>
          <div className="auto-gen-accuracy-label">
            <CdsMigrationTypography variant="body2" cuiComponentName="Caption">
              <FormattedMessage
                message={_t('Auto-generated: {confidenceLevel}% accuracy')}
                confidenceLevel={readableConfidenceLevel}
              />
            </CdsMigrationTypography>
          </div>
        </TooltipWrapper>
      </div>
    </div>
  );
};

export default AutoGeneratedImageAssetTableTag;
