'use es6';

export var SET_REGISTER_FROM_NUMBER_TYPE = 'SET_REGISTER_FROM_NUMBER_TYPE';
export var SET_SHOULD_SHOW_ONBOARDING_INTRO = 'SET_SHOULD_SHOW_ONBOARDING_INTRO';
export var RESET_ONBOARDING_STATE = 'RESET_ONBOARDING_STATE';