'use es6';

export var BROWSER_NOTIFICATION_LAST_SUBSCRIBED = 'BROWSER_NOTIFICATION_LAST_SUBSCRIBED';
export var BROWSER_NOTIFICATION_PRE_PERMISSION_POPUP_ACCEPT_TIME = 'BROWSER_NOTIFICATION_PRE_PERMISSION_POPUP_ACCEPT_TIME';
export var BROWSER_NOTIFICATION_PRE_PERMISSION_POPUP_DISMISS_TIME = 'BROWSER_NOTIFICATION_PRE_PERMISSION_POPUP_DISMISS_TIME';
export var BROWSER_SUBSCRIPTION_TIMEOUT = 86400000;
export var BROWSER_NOTIFICATION_PRE_PERMISSION_POPUP_RESHOW_THRESHOLD = 21 * 86400000; // THREE WEEKS

export var GRANTED = 'granted';
export var DENY = 'denied';