'use es6';

export var SALES_SUBSCRIPTION = 'SALES_SUBSCRIPTION';
export var ACTIVE_ENROLLMENTS = 'ACTIVE_ENROLLMENTS';
export var MISSING_EMAIL = 'MISSING_EMAIL';
export var INVALID_EMAIL = 'INVALID_EMAIL';