'use es6';

export var CLICKED = 'CLICKED';
export var ENROLLED = 'ENROLLED';
export var REPLIED = 'REPLIED';
export var OPENED = 'OPENED';
export var BOUNCED = 'BOUNCED';
export var SCHEDULED_MEETING = 'SCHEDULED_MEETING';
export var UNSUBSCRIBED = 'UNSUBSCRIBED';
export var EnrollmentEngagementEventTypes = {
  ENROLLED: ENROLLED,
  CLICKED: CLICKED,
  OPENED: OPENED,
  REPLIED: REPLIED,
  SCHEDULED_MEETING: SCHEDULED_MEETING,
  BOUNCED: BOUNCED
};
export var ALLEnrollmentEngagementEventTypes = {
  ENROLLED: ENROLLED,
  OPENED: OPENED,
  CLICKED: CLICKED,
  REPLIED: REPLIED,
  SCHEDULED_MEETING: SCHEDULED_MEETING,
  UNSUBSCRIBED: UNSUBSCRIBED,
  BOUNCED: BOUNCED
};