'use es6';

export var FLOW_IDS_FETCH_STARTED = 'FLOW_IDS_FETCH_STARTED';
export var FLOW_IDS_FETCH_SUCCEEDED = 'FLOW_IDS_FETCH_SUCCEEDED';
export var FLOW_IDS_FETCH_FAILED = 'FLOW_IDS_FETCH_FAILED';
export var FLOWS_FETCH_STARTED = 'FLOWS_FETCH_STARTED';
export var FLOWS_FETCH_SUCCEEDED = 'FLOWS_FETCH_SUCCEEDED';
export var FLOWS_FETCH_FAILED = 'FLOWS_FETCH_FAILED';
export var FLOW_DELETE_SUCCEEDED = 'FLOW_DELETE_SUCCEEDED';
export var FLOW_UPDATE_SUCCEEDED = 'FLOW_UPDATE_SUCCEEDED';
export var FLOW_CREATE_SUCCEEDED = 'FLOW_CREATE_SUCCEEDED';
export var FLOW_CREATE_FAILED = 'FLOW_CREATE_FAILED';