'use es6';

export var START_CALL = 'START_CALL';
export var END_CALL = 'END_CALL';
export var START_CALL_FAILED = 'START_CALL_FAILED';
export var VIEWED_INITIALIZATION_ERROR = 'VIEWED_INITIALIZATION_ERROR';
export var VIEWED_WIDGET_ERROR = 'VIEWED_WIDGET_ERROR';