'use es6';

export var PERSISTENT_NOTIFICATIONS_HAS_BANNER_NOTIFICATIONS = 'HAS_BANNER_NOTIFICATIONS';
export var PERSISTENT_NOTIFICATIONS_LAST_CHECKED = 'LAST_CHECKED';
export var CACHE_TIMEOUT = 600000; // 10 minutes

export var ACTION_READ = 'MARKED_AS_READ';
export var ACTION_CLICKED = 'CTA_CLICKED';