'use es6';

export var SEQUENCE_REPORT_FETCH_QUEUED = 'SEQUENCE_REPORT_FETCH_QUEUED';
export var SEQUENCE_REPORT_FETCH_SUCCEEDED = 'SEQUENCE_REPORT_FETCH_SUCCEEDED';
export var SEQUENCE_REPORT_FETCH_FAILED = 'SEQUENCE_REPORT_FETCH_FAILED';