'use es6';

export var FOLDERS_FETCH_SUCCESS = 'FOLDERS_FETCH_SUCCESS';
export var FOLDERS_FETCH_FAILED = 'FOLDERS_FETCH_FAILED';
export var FETCH_ERROR = 'FETCH_ERROR';
export var BATCH_TEMPLATE_DELETE_SUCCEEDED = 'BATCH_TEMPLATE_DELETE_SUCCEEDED';
export var BATCH_TEMPLATE_REFRESH_QUEUED = 'BATCH_TEMPLATE_REFRESH_QUEUED';
export var CREATE_SUCCESS = 'CREATE_SUCCESS';
export var TEMPLATE_SEARCH_FETCH_SUCCEEDED = 'TEMPLATE_SEARCH_FETCH_SUCCEEDED';
export var TEMPLATE_SEARCH_FETCH_FAILED = 'TEMPLATE_SEARCH_FETCH_FAILED';
export var V2_TEMPLATE_SEARCH_FETCH_SUCCEEDED = 'V2_TEMPLATE_SEARCH_FETCH_SUCCEEDED';
export var TEMPLATE_SEARCH_UPDATE_QUERY = 'TEMPLATE_SEARCH_UPDATE_QUERY';
export var FETCH_TEMPLATE_USAGE_SUCCESS = 'FETCH_TEMPLATE_USAGE_SUCCESS';
export var FETCH_TEMPLATE_USAGE_FAILURE = 'FETCH_TEMPLATE_USAGE_FAILURE';