'use es6';

export var MANUAL = 'MANUAL';
export var WORKFLOW = 'WORKFLOW';
export var REPLY = 'REPLY';
export var ERROR = 'ERROR';
export var THREAD_REPLY = 'THREAD_REPLY';
export var MEETING = 'MEETING';
export var ACCOUNT_REPLY = 'ACCOUNT_REPLY';
export var ACCOUNT_MEETING = 'ACCOUNT_MEETING';
export var SEQUENCE_DELETED = 'SEQUENCE_DELETED';
export var UnenrolledSourceTypes = {
  ACCOUNT_MEETING: ACCOUNT_MEETING,
  ACCOUNT_REPLY: ACCOUNT_REPLY,
  ERROR: ERROR,
  MANUAL: MANUAL,
  WORKFLOW: WORKFLOW,
  MEETING: MEETING,
  REPLY: REPLY,
  THREAD_REPLY: THREAD_REPLY
};