'use es6';

export var FETCH_PINNED_VIEWS_STARTED = 'FETCH_PINNED_VIEWS_STARTED';
export var FETCH_PINNED_VIEWS_SUCCEEDED = 'FETCH_PINNED_VIEWS_SUCCEEDED';
export var FETCH_PINNED_VIEWS_FAILED = 'FETCH_PINNED_VIEWS_FAILED';
export var SET_PINNED_VIEWS_STARTED = 'SET_PINNED_VIEWS_STARTED';
export var SET_PINNED_VIEWS_SUCCEEDED = 'SET_PINNED_VIEWS_SUCCEEDED';
export var SET_PINNED_VIEWS_FAILED = 'SET_PINNED_VIEWS_FAILED';