'use es6';

export var ACTIVE_BANNER_TYPES = {
  ACTIVE_INTERNAL: 'ACTIVE_INTERNAL',
  ACTIVE_MARKETING_PRO: 'ACTIVE_MARKETING_PRO',
  ACTIVE_OPERATIONS_PROFESSIONAL: 'ACTIVE_OPERATIONS_PROFESSIONAL',
  ACTIVE_SALES_PROFESSIONAL: 'ACTIVE_SALES_PROFESSIONAL',
  ACTIVE_TALK_TO_SALES: 'ACTIVE_TALK_TO_SALES'
};
export var EXPIRED_BANNER_TYPES = {
  EXPIRED_INTERNAL: 'EXPIRED_INTERNAL',
  EXPIRED_MARKETING_PRO: 'EXPIRED_MARKETING_PRO',
  EXPIRED_OPERATIONS_PROFESSIONAL: 'EXPIRED_OPERATIONS_PROFESSIONAL',
  EXPIRED_TALK_TO_SALES: 'EXPIRED_TALK_TO_SALES'
};