'use es6';

export var SET_ENGAGEMENT_DATA = 'SET_ENGAGEMENT_DATA';
export var SET_CALL_DISPOSITION = 'SET_CALL_DISPOSITION';
export var SET_ACTIVITY_TYPE = 'SET_ACTIVITY_TYPE';
export var SET_NOTES = 'SET_NOTES';
export var SET_NON_TWILIO_BET_PROPERTIES = 'SET_NON_TWILIO_BET_PROPERTIES';