'use es6';

export var PINNED_VIEWS_USER_UPDATE_QUEUED = 'PINNED_VIEWS_USER_UPDATE_QUEUED';
export var PINNED_VIEWS_USER_UPDATE_STARTED = 'PINNED_VIEWS_USER_UPDATE_STARTED';
export var PINNED_VIEWS_USER_UPDATE_FAILED = 'PINNED_VIEWS_USER_UPDATE_FAILED';
export var PINNED_VIEWS_USER_UPDATE_SUCCEEDED = 'PINNED_VIEWS_USER_UPDATE_SUCCEEDED';
export var PINNED_VIEWS_USER_UPDATE_SETTLED = 'PINNED_VIEWS_USER_UPDATE_SETTLED';
export var PINNED_VIEWS_FETCH_STARTED = 'PINNED_VIEWS_FETCH_STARTED';
export var PINNED_VIEWS_FETCH_SUCCEEDED = 'PINNED_VIEWS_FETCH_SUCCEEDED';
export var PINNED_VIEWS_FETCH_FAILED = 'PINNED_VIEWS_FETCH_FAILED';