'use es6';

export var PROPERTIES_FETCH_STARTED = 'PROPERTIES_FETCH_STARTED';
export var PROPERTIES_FETCH_SUCCEEDED = 'PROPERTIES_FETCH_SUCCEEDED';
export var PROPERTIES_FETCH_FAILED = 'PROPERTIES_FETCH_FAILED';