'use es6';

export var FETCH_AUTOMATION_FLOW_STARTED = 'FETCH_AUTOMATION_FLOW_STARTED';
export var FETCH_AUTOMATION_FLOW_SUCCEEDED = 'FETCH_AUTOMATION_FLOW_SUCCEEDED';
export var FETCH_AUTOMATION_FLOW_FAILED = 'FETCH_AUTOMATION_FLOW_FAILED';