export const subscriptionPlanMap = {
	26: 'Monthly Plan',
	28: 'Monthly Seat',
	32: 'Monthly Seat',
	42: 'Monthly Seat',
	46: 'Essential Seat Monthly',
	54: 'Essential monthly - price test v1',
	62: 'Essential monthly - BR test v1',
	27: 'Annual Plan',
	29: 'Annual Seat',
	33: 'Annual Seat',
	43: 'Annual Seat',
	47: 'Essential Seat Annual',
	55: 'Essential annual - price test v1',
	63: 'Essential annual - BR test v1',
	34: 'Gold Seat Monthly',
	38: 'Gold Seat Monthly',
	48: 'Advanced Seat Monthly',
	56: 'Advanced monthly - price test v1',
	64: 'Advanced monthly - BR test v1',
	35: 'Gold Seat Annual',
	39: 'Gold Seat Annual',
	49: 'Advanced Seat Annual',
	57: 'Advanced annual - price test v1',
	65: 'Advanced annual - BR test v1',
	36: 'Platinum Seat Monthly',
	40: 'Platinum Seat Monthly',
	44: 'Platinum Seat Monthly',
	50: 'Professional Seat Monthly',
	58: 'Professional Seat Monthly - price test v1',
	66: 'Professional Seat Monthly - BR test v1',
	37: 'Platinum Seat Annual',
	41: 'Platinum Seat Annual',
	45: 'Platinum Seat Annual',
	51: 'Professional Seat Annual',
	59: 'Professional Seat Annual - price test v1',
	67: 'Professional Seat Annual - BR test v1',
	52: 'Enterprise Seat Monthly',
	60: 'Enterprise Seat Monthly - price test v1',
	68: 'Enterprise Seat Monthly - BR test v1',
	53: 'Enterprise Seat Annual',
	61: 'Enterprise Seat Annual - price test v1',
	69: 'Enterprise Seat Annual - BR test v1'
};
