'use es6';

export var UPDATE_GLOBAL_COOKIE_OPT_OUT = 'UPDATE_GLOBAL_COOKIE_OPT_OUT';
export var UPDATE_IS_FIRST_VISITOR_SESSION = 'UPDATE_IS_FIRST_VISITOR_SESSION';
export var UPDATE_SHOW_EXIT_INTENT_COOKIE_BANNER = 'UPDATE_SHOW_EXIT_INTENT_COOKIE_BANNER';