import * as React from "react";
import { Select } from "../select";
import { en, fr } from "./translations";
export class StateSelector extends React.Component {
    render() {
        const messages = this.props.locale === "en-CA" ? en : fr;
        if (this.props.locale === "fr-CA") {
            return (React.createElement(Select, Object.assign({}, this.props),
                React.createElement("option", { value: "" }, messages.stateOptionPrompt),
                React.createElement("option", { value: "AK" }, messages.stateOptionAlaska),
                React.createElement("option", { value: "AL" }, messages.stateOptionAlabama),
                React.createElement("option", { value: "AZ" }, messages.stateOptionArizona),
                React.createElement("option", { value: "CA" }, messages.stateOptionCalifornia),
                React.createElement("option", { value: "NC" }, messages.stateOptionNorthCarolina),
                React.createElement("option", { value: "SC" }, messages.stateOptionSouthCarolina),
                React.createElement("option", { value: "CO" }, messages.stateOptionColorado),
                React.createElement("option", { value: "CT" }, messages.stateOptionConnecticut),
                React.createElement("option", { value: "ND" }, messages.stateOptionNorthDakota),
                React.createElement("option", { value: "DC" }, messages.stateOptionDistrictOfColumbia),
                React.createElement("option", { value: "DE" }, messages.stateOptionDelaware),
                React.createElement("option", { value: "FL" }, messages.stateOptionFlorida),
                React.createElement("option", { value: "GA" }, messages.stateOptionGeorgia),
                React.createElement("option", { value: "HI" }, messages.stateOptionHawaii),
                React.createElement("option", { value: "ID" }, messages.stateOptionIdaho),
                React.createElement("option", { value: "IL" }, messages.stateOptionIllinois),
                React.createElement("option", { value: "IN" }, messages.stateOptionIndiana),
                React.createElement("option", { value: "IA" }, messages.stateOptionIowa),
                React.createElement("option", { value: "KS" }, messages.stateOptionKansas),
                React.createElement("option", { value: "KY" }, messages.stateOptionKentucky),
                React.createElement("option", { value: "LA" }, messages.stateOptionLouisiana),
                React.createElement("option", { value: "ME" }, messages.stateOptionMaine),
                React.createElement("option", { value: "MD" }, messages.stateOptionMaryland),
                React.createElement("option", { value: "MA" }, messages.stateOptionMassachusetts),
                React.createElement("option", { value: "MI" }, messages.stateOptionMichigan),
                React.createElement("option", { value: "MN" }, messages.stateOptionMinnesota),
                React.createElement("option", { value: "MS" }, messages.stateOptionMississippi),
                React.createElement("option", { value: "MO" }, messages.stateOptionMissouri),
                React.createElement("option", { value: "MT" }, messages.stateOptionMontana),
                React.createElement("option", { value: "NE" }, messages.stateOptionNebraska),
                React.createElement("option", { value: "NV" }, messages.stateOptionNevada),
                React.createElement("option", { value: "NH" }, messages.stateOptionNewHampshire),
                React.createElement("option", { value: "NJ" }, messages.stateOptionNewJersey),
                React.createElement("option", { value: "NY" }, messages.stateOptionNewYork),
                React.createElement("option", { value: "NM" }, messages.stateOptionNewMexico),
                React.createElement("option", { value: "OH" }, messages.stateOptionOhio),
                React.createElement("option", { value: "OK" }, messages.stateOptionOklahoma),
                React.createElement("option", { value: "OR" }, messages.stateOptionOregon),
                React.createElement("option", { value: "PA" }, messages.stateOptionPennsylvania),
                React.createElement("option", { value: "RI" }, messages.stateOptionRhodeIsland),
                React.createElement("option", { value: "TN" }, messages.stateOptionTennessee),
                React.createElement("option", { value: "TX" }, messages.stateOptionTexas),
                React.createElement("option", { value: "UT" }, messages.stateOptionUtah),
                React.createElement("option", { value: "VT" }, messages.stateOptionVermont),
                React.createElement("option", { value: "VA" }, messages.stateOptionVirginia),
                React.createElement("option", { value: "WV" }, messages.stateOptionWestVirginia),
                React.createElement("option", { value: "WA" }, messages.stateOptionWashington),
                React.createElement("option", { value: "WI" }, messages.stateOptionWisconsin),
                React.createElement("option", { value: "WY" }, messages.stateOptionWyoming)));
        }
        else {
            return (React.createElement(Select, Object.assign({}, this.props),
                React.createElement("option", { value: "" }, messages.stateOptionPrompt),
                React.createElement("option", { value: "AK" }, messages.stateOptionAlaska),
                React.createElement("option", { value: "AL" }, messages.stateOptionAlabama),
                React.createElement("option", { value: "AZ" }, messages.stateOptionArizona),
                React.createElement("option", { value: "CA" }, messages.stateOptionCalifornia),
                React.createElement("option", { value: "CO" }, messages.stateOptionColorado),
                React.createElement("option", { value: "CT" }, messages.stateOptionConnecticut),
                React.createElement("option", { value: "DC" }, messages.stateOptionDistrictOfColumbia),
                React.createElement("option", { value: "DE" }, messages.stateOptionDelaware),
                React.createElement("option", { value: "FL" }, messages.stateOptionFlorida),
                React.createElement("option", { value: "GA" }, messages.stateOptionGeorgia),
                React.createElement("option", { value: "HI" }, messages.stateOptionHawaii),
                React.createElement("option", { value: "IA" }, messages.stateOptionIowa),
                React.createElement("option", { value: "ID" }, messages.stateOptionIdaho),
                React.createElement("option", { value: "IL" }, messages.stateOptionIllinois),
                React.createElement("option", { value: "IN" }, messages.stateOptionIndiana),
                React.createElement("option", { value: "KS" }, messages.stateOptionKansas),
                React.createElement("option", { value: "KY" }, messages.stateOptionKentucky),
                React.createElement("option", { value: "LA" }, messages.stateOptionLouisiana),
                React.createElement("option", { value: "MA" }, messages.stateOptionMassachusetts),
                React.createElement("option", { value: "MD" }, messages.stateOptionMaryland),
                React.createElement("option", { value: "ME" }, messages.stateOptionMaine),
                React.createElement("option", { value: "MI" }, messages.stateOptionMichigan),
                React.createElement("option", { value: "MN" }, messages.stateOptionMinnesota),
                React.createElement("option", { value: "MO" }, messages.stateOptionMissouri),
                React.createElement("option", { value: "MS" }, messages.stateOptionMississippi),
                React.createElement("option", { value: "MT" }, messages.stateOptionMontana),
                React.createElement("option", { value: "NC" }, messages.stateOptionNorthCarolina),
                React.createElement("option", { value: "ND" }, messages.stateOptionNorthDakota),
                React.createElement("option", { value: "NE" }, messages.stateOptionNebraska),
                React.createElement("option", { value: "NH" }, messages.stateOptionNewHampshire),
                React.createElement("option", { value: "NJ" }, messages.stateOptionNewJersey),
                React.createElement("option", { value: "NM" }, messages.stateOptionNewMexico),
                React.createElement("option", { value: "NV" }, messages.stateOptionNevada),
                React.createElement("option", { value: "NY" }, messages.stateOptionNewYork),
                React.createElement("option", { value: "OH" }, messages.stateOptionOhio),
                React.createElement("option", { value: "OK" }, messages.stateOptionOklahoma),
                React.createElement("option", { value: "OR" }, messages.stateOptionOregon),
                React.createElement("option", { value: "PA" }, messages.stateOptionPennsylvania),
                React.createElement("option", { value: "RI" }, messages.stateOptionRhodeIsland),
                React.createElement("option", { value: "SC" }, messages.stateOptionSouthCarolina),
                React.createElement("option", { value: "TN" }, messages.stateOptionTennessee),
                React.createElement("option", { value: "TX" }, messages.stateOptionTexas),
                React.createElement("option", { value: "UT" }, messages.stateOptionUtah),
                React.createElement("option", { value: "VA" }, messages.stateOptionVirginia),
                React.createElement("option", { value: "VT" }, messages.stateOptionVermont),
                React.createElement("option", { value: "WA" }, messages.stateOptionWashington),
                React.createElement("option", { value: "WI" }, messages.stateOptionWisconsin),
                React.createElement("option", { value: "WV" }, messages.stateOptionWestVirginia),
                React.createElement("option", { value: "WY" }, messages.stateOptionWyoming)));
        }
    }
}
export default StateSelector;
//# sourceMappingURL=StateSelector.js.map