export const KEYWORD_GENERATOR_TOOL_SET_SEED_KEYWORD = "KEYWORD_GENERATOR_TOOL_SET_SEED_KEYWORD";
export const KEYWORD_GENERATOR_TOOL_SET_COUNTRY = "KEYWORD_GENERATOR_TOOL_SET_COUNTRY";
export const KEYWORD_GENERATOR_TOOL_SET_DURATION = "KEYWORD_GENERATOR_TOOL_SET_DURATION";
export const KEYWORD_GENERATOR_TOOL_SET_WEBSOURCE = "KEYWORD_GENERATOR_TOOL_SET_WEBSOURCE";
export const KEYWORD_GENERATOR_TOOL_CLEAR_ALL_PARAMS = "KEYWORD_GENERATOR_TOOL_CLEAR_ALL_PARAMS";
export const KEYWORD_GENERATOR_TOOL_SUGGESTION_PARAMS = "KEYWORD_GENERATOR_TOOL_SUGGESTION_PARAMS";
export const KEYWORD_GENERATOR_TOOL_SET_RESULTS_TABLE_VIEW =
    "KEYWORD_GENERATOR_TOOL_SET_RESULTS_TABLE_VIEW";
export const KEYWORD_GENERATOR_TOOL_SET_BOOLEAN_SEARCH_TERM =
    "KEYWORD_GENERATOR_TOOL_SET_BOOLEAN_SEARCH_TERM";
export const KEYWORD_GENERATOR_TOOL_SET_IS_GROUP_CONTEXT =
    "KEYWORD_GENERATOR_TOOL_SET_IS_GROUP_CONTEXT";
