export const MARKETING_WORKSPACE_ARENA_SET_SELECTED_TAB =
    "MARKETING_WORKSPACE_ARENA_SET_SELECTED_TAB";
export const MARKETING_WORKSPACE_SET_COUNTRY = "MARKETING_WORKSPACE_SET_COUNTRY";
export const MARKETING_WORKSPACE_SET_DURATION = "MARKETING_WORKSPACE_SET_DURATION";
export const MARKETING_WORKSPACE_SET_WEBSOURCE = "MARKETING_WORKSPACE_SET_WEBSOURCE";
export const MARKETING_WORKSPACE_SET_IS_WWW = "MARKETING_WORKSPACE_SET_IS_WWW";
export const MARKETING_WORKSPACE_SET_SITES = "MARKETING_WORKSPACE_SET_SITES";
export const MARKETING_WORKSPACE_SET_KEYWORDS_TYPE = "MARKETING_WORKSPACE_SET_KEYWORDS_TYPE";
export const MARKETING_WORKSPACE_SET_FILTERS = "MARKETING_WORKSPACE_SET_FILTERS";
export const MARKETING_WORKSPACE_SET_ALL_PARAMS = "MARKETING_WORKSPACE_SET_ALL_PARAMS";
export const MARKETING_WORKSPACE_SET_SELECTED_WORKSPACE =
    "MARKETING_WORKSPACE_SET_SELECTED_WORKSPACE";
export const MARKETING_WORKSPACE_SET_CATEGORY = "MARKETING_WORKSPACE_SET_CATEGORY";
export const MARKETING_WORKSPACE_SET_RECOMMENDATION_ENGINE_START =
    "MARKETING_WORKSPACE_SET_RECOMMENDATION_ENGINE_START";
export const MARKETING_WORKSPACE_SET_RECOMMENDATION_ENGINE_SUCCESS =
    "MARKETING_WORKSPACE_SET_RECOMMENDATION_ENGINE_SUCCESS";
export const MARKETING_WORKSPACE_SET_RECOMMENDATION_ENGINE_FAILED =
    "MARKETING_WORKSPACE_SET_RECOMMENDATION_ENGINE_FAILED";
export const MARKETING_WORKSPACE_SET_RECOMMENDATION_ENGINE_CLEAR =
    "MARKETING_WORKSPACE_SET_RECOMMENDATION_ENGINE_CLEAR";
export const MARKETING_WORKSPACE_UNSET_NEWLY_CREATED = "MARKETING_WORKSPACE_UNSET_NEWLY_CREATED";
export const MARKETING_WORKSPACE_CLEAR_ALL_PARAMS = "MARKETING_WORKSPACE_CLEAR_ALL_PARAMS";
export const MARKETING_WORKSPACE_SET_SELECTED_WORKSPACE_KEYWORD_GROUPS =
    "MARKETING_WORKSPACE_SET_SELECTED_WORKSPACE_KEYWORD_GROUPS";
export const MARKETING_WORKSPACE_UPDATE_SELECTED_WORKSPACE_KEYWORD_GROUP =
    "MARKETING_WORKSPACE_UPDATE_SELECTED_WORKSPACE_KEYWORD_GROUP";
