'use es6';

export var VIEW_COUNTS_FETCH_STARTED = 'VIEW_COUNTS_FETCH_STARTED';
export var VIEW_COUNTS_FETCH_SUCCEEDED = 'VIEW_COUNTS_FETCH_SUCCEEDED';
export var VIEW_COUNTS_FETCH_FAILED = 'VIEW_COUNTS_FETCH_FAILED';