'use es6';

export var STAGE_MESSAGE_ON_STUBBED_THREAD = 'STAGE_MESSAGE_ON_STUBBED_THREAD';
export var ADD_VISITOR_MESSAGE_TO_STUBBED_THREAD = 'ADD_VISITOR_MESSAGE_TO_STUBBED_THREAD';
export var RESET_STUBBED_THREAD = 'RESET_STUBBED_THREAD';