import { IndexCell } from "components/React/Table/cells/IndexCell";
import { ChangePercentage } from "components/React/Table/cells/ChangePercentage";
import {
    DefaultCellRightAlign,
    LinkCell,
    TrafficShare,
    WebsiteTooltipTopCell,
} from "components/React/Table/cells";
import { DefaultCellHeaderRightAlign } from "components/React/Table/headerCells/DefaultCellHeaderRightAlign";
import { DefaultCenteredCellHeader } from "components/React/Table/headerCells/DefaultCenteredCellHeader";
import selectionColumn from "../../TableSelection/selection-column";

// Attention, necessary fields are:
// cellComponent, visible, sortable, field and sortDirection

export const mobileTraffic = [
    selectionColumn,
    {
        field: "",
        cellComponent: IndexCell,
        fixed: true,
        cellTemp: "index",
        sortDirection: "desc",
        headerComponent: DefaultCenteredCellHeader,
        sortable: false,
        width: 65,
        visible: true,
        disableHeaderCellHover: true,
    },
    {
        name: "Domain",
        field: "Domain",
        fixed: true,
        title: "Domain",
        displayName: "Domain",
        visible: true,
        type: "string",
        format: "None",
        sortable: true,
        isSorted: false,
        sortDirection: "desc",
        cellComponent: WebsiteTooltipTopCell,
        groupable: true,
        showTotalCount: true,
        width: 220,
    },
    {
        name: "Share",
        field: "Share",
        title: "Traffic Share",
        displayName: "Traffic Share",
        type: "string",
        format: "percentagesign",
        sortable: true,
        isSorted: true,
        sortDirection: "desc",
        cellComponent: TrafficShare,
        groupable: false,
        cellTemp: "traffic-share",
        headTemp: "",
        totalCount: false,
        visible: true,
        width: 200,
    },
    {
        name: "Change",
        field: "Change",
        title: "Change",
        displayName: "Change",
        type: "double",
        format: "percentagesign",
        cellComponent: ChangePercentage,
        sortable: true,
        isSorted: false,
        sortDirection: "desc",
        groupable: false,
        cellTemp: "change-percentage",
        headerComponent: DefaultCellHeaderRightAlign,
        visible: true,
        totalCount: false,
        width: 110,
    },
    {
        name: "Position",
        field: "Position",
        displayName: "Position",
        title: "Position",
        type: "int",
        format: "None",
        sortable: true,
        isSorted: false,
        sortDirection: "asc",
        groupable: false,
        cellTemp: "keyword-analysis-position",
        cellComponent: DefaultCellRightAlign,
        headerComponent: DefaultCellHeaderRightAlign,
        totalCount: false,
        visible: true,
        width: 80,
    },
    {
        name: "Url",
        field: "Url",
        title: "Destination URL",
        displayName: "Destination URL",
        type: "string",
        format: "None",
        sortable: true,
        isSorted: false,
        sortDirection: "desc",
        groupable: false,
        cellTemp: "keyword-analysis-url",
        cellCls: "url-cell",
        cellClass: "url-cell",
        cellComponent: LinkCell,
        headTemp: "",
        totalCount: false,
        visible: true,
        width: 275,
    },
    {
        name: "Category",
        field: "Category",
        displayName: "Website Category",
        title: "Category",
        type: "string",
        format: "prettifyCategory",
        sortable: true,
        isSorted: false,
        sortDirection: "desc",
        groupable: false,
        cellTemp: "default-cell",
        headTemp: "",
        totalCount: false,
        visible: true,
        width: 220,
    },
    {
        name: `Serp`,
        field: `Serp`,
        displayName: `Serp`,
        trackingName: `Serp`,
        sortDirection: "desc",
        title: "analysis.source.search.all.table.columns.featured.title",
        tooltip: "analysis.source.search.all.table.columns.featured.title.tooltip",
        cellTemp: "adsense-cell",
        sortable: true,
        visible: true,
        width: 95,
    },
];
// TODO fix values
export const mobileTrafficMetaData = {
    tableApi: `/widgetApi/KeywordAnalysisOP/KeywordAnalysisOrganic/Table`,
    excelApi: `/widgetApi/KeywordAnalysisOP/KeywordAnalysisOrganic/Excel`,
};

export const mobileTrafficFilters = {
    showWebsiteFilter: false,
    showCategoryFilter: false,
    showSearchTypeFilter: false,
};
