'use es6';

export var POSTS_FETCH_BEGAN = 'POSTS_FETCH_BEGAN';
export var POSTS_FETCH_ERROR = 'POSTS_FETCH_ERROR';
export var POSTS_FETCH_SUCCESS = 'POSTS_FETCH_SUCCESS';
export var POSTS_UPDATE_CAMPAIGN_BEGAN = 'POSTS_UPDATE_CAMPAIGN_BEGAN';
export var POSTS_UPDATE_CAMPAIGN_ERROR = 'POSTS_UPDATE_CAMPAIGN_ERROR';
export var POSTS_UPDATE_CAMPAIGN_SUCCESS = 'POSTS_UPDATE_CAMPAIGN_SUCCESS';
export var POST_BULK_CLONE_BEGAN = 'POST_BULK_CLONE_BEGAN';
export var POST_BULK_CLONE_ERROR = 'POST_BULK_CLONE_ERROR';
export var POST_BULK_CLONE_SUCCESS = 'POST_BULK_CLONE_SUCCESS';
export var POST_DELETE_BEGAN = 'POST_DELETE_BEGAN';
export var POST_DELETE_ERROR = 'POST_DELETE_ERROR';
export var POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';