var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from 'styled-components';
import { color, typography } from '../../themes/utils';
import { AuthFormStyle } from './auth-form.style';
export var LoginFormStyle = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    ", "\n\n    .submit-btn {\n        margin-top: 24px;\n    }\n\n    .forgot-password {\n        margin: 16px 0;\n    }\n\n    .forgot-pass-text {\n        ", "\n        text-decoration: none;\n        font-weight: bold;\n        font-size: 15px;\n        color: ", ";\n\n        &:hover {\n            text-decoration: underline;\n        }\n    }\n\n    .remember-me {\n        margin-top: 16px;\n    }\n\n    input[type='checkbox'] {\n        margin-right: 6px;\n    }\n\n    .remember-me-label {\n        ", "\n        font-size: 13px;\n    }\n\n    .login-inputs-fields {\n        margin-bottom: 10px;\n\n        &.bold {\n            font-weight: bold;\n        }\n    }\n\n    .sign-up {\n        text-align: center;\n        ", "\n        margin-top: 34px;\n        a {\n            ", "\n            font-size: 15px;\n            font-weight: bold;\n            text-decoration: none;\n            cursor: pointer;\n            color: ", ";\n        }\n\n        a:hover {\n            text-decoration: underline;\n        }\n    }\n"], ["\n    ", "\n\n    .submit-btn {\n        margin-top: 24px;\n    }\n\n    .forgot-password {\n        margin: 16px 0;\n    }\n\n    .forgot-pass-text {\n        ", "\n        text-decoration: none;\n        font-weight: bold;\n        font-size: 15px;\n        color: ", ";\n\n        &:hover {\n            text-decoration: underline;\n        }\n    }\n\n    .remember-me {\n        margin-top: 16px;\n    }\n\n    input[type='checkbox'] {\n        margin-right: 6px;\n    }\n\n    .remember-me-label {\n        ", "\n        font-size: 13px;\n    }\n\n    .login-inputs-fields {\n        margin-bottom: 10px;\n\n        &.bold {\n            font-weight: bold;\n        }\n    }\n\n    .sign-up {\n        text-align: center;\n        ", "\n        margin-top: 34px;\n        a {\n            ", "\n            font-size: 15px;\n            font-weight: bold;\n            text-decoration: none;\n            cursor: pointer;\n            color: ", ";\n        }\n\n        a:hover {\n            text-decoration: underline;\n        }\n    }\n"])), AuthFormStyle, typography(function (t) { return t.links.nav.small; }), color(function (c) { return c.violet; }), typography(function (t) { return t.normal; }), typography(function (t) { return t.normal; }), typography(function (t) { return t.links.nav.small; }), color(function (c) { return c.violet; }));
var templateObject_1;
//# sourceMappingURL=login-form-style.js.map