// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type AddEventToMyCalendarRequest from '../contract/AddEventToMyCalendarRequest';

export default function addEventToMyCalendarRequest(
    data: AddEventToMyCalendarRequest
): AddEventToMyCalendarRequest {
    let result: AddEventToMyCalendarRequest = {
        __type: 'AddEventToMyCalendarRequest:#Exchange',
        ...data,
    };

    return result;
}
