// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type AddEntityFeedbackRequest from '../contract/AddEntityFeedbackRequest';

export default function addEntityFeedbackRequest(
    data: AddEntityFeedbackRequest
): AddEntityFeedbackRequest {
    let result: AddEntityFeedbackRequest = {
        __type: 'AddEntityFeedbackRequest:#Exchange',
        ...data,
    };

    return result;
}
