// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type AddEntityFeedbackJsonRequest from '../contract/AddEntityFeedbackJsonRequest';

export default function addEntityFeedbackJsonRequest(
    data: AddEntityFeedbackJsonRequest
): AddEntityFeedbackJsonRequest {
    let result: AddEntityFeedbackJsonRequest = {
        __type: 'AddEntityFeedbackJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
