// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type ApplyCategoryOperationRequest from '../contract/ApplyCategoryOperationRequest';

export default function applyCategoryOperationRequest(
    data: ApplyCategoryOperationRequest
): ApplyCategoryOperationRequest {
    let result: ApplyCategoryOperationRequest = {
        __type: 'ApplyCategoryOperationRequest:#Exchange',
        ...data,
    };

    return result;
}
