// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type AttachmentType from '../contract/AttachmentType';

export default function attachmentType(data: AttachmentType): AttachmentType {
    let result: AttachmentType = {
        __type: 'AttachmentType:#Exchange',
        ...data,
    };

    return result;
}
