// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type BodyContentType from '../contract/BodyContentType';

export default function bodyContentType(data: BodyContentType): BodyContentType {
    let result: BodyContentType = {
        __type: 'BodyContentType:#Exchange',
        ...data,
    };

    return result;
}
