// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type CancelDeferredSendRequest from '../contract/CancelDeferredSendRequest';

export default function cancelDeferredSendRequest(
    data: CancelDeferredSendRequest
): CancelDeferredSendRequest {
    let result: CancelDeferredSendRequest = {
        __type: 'CancelDeferredSendRequest:#Exchange',
        ...data,
    };

    return result;
}
