// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type CancelConvertLocalToRefAttachmentRequest from '../contract/CancelConvertLocalToRefAttachmentRequest';

export default function cancelConvertLocalToRefAttachmentRequest(
    data: CancelConvertLocalToRefAttachmentRequest
): CancelConvertLocalToRefAttachmentRequest {
    let result: CancelConvertLocalToRefAttachmentRequest = {
        __type: 'CancelConvertLocalToRefAttachmentRequest:#Exchange',
        ...data,
    };

    return result;
}
