// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type CancelCalendarEventRequest from '../contract/CancelCalendarEventRequest';

export default function cancelCalendarEventRequest(
    data: CancelCalendarEventRequest
): CancelCalendarEventRequest {
    let result: CancelCalendarEventRequest = {
        __type: 'CancelCalendarEventRequest:#Exchange',
        ...data,
    };

    return result;
}
