// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type ChannelRoundTripNotificationRequest from '../contract/ChannelRoundTripNotificationRequest';

export default function channelRoundTripNotificationRequest(
    data: ChannelRoundTripNotificationRequest
): ChannelRoundTripNotificationRequest {
    let result: ChannelRoundTripNotificationRequest = {
        __type: 'ChannelRoundTripNotificationRequest:#Exchange',
        ...data,
    };

    return result;
}
