// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type ContextProperty from '../contract/ContextProperty';

export default function contextProperty(data: ContextProperty): ContextProperty {
    let result: ContextProperty = {
        __type: 'ContextProperty:#Exchange',
        ...data,
    };

    return result;
}
