// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type ConvertLocalToRefAttachmentRequest from '../contract/ConvertLocalToRefAttachmentRequest';

export default function convertLocalToRefAttachmentRequest(
    data: ConvertLocalToRefAttachmentRequest
): ConvertLocalToRefAttachmentRequest {
    let result: ConvertLocalToRefAttachmentRequest = {
        __type: 'ConvertLocalToRefAttachmentRequest:#Exchange',
        ...data,
    };

    return result;
}
