// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type ConversationRequestType from '../contract/ConversationRequestType';

export default function conversationRequestType(
    data: ConversationRequestType
): ConversationRequestType {
    let result: ConversationRequestType = {
        __type: 'ConversationRequestType:#Exchange',
        ...data,
    };

    return result;
}
