// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type ConvertRefToLocalAttachmentRequest from '../contract/ConvertRefToLocalAttachmentRequest';

export default function convertRefToLocalAttachmentRequest(
    data: ConvertRefToLocalAttachmentRequest
): ConvertRefToLocalAttachmentRequest {
    let result: ConvertRefToLocalAttachmentRequest = {
        __type: 'ConvertRefToLocalAttachmentRequest:#Exchange',
        ...data,
    };

    return result;
}
