// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type CreateResponseFromModernGroupJsonRequest from '../contract/CreateResponseFromModernGroupJsonRequest';

export default function createResponseFromModernGroupJsonRequest(
    data: CreateResponseFromModernGroupJsonRequest
): CreateResponseFromModernGroupJsonRequest {
    let result: CreateResponseFromModernGroupJsonRequest = {
        __type: 'CreateResponseFromModernGroupJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
