// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type CreateItemJsonRequest from '../contract/CreateItemJsonRequest';

export default function createItemJsonRequest(data: CreateItemJsonRequest): CreateItemJsonRequest {
    let result: CreateItemJsonRequest = {
        __type: 'CreateItemJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
