// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type CreateFolderRequest from '../contract/CreateFolderRequest';

export default function createFolderRequest(data: CreateFolderRequest): CreateFolderRequest {
    let result: CreateFolderRequest = {
        __type: 'CreateFolderRequest:#Exchange',
        ...data,
    };

    return result;
}
