// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type CreateFolderJsonRequest from '../contract/CreateFolderJsonRequest';

export default function createFolderJsonRequest(
    data: CreateFolderJsonRequest
): CreateFolderJsonRequest {
    let result: CreateFolderJsonRequest = {
        __type: 'CreateFolderJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
