// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type CreatePersonaRequest from '../contract/CreatePersonaRequest';

export default function createPersonaRequest(data: CreatePersonaRequest): CreatePersonaRequest {
    let result: CreatePersonaRequest = {
        __type: 'CreatePersonaRequest:#Exchange',
        ...data,
    };

    return result;
}
