// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type CreateResponseFromModernGroupRequest from '../contract/CreateResponseFromModernGroupRequest';

export default function createResponseFromModernGroupRequest(
    data: CreateResponseFromModernGroupRequest
): CreateResponseFromModernGroupRequest {
    let result: CreateResponseFromModernGroupRequest = {
        __type: 'CreateResponseFromModernGroupRequest:#Exchange',
        ...data,
    };

    return result;
}
