// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type DeleteCalendarEventJsonRequest from '../contract/DeleteCalendarEventJsonRequest';

export default function deleteCalendarEventJsonRequest(
    data: DeleteCalendarEventJsonRequest
): DeleteCalendarEventJsonRequest {
    let result: DeleteCalendarEventJsonRequest = {
        __type: 'DeleteCalendarEventJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
