// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type DeleteItemField from '../contract/DeleteItemField';

export default function deleteItemField(data: DeleteItemField): DeleteItemField {
    let result: DeleteItemField = {
        __type: 'DeleteItemField:#Exchange',
        ...data,
    };

    return result;
}
