// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type DeleteFolderJsonRequest from '../contract/DeleteFolderJsonRequest';

export default function deleteFolderJsonRequest(
    data: DeleteFolderJsonRequest
): DeleteFolderJsonRequest {
    let result: DeleteFolderJsonRequest = {
        __type: 'DeleteFolderJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
