// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type DeleteFolderRequest from '../contract/DeleteFolderRequest';

export default function deleteFolderRequest(data: DeleteFolderRequest): DeleteFolderRequest {
    let result: DeleteFolderRequest = {
        __type: 'DeleteFolderRequest:#Exchange',
        ...data,
    };

    return result;
}
