// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type DeleteItemJsonRequest from '../contract/DeleteItemJsonRequest';

export default function deleteItemJsonRequest(data: DeleteItemJsonRequest): DeleteItemJsonRequest {
    let result: DeleteItemJsonRequest = {
        __type: 'DeleteItemJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
