// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type DismissUserUnifiedGroupSuggestionRequest from '../contract/DismissUserUnifiedGroupSuggestionRequest';

export default function dismissUserUnifiedGroupSuggestionRequest(
    data: DismissUserUnifiedGroupSuggestionRequest
): DismissUserUnifiedGroupSuggestionRequest {
    let result: DismissUserUnifiedGroupSuggestionRequest = {
        __type: 'DismissUserUnifiedGroupSuggestionRequest:#Exchange',
        ...data,
    };

    return result;
}
