// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type DismissUserUnifiedGroupSuggestionJsonRequest from '../contract/DismissUserUnifiedGroupSuggestionJsonRequest';

export default function dismissUserUnifiedGroupSuggestionJsonRequest(
    data: DismissUserUnifiedGroupSuggestionJsonRequest
): DismissUserUnifiedGroupSuggestionJsonRequest {
    let result: DismissUserUnifiedGroupSuggestionJsonRequest = {
        __type: 'DismissUserUnifiedGroupSuggestionJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
