// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type Duration from '../contract/Duration';

export default function duration(data: Duration): Duration {
    let result: Duration = {
        __type: 'Duration:#Exchange',
        ...data,
    };

    return result;
}
