// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type DynamicRefinerQueryType from '../contract/DynamicRefinerQueryType';

export default function dynamicRefinerQueryType(
    data: DynamicRefinerQueryType
): DynamicRefinerQueryType {
    let result: DynamicRefinerQueryType = {
        __type: 'DynamicRefinerQueryType:#Exchange',
        ...data,
    };

    return result;
}
