// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type EndSearchSessionJsonRequest from '../contract/EndSearchSessionJsonRequest';

export default function endSearchSessionJsonRequest(
    data: EndSearchSessionJsonRequest
): EndSearchSessionJsonRequest {
    let result: EndSearchSessionJsonRequest = {
        __type: 'EndSearchSessionJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
