// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type EndSearchSessionRequest from '../contract/EndSearchSessionRequest';

export default function endSearchSessionRequest(
    data: EndSearchSessionRequest
): EndSearchSessionRequest {
    let result: EndSearchSessionRequest = {
        __type: 'EndSearchSessionRequest:#Exchange',
        ...data,
    };

    return result;
}
