// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type ExecuteSearchJsonRequest from '../contract/ExecuteSearchJsonRequest';

export default function executeSearchJsonRequest(
    data: ExecuteSearchJsonRequest
): ExecuteSearchJsonRequest {
    let result: ExecuteSearchJsonRequest = {
        __type: 'ExecuteSearchJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
