// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type ExecuteSearchRequest from '../contract/ExecuteSearchRequest';

export default function executeSearchRequest(data: ExecuteSearchRequest): ExecuteSearchRequest {
    let result: ExecuteSearchRequest = {
        __type: 'ExecuteSearchRequest:#Exchange',
        ...data,
    };

    return result;
}
