// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type ExpandCalendarEventJsonRequest from '../contract/ExpandCalendarEventJsonRequest';

export default function expandCalendarEventJsonRequest(
    data: ExpandCalendarEventJsonRequest
): ExpandCalendarEventJsonRequest {
    let result: ExpandCalendarEventJsonRequest = {
        __type: 'ExpandCalendarEventJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
