// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type ExtendedPropertyType from '../contract/ExtendedPropertyType';

export default function extendedPropertyType(data: ExtendedPropertyType): ExtendedPropertyType {
    let result: ExtendedPropertyType = {
        __type: 'ExtendedPropertyType:#Exchange',
        ...data,
    };

    return result;
}
