// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type FetchDataProviderResourceRequest from '../contract/FetchDataProviderResourceRequest';

export default function fetchDataProviderResourceRequest(
    data: FetchDataProviderResourceRequest
): FetchDataProviderResourceRequest {
    let result: FetchDataProviderResourceRequest = {
        __type: 'FetchDataProviderResourceRequest:#Exchange',
        ...data,
    };

    return result;
}
