// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type FindUnifiedGroupsRequest from '../contract/FindUnifiedGroupsRequest';

export default function findUnifiedGroupsRequest(
    data: FindUnifiedGroupsRequest
): FindUnifiedGroupsRequest {
    let result: FindUnifiedGroupsRequest = {
        __type: 'FindUnifiedGroupsRequest:#Exchange',
        ...data,
    };

    return result;
}
