// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type FindConversationJsonRequest from '../contract/FindConversationJsonRequest';

export default function findConversationJsonRequest(
    data: FindConversationJsonRequest
): FindConversationJsonRequest {
    let result: FindConversationJsonRequest = {
        __type: 'FindConversationJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
