// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type FindCategoryDetailsJsonRequest from '../contract/FindCategoryDetailsJsonRequest';

export default function findCategoryDetailsJsonRequest(
    data: FindCategoryDetailsJsonRequest
): FindCategoryDetailsJsonRequest {
    let result: FindCategoryDetailsJsonRequest = {
        __type: 'FindCategoryDetailsJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
