// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type FindCategoryDetailsRequest from '../contract/FindCategoryDetailsRequest';

export default function findCategoryDetailsRequest(
    data: FindCategoryDetailsRequest
): FindCategoryDetailsRequest {
    let result: FindCategoryDetailsRequest = {
        __type: 'FindCategoryDetailsRequest:#Exchange',
        ...data,
    };

    return result;
}
