// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type FindItemRequest from '../contract/FindItemRequest';

export default function findItemRequest(data: FindItemRequest): FindItemRequest {
    let result: FindItemRequest = {
        __type: 'FindItemRequest:#Exchange',
        ...data,
    };

    return result;
}
