// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type FindPeopleJsonRequest from '../contract/FindPeopleJsonRequest';

export default function findPeopleJsonRequest(data: FindPeopleJsonRequest): FindPeopleJsonRequest {
    let result: FindPeopleJsonRequest = {
        __type: 'FindPeopleJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
