// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type FindUnifiedGroupsJsonRequest from '../contract/FindUnifiedGroupsJsonRequest';

export default function findUnifiedGroupsJsonRequest(
    data: FindUnifiedGroupsJsonRequest
): FindUnifiedGroupsJsonRequest {
    let result: FindUnifiedGroupsJsonRequest = {
        __type: 'FindUnifiedGroupsJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
