// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type FindPeopleRequest from '../contract/FindPeopleRequest';

export default function findPeopleRequest(data: FindPeopleRequest): FindPeopleRequest {
    let result: FindPeopleRequest = {
        __type: 'FindPeopleRequest:#Exchange',
        ...data,
    };

    return result;
}
