// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type Folder from '../contract/Folder';

export default function folder(data: Folder): Folder {
    let result: Folder = {
        __type: 'Folder:#Exchange',
        ...data,
    };

    return result;
}
