// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type ForwardItem from '../contract/ForwardItem';

export default function forwardItem(data: ForwardItem): ForwardItem {
    let result: ForwardItem = {
        __type: 'ForwardItem:#Exchange',
        ...data,
    };

    return result;
}
