// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type ForwardCalendarEventJsonRequest from '../contract/ForwardCalendarEventJsonRequest';

export default function forwardCalendarEventJsonRequest(
    data: ForwardCalendarEventJsonRequest
): ForwardCalendarEventJsonRequest {
    let result: ForwardCalendarEventJsonRequest = {
        __type: 'ForwardCalendarEventJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
