// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type FreeBusyViewOptions from '../contract/FreeBusyViewOptions';

export default function freeBusyViewOptions(data: FreeBusyViewOptions): FreeBusyViewOptions {
    let result: FreeBusyViewOptions = {
        __type: 'FreeBusyViewOptions:#Exchange',
        ...data,
    };

    return result;
}
