// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetAllClientExtensionsNotificationsRequest from '../contract/GetAllClientExtensionsNotificationsRequest';

export default function getAllClientExtensionsNotificationsRequest(
    data: GetAllClientExtensionsNotificationsRequest
): GetAllClientExtensionsNotificationsRequest {
    let result: GetAllClientExtensionsNotificationsRequest = {
        __type: 'GetAllClientExtensionsNotificationsRequest:#Exchange',
        ...data,
    };

    return result;
}
