// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetAttachmentDataProviderCreatorRequest from '../contract/GetAttachmentDataProviderCreatorRequest';

export default function getAttachmentDataProviderCreatorRequest(
    data: GetAttachmentDataProviderCreatorRequest
): GetAttachmentDataProviderCreatorRequest {
    let result: GetAttachmentDataProviderCreatorRequest = {
        __type: 'GetAttachmentDataProviderCreatorRequest:#Exchange',
        ...data,
    };

    return result;
}
