// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetAttachmentTextPreviewRequest from '../contract/GetAttachmentTextPreviewRequest';

export default function getAttachmentTextPreviewRequest(
    data: GetAttachmentTextPreviewRequest
): GetAttachmentTextPreviewRequest {
    let result: GetAttachmentTextPreviewRequest = {
        __type: 'GetAttachmentTextPreviewRequest:#Exchange',
        ...data,
    };

    return result;
}
