// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetBirthdayCalendarViewJsonRequest from '../contract/GetBirthdayCalendarViewJsonRequest';

export default function getBirthdayCalendarViewJsonRequest(
    data: GetBirthdayCalendarViewJsonRequest
): GetBirthdayCalendarViewJsonRequest {
    let result: GetBirthdayCalendarViewJsonRequest = {
        __type: 'GetBirthdayCalendarViewJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
