// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetBirthdayEventJsonRequest from '../contract/GetBirthdayEventJsonRequest';

export default function getBirthdayEventJsonRequest(
    data: GetBirthdayEventJsonRequest
): GetBirthdayEventJsonRequest {
    let result: GetBirthdayEventJsonRequest = {
        __type: 'GetBirthdayEventJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
