// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetCalendarEventRequest from '../contract/GetCalendarEventRequest';

export default function getCalendarEventRequest(
    data: GetCalendarEventRequest
): GetCalendarEventRequest {
    let result: GetCalendarEventRequest = {
        __type: 'GetCalendarEventRequest:#Exchange',
        ...data,
    };

    return result;
}
