// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetCalendarViewRequest from '../contract/GetCalendarViewRequest';

export default function getCalendarViewRequest(
    data: GetCalendarViewRequest
): GetCalendarViewRequest {
    let result: GetCalendarViewRequest = {
        __type: 'GetCalendarViewRequest:#Exchange',
        ...data,
    };

    return result;
}
