// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetCalendarEventJsonRequest from '../contract/GetCalendarEventJsonRequest';

export default function getCalendarEventJsonRequest(
    data: GetCalendarEventJsonRequest
): GetCalendarEventJsonRequest {
    let result: GetCalendarEventJsonRequest = {
        __type: 'GetCalendarEventJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
