// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetConversationItemsRequest from '../contract/GetConversationItemsRequest';

export default function getConversationItemsRequest(
    data: GetConversationItemsRequest
): GetConversationItemsRequest {
    let result: GetConversationItemsRequest = {
        __type: 'GetConversationItemsRequest:#Exchange',
        ...data,
    };

    return result;
}
