// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetClientAccessTokenJsonRequest from '../contract/GetClientAccessTokenJsonRequest';

export default function getClientAccessTokenJsonRequest(
    data: GetClientAccessTokenJsonRequest
): GetClientAccessTokenJsonRequest {
    let result: GetClientAccessTokenJsonRequest = {
        __type: 'GetClientAccessTokenJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
