// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetDlpPolicyTipsRequest from '../contract/GetDlpPolicyTipsRequest';

export default function getDlpPolicyTipsRequest(
    data: GetDlpPolicyTipsRequest
): GetDlpPolicyTipsRequest {
    let result: GetDlpPolicyTipsRequest = {
        __type: 'GetDlpPolicyTipsRequest:#Exchange',
        ...data,
    };

    return result;
}
