// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetExtensibilityContextParameters from '../contract/GetExtensibilityContextParameters';

export default function getExtensibilityContextParameters(
    data: GetExtensibilityContextParameters
): GetExtensibilityContextParameters {
    let result: GetExtensibilityContextParameters = {
        __type: 'GetExtensibilityContextParameters:#Exchange',
        ...data,
    };

    return result;
}
