// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetFileItemsRequest from '../contract/GetFileItemsRequest';

export default function getFileItemsRequest(data: GetFileItemsRequest): GetFileItemsRequest {
    let result: GetFileItemsRequest = {
        __type: 'GetFileItemsRequest:#Exchange',
        ...data,
    };

    return result;
}
