// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetNewAttachmentDataProviderCreationInfoRequest from '../contract/GetNewAttachmentDataProviderCreationInfoRequest';

export default function getNewAttachmentDataProviderCreationInfoRequest(
    data: GetNewAttachmentDataProviderCreationInfoRequest
): GetNewAttachmentDataProviderCreationInfoRequest {
    let result: GetNewAttachmentDataProviderCreationInfoRequest = {
        __type: 'GetNewAttachmentDataProviderCreationInfoRequest:#Exchange',
        ...data,
    };

    return result;
}
