// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetPersonaRequest from '../contract/GetPersonaRequest';

export default function getPersonaRequest(data: GetPersonaRequest): GetPersonaRequest {
    let result: GetPersonaRequest = {
        __type: 'GetPersonaRequest:#Exchange',
        ...data,
    };

    return result;
}
