// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetRemindersJsonRequest from '../contract/GetRemindersJsonRequest';

export default function getRemindersJsonRequest(
    data: GetRemindersJsonRequest
): GetRemindersJsonRequest {
    let result: GetRemindersJsonRequest = {
        __type: 'GetRemindersJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
