// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetRemindersRequest from '../contract/GetRemindersRequest';

export default function getRemindersRequest(data: GetRemindersRequest): GetRemindersRequest {
    let result: GetRemindersRequest = {
        __type: 'GetRemindersRequest:#Exchange',
        ...data,
    };

    return result;
}
