// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetSuggestedUnifiedGroupsRequest from '../contract/GetSuggestedUnifiedGroupsRequest';

export default function getSuggestedUnifiedGroupsRequest(
    data: GetSuggestedUnifiedGroupsRequest
): GetSuggestedUnifiedGroupsRequest {
    let result: GetSuggestedUnifiedGroupsRequest = {
        __type: 'GetSuggestedUnifiedGroupsRequest:#Exchange',
        ...data,
    };

    return result;
}
