// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetSearchSuggestionsJsonRequest from '../contract/GetSearchSuggestionsJsonRequest';

export default function getSearchSuggestionsJsonRequest(
    data: GetSearchSuggestionsJsonRequest
): GetSearchSuggestionsJsonRequest {
    let result: GetSearchSuggestionsJsonRequest = {
        __type: 'GetSearchSuggestionsJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
