// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetUnifiedGroupMembersRequest from '../contract/GetUnifiedGroupMembersRequest';

export default function getUnifiedGroupMembersRequest(
    data: GetUnifiedGroupMembersRequest
): GetUnifiedGroupMembersRequest {
    let result: GetUnifiedGroupMembersRequest = {
        __type: 'GetUnifiedGroupMembersRequest:#Exchange',
        ...data,
    };

    return result;
}
