// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetUnifiedGroupMembersJsonRequest from '../contract/GetUnifiedGroupMembersJsonRequest';

export default function getUnifiedGroupMembersJsonRequest(
    data: GetUnifiedGroupMembersJsonRequest
): GetUnifiedGroupMembersJsonRequest {
    let result: GetUnifiedGroupMembersJsonRequest = {
        __type: 'GetUnifiedGroupMembersJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
