// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetUserAvailabilityRequest from '../contract/GetUserAvailabilityRequest';

export default function getUserAvailabilityRequest(
    data: GetUserAvailabilityRequest
): GetUserAvailabilityRequest {
    let result: GetUserAvailabilityRequest = {
        __type: 'GetUserAvailabilityRequest:#Exchange',
        ...data,
    };

    return result;
}
