// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetUnifiedGroupsSettingsJsonRequest from '../contract/GetUnifiedGroupsSettingsJsonRequest';

export default function getUnifiedGroupsSettingsJsonRequest(
    data: GetUnifiedGroupsSettingsJsonRequest
): GetUnifiedGroupsSettingsJsonRequest {
    let result: GetUnifiedGroupsSettingsJsonRequest = {
        __type: 'GetUnifiedGroupsSettingsJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
