// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetUnifiedGroupDetailsJsonRequest from '../contract/GetUnifiedGroupDetailsJsonRequest';

export default function getUnifiedGroupDetailsJsonRequest(
    data: GetUnifiedGroupDetailsJsonRequest
): GetUnifiedGroupDetailsJsonRequest {
    let result: GetUnifiedGroupDetailsJsonRequest = {
        __type: 'GetUnifiedGroupDetailsJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
