// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetUserUnifiedGroupsRequest from '../contract/GetUserUnifiedGroupsRequest';

export default function getUserUnifiedGroupsRequest(
    data: GetUserUnifiedGroupsRequest
): GetUserUnifiedGroupsRequest {
    let result: GetUserUnifiedGroupsRequest = {
        __type: 'GetUserUnifiedGroupsRequest:#Exchange',
        ...data,
    };

    return result;
}
