// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetUserAvailabilityInternalJsonRequest from '../contract/GetUserAvailabilityInternalJsonRequest';

export default function getUserAvailabilityInternalJsonRequest(
    data: GetUserAvailabilityInternalJsonRequest
): GetUserAvailabilityInternalJsonRequest {
    let result: GetUserAvailabilityInternalJsonRequest = {
        __type: 'GetUserAvailabilityInternalJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
