// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetUnifiedGroupDetailsRequest from '../contract/GetUnifiedGroupDetailsRequest';

export default function getUnifiedGroupDetailsRequest(
    data: GetUnifiedGroupDetailsRequest
): GetUnifiedGroupDetailsRequest {
    let result: GetUnifiedGroupDetailsRequest = {
        __type: 'GetUnifiedGroupDetailsRequest:#Exchange',
        ...data,
    };

    return result;
}
