// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetUserUnifiedGroupsJsonRequest from '../contract/GetUserUnifiedGroupsJsonRequest';

export default function getUserUnifiedGroupsJsonRequest(
    data: GetUserUnifiedGroupsJsonRequest
): GetUserUnifiedGroupsJsonRequest {
    let result: GetUserUnifiedGroupsJsonRequest = {
        __type: 'GetUserUnifiedGroupsJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
