// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type GetWacInfoRequest from '../contract/GetWacInfoRequest';

export default function getWacInfoRequest(data: GetWacInfoRequest): GetWacInfoRequest {
    let result: GetWacInfoRequest = {
        __type: 'GetWacInfoRequest:#Exchange',
        ...data,
    };

    return result;
}
