// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type IdentityRequest from '../contract/IdentityRequest';

export default function identityRequest(data: IdentityRequest): IdentityRequest {
    let result: IdentityRequest = {
        __type: 'IdentityRequest:#Exchange',
        ...data,
    };

    return result;
}
