// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type InboxReminderType from '../contract/InboxReminderType';

export default function inboxReminderType(data: InboxReminderType): InboxReminderType {
    let result: InboxReminderType = {
        __type: 'InboxReminderType:#Exchange',
        ...data,
    };

    return result;
}
