// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type IsNotEqualTo from '../contract/IsNotEqualTo';

export default function isNotEqualTo(data: IsNotEqualTo): IsNotEqualTo {
    let result: IsNotEqualTo = {
        __type: 'IsNotEqualTo:#Exchange',
        ...data,
    };

    return result;
}
