// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type Item from '../contract/Item';

export default function item(data: Item): Item {
    let result: Item = {
        __type: 'Item:#Exchange',
        ...data,
    };

    return result;
}
