// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type ItemId from '../contract/ItemId';

export default function itemId(data: ItemId): ItemId {
    let result: ItemId = {
        __type: 'ItemId:#Exchange',
        ...data,
    };

    return result;
}
