// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type ItemChange from '../contract/ItemChange';

export default function itemChange(data: ItemChange): ItemChange {
    let result: ItemChange = {
        __type: 'ItemChange:#Exchange',
        ...data,
    };

    return result;
}
