// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type JoinPrivateUnifiedGroupRequest from '../contract/JoinPrivateUnifiedGroupRequest';

export default function joinPrivateUnifiedGroupRequest(
    data: JoinPrivateUnifiedGroupRequest
): JoinPrivateUnifiedGroupRequest {
    let result: JoinPrivateUnifiedGroupRequest = {
        __type: 'JoinPrivateUnifiedGroupRequest:#Exchange',
        ...data,
    };

    return result;
}
