// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type LoadExtensionCustomPropertiesParameters from '../contract/LoadExtensionCustomPropertiesParameters';

export default function loadExtensionCustomPropertiesParameters(
    data: LoadExtensionCustomPropertiesParameters
): LoadExtensionCustomPropertiesParameters {
    let result: LoadExtensionCustomPropertiesParameters = {
        __type: 'LoadExtensionCustomPropertiesParameters:#Exchange',
        ...data,
    };

    return result;
}
