// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type MailboxData from '../contract/MailboxData';

export default function mailboxData(data: MailboxData): MailboxData {
    let result: MailboxData = {
        __type: 'MailboxData:#Exchange',
        ...data,
    };

    return result;
}
