// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type MailboxMessageConfigurationOptions from '../contract/MailboxMessageConfigurationOptions';

export default function mailboxMessageConfigurationOptions(
    data: MailboxMessageConfigurationOptions
): MailboxMessageConfigurationOptions {
    let result: MailboxMessageConfigurationOptions = {
        __type: 'MailboxMessageConfigurationOptions:#Exchange',
        ...data,
    };

    return result;
}
