// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type MaskAutoCompleteRecipientRequest from '../contract/MaskAutoCompleteRecipientRequest';

export default function maskAutoCompleteRecipientRequest(
    data: MaskAutoCompleteRecipientRequest
): MaskAutoCompleteRecipientRequest {
    let result: MaskAutoCompleteRecipientRequest = {
        __type: 'MaskAutoCompleteRecipientRequest:#Exchange',
        ...data,
    };

    return result;
}
