// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type MeetingCancellationMessageType from '../contract/MeetingCancellationMessageType';

export default function meetingCancellationMessageType(
    data: MeetingCancellationMessageType
): MeetingCancellationMessageType {
    let result: MeetingCancellationMessageType = {
        __type: 'MeetingCancellationMessageType:#Exchange',
        ...data,
    };

    return result;
}
