// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type MeetingResponseMessageType from '../contract/MeetingResponseMessageType';

export default function meetingResponseMessageType(
    data: MeetingResponseMessageType
): MeetingResponseMessageType {
    let result: MeetingResponseMessageType = {
        __type: 'MeetingResponseMessageType:#Exchange',
        ...data,
    };

    return result;
}
