// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type MeetingRequestMessageType from '../contract/MeetingRequestMessageType';

export default function meetingRequestMessageType(
    data: MeetingRequestMessageType
): MeetingRequestMessageType {
    let result: MeetingRequestMessageType = {
        __type: 'MeetingRequestMessageType:#Exchange',
        ...data,
    };

    return result;
}
