// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type Message from '../contract/Message';

export default function message(data: Message): Message {
    let result: Message = {
        __type: 'Message:#Exchange',
        ...data,
    };

    return result;
}
