// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type MoveItemJsonRequest from '../contract/MoveItemJsonRequest';

export default function moveItemJsonRequest(data: MoveItemJsonRequest): MoveItemJsonRequest {
    let result: MoveItemJsonRequest = {
        __type: 'MoveItemJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
