// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type NotificationSubscribeJsonRequest from '../contract/NotificationSubscribeJsonRequest';

export default function notificationSubscribeJsonRequest(
    data: NotificationSubscribeJsonRequest
): NotificationSubscribeJsonRequest {
    let result: NotificationSubscribeJsonRequest = {
        __type: 'NotificationSubscribeJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
