// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type Or from '../contract/Or';

export default function or(data: Or): Or {
    let result: Or = {
        __type: 'Or:#Exchange',
        ...data,
    };

    return result;
}
