// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type PerformReminderActionJsonRequest from '../contract/PerformReminderActionJsonRequest';

export default function performReminderActionJsonRequest(
    data: PerformReminderActionJsonRequest
): PerformReminderActionJsonRequest {
    let result: PerformReminderActionJsonRequest = {
        __type: 'PerformReminderActionJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
