// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type PopupReminderSetting from '../contract/PopupReminderSetting';

export default function popupReminderSetting(data: PopupReminderSetting): PopupReminderSetting {
    let result: PopupReminderSetting = {
        __type: 'PopupReminderSetting:#Exchange',
        ...data,
    };

    return result;
}
