// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type PostGroupItemJsonRequest from '../contract/PostGroupItemJsonRequest';

export default function postGroupItemJsonRequest(
    data: PostGroupItemJsonRequest
): PostGroupItemJsonRequest {
    let result: PostGroupItemJsonRequest = {
        __type: 'PostGroupItemJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
