// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type PostGroupItemRequest from '../contract/PostGroupItemRequest';

export default function postGroupItemRequest(data: PostGroupItemRequest): PostGroupItemRequest {
    let result: PostGroupItemRequest = {
        __type: 'PostGroupItemRequest:#Exchange',
        ...data,
    };

    return result;
}
