// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type PostUnifiedGroupItemJsonRequest from '../contract/PostUnifiedGroupItemJsonRequest';

export default function postUnifiedGroupItemJsonRequest(
    data: PostUnifiedGroupItemJsonRequest
): PostUnifiedGroupItemJsonRequest {
    let result: PostUnifiedGroupItemJsonRequest = {
        __type: 'PostUnifiedGroupItemJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
