// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type QueryStringType from '../contract/QueryStringType';

export default function queryStringType(data: QueryStringType): QueryStringType {
    let result: QueryStringType = {
        __type: 'QueryStringType:#Exchange',
        ...data,
    };

    return result;
}
