// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type ReferenceAttachment from '../contract/ReferenceAttachment';

export default function referenceAttachment(data: ReferenceAttachment): ReferenceAttachment {
    let result: ReferenceAttachment = {
        __type: 'ReferenceAttachment:#Exchange',
        ...data,
    };

    return result;
}
