// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type RegisterConsentJsonRequest from '../contract/RegisterConsentJsonRequest';

export default function registerConsentJsonRequest(
    data: RegisterConsentJsonRequest
): RegisterConsentJsonRequest {
    let result: RegisterConsentJsonRequest = {
        __type: 'RegisterConsentJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
