// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type RejectRequestItem from '../contract/RejectRequestItem';

export default function rejectRequestItem(data: RejectRequestItem): RejectRequestItem {
    let result: RejectRequestItem = {
        __type: 'RejectRequestItem:#Exchange',
        ...data,
    };

    return result;
}
