// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type ReminderItemAction from '../contract/ReminderItemAction';

export default function reminderItemAction(data: ReminderItemAction): ReminderItemAction {
    let result: ReminderItemAction = {
        __type: 'ReminderItemAction:#Exchange',
        ...data,
    };

    return result;
}
