// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type ReplyAllToItem from '../contract/ReplyAllToItem';

export default function replyAllToItem(data: ReplyAllToItem): ReplyAllToItem {
    let result: ReplyAllToItem = {
        __type: 'ReplyAllToItem:#Exchange',
        ...data,
    };

    return result;
}
