// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type SaveAttachmentsToCloudRequest from '../contract/SaveAttachmentsToCloudRequest';

export default function saveAttachmentsToCloudRequest(
    data: SaveAttachmentsToCloudRequest
): SaveAttachmentsToCloudRequest {
    let result: SaveAttachmentsToCloudRequest = {
        __type: 'SaveAttachmentsToCloudRequest:#Exchange',
        ...data,
    };

    return result;
}
