// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type SaveExtensionCustomPropertiesParameters from '../contract/SaveExtensionCustomPropertiesParameters';

export default function saveExtensionCustomPropertiesParameters(
    data: SaveExtensionCustomPropertiesParameters
): SaveExtensionCustomPropertiesParameters {
    let result: SaveExtensionCustomPropertiesParameters = {
        __type: 'SaveExtensionCustomPropertiesParameters:#Exchange',
        ...data,
    };

    return result;
}
