// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type SaveExtensionSettingsParameters from '../contract/SaveExtensionSettingsParameters';

export default function saveExtensionSettingsParameters(
    data: SaveExtensionSettingsParameters
): SaveExtensionSettingsParameters {
    let result: SaveExtensionSettingsParameters = {
        __type: 'SaveExtensionSettingsParameters:#Exchange',
        ...data,
    };

    return result;
}
