// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type SearchFolder from '../contract/SearchFolder';

export default function searchFolder(data: SearchFolder): SearchFolder {
    let result: SearchFolder = {
        __type: 'SearchFolder:#Exchange',
        ...data,
    };

    return result;
}
