// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type SearchParametersType from '../contract/SearchParametersType';

export default function searchParametersType(data: SearchParametersType): SearchParametersType {
    let result: SearchParametersType = {
        __type: 'SearchParametersType:#Exchange',
        ...data,
    };

    return result;
}
