// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type ServiceUserConfiguration from '../contract/ServiceUserConfiguration';

export default function serviceUserConfiguration(
    data: ServiceUserConfiguration
): ServiceUserConfiguration {
    let result: ServiceUserConfiguration = {
        __type: 'ServiceUserConfiguration:#Exchange',
        ...data,
    };

    return result;
}
