// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type SetItemField from '../contract/SetItemField';

export default function setItemField(data: SetItemField): SetItemField {
    let result: SetItemField = {
        __type: 'SetItemField:#Exchange',
        ...data,
    };

    return result;
}
