// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type SetMailboxRegionalConfigurationData from '../contract/SetMailboxRegionalConfigurationData';

export default function setMailboxRegionalConfigurationData(
    data: SetMailboxRegionalConfigurationData
): SetMailboxRegionalConfigurationData {
    let result: SetMailboxRegionalConfigurationData = {
        __type: 'SetMailboxRegionalConfigurationData:#Exchange',
        ...data,
    };

    return result;
}
