// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type SetMailboxMessageConfigurationRequest from '../contract/SetMailboxMessageConfigurationRequest';

export default function setMailboxMessageConfigurationRequest(
    data: SetMailboxMessageConfigurationRequest
): SetMailboxMessageConfigurationRequest {
    let result: SetMailboxMessageConfigurationRequest = {
        __type: 'SetMailboxMessageConfigurationRequest:#Exchange',
        ...data,
    };

    return result;
}
