// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type SetUnifiedGroupUserSubscribeStateJsonRequest from '../contract/SetUnifiedGroupUserSubscribeStateJsonRequest';

export default function setUnifiedGroupUserSubscribeStateJsonRequest(
    data: SetUnifiedGroupUserSubscribeStateJsonRequest
): SetUnifiedGroupUserSubscribeStateJsonRequest {
    let result: SetUnifiedGroupUserSubscribeStateJsonRequest = {
        __type: 'SetUnifiedGroupUserSubscribeStateJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
