// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type SetUnifiedGroupMembershipStateJsonRequest from '../contract/SetUnifiedGroupMembershipStateJsonRequest';

export default function setUnifiedGroupMembershipStateJsonRequest(
    data: SetUnifiedGroupMembershipStateJsonRequest
): SetUnifiedGroupMembershipStateJsonRequest {
    let result: SetUnifiedGroupMembershipStateJsonRequest = {
        __type: 'SetUnifiedGroupMembershipStateJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
