// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type SetUnifiedGroupUserSubscribeStateRequest from '../contract/SetUnifiedGroupUserSubscribeStateRequest';

export default function setUnifiedGroupUserSubscribeStateRequest(
    data: SetUnifiedGroupUserSubscribeStateRequest
): SetUnifiedGroupUserSubscribeStateRequest {
    let result: SetUnifiedGroupUserSubscribeStateRequest = {
        __type: 'SetUnifiedGroupUserSubscribeStateRequest:#Exchange',
        ...data,
    };

    return result;
}
