// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type SetUnifiedGroupMembershipStateRequest from '../contract/SetUnifiedGroupMembershipStateRequest';

export default function setUnifiedGroupMembershipStateRequest(
    data: SetUnifiedGroupMembershipStateRequest
): SetUnifiedGroupMembershipStateRequest {
    let result: SetUnifiedGroupMembershipStateRequest = {
        __type: 'SetUnifiedGroupMembershipStateRequest:#Exchange',
        ...data,
    };

    return result;
}
