// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type ShareTailoredExperienceEventRequest from '../contract/ShareTailoredExperienceEventRequest';

export default function shareTailoredExperienceEventRequest(
    data: ShareTailoredExperienceEventRequest
): ShareTailoredExperienceEventRequest {
    let result: ShareTailoredExperienceEventRequest = {
        __type: 'ShareTailoredExperienceEventRequest:#Exchange',
        ...data,
    };

    return result;
}
