// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type SingleGroupSearchScopeType from '../contract/SingleGroupSearchScopeType';

export default function singleGroupSearchScopeType(
    data: SingleGroupSearchScopeType
): SingleGroupSearchScopeType {
    let result: SingleGroupSearchScopeType = {
        __type: 'SingleGroupSearchScopeType:#Exchange',
        ...data,
    };

    return result;
}
