// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type SingleRecipientType from '../contract/SingleRecipientType';

export default function singleRecipientType(data: SingleRecipientType): SingleRecipientType {
    let result: SingleRecipientType = {
        __type: 'SingleRecipientType:#Exchange',
        ...data,
    };

    return result;
}
