// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type SortResults from '../contract/SortResults';

export default function sortResults(data: SortResults): SortResults {
    let result: SortResults = {
        __type: 'SortResults:#Exchange',
        ...data,
    };

    return result;
}
