// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type SubscriptionData from '../contract/SubscriptionData';

export default function subscriptionData(data: SubscriptionData): SubscriptionData {
    let result: SubscriptionData = {
        __type: 'SubscriptionData:#Exchange',
        ...data,
    };

    return result;
}
