// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type SubscriptionParameters from '../contract/SubscriptionParameters';

export default function subscriptionParameters(
    data: SubscriptionParameters
): SubscriptionParameters {
    let result: SubscriptionParameters = {
        __type: 'SubscriptionParameters:#Exchange',
        ...data,
    };

    return result;
}
