// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type UpdateBirthdayEventJsonRequest from '../contract/UpdateBirthdayEventJsonRequest';

export default function updateBirthdayEventJsonRequest(
    data: UpdateBirthdayEventJsonRequest
): UpdateBirthdayEventJsonRequest {
    let result: UpdateBirthdayEventJsonRequest = {
        __type: 'UpdateBirthdayEventJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
