// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type UpdatePersonaJsonRequest from '../contract/UpdatePersonaJsonRequest';

export default function updatePersonaJsonRequest(
    data: UpdatePersonaJsonRequest
): UpdatePersonaJsonRequest {
    let result: UpdatePersonaJsonRequest = {
        __type: 'UpdatePersonaJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
