// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type UpdateCalendarEventJsonRequest from '../contract/UpdateCalendarEventJsonRequest';

export default function updateCalendarEventJsonRequest(
    data: UpdateCalendarEventJsonRequest
): UpdateCalendarEventJsonRequest {
    let result: UpdateCalendarEventJsonRequest = {
        __type: 'UpdateCalendarEventJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
