// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type UpdateUserGroupsSetConfigurationRequest from '../contract/UpdateUserGroupsSetConfigurationRequest';

export default function updateUserGroupsSetConfigurationRequest(
    data: UpdateUserGroupsSetConfigurationRequest
): UpdateUserGroupsSetConfigurationRequest {
    let result: UpdateUserGroupsSetConfigurationRequest = {
        __type: 'UpdateUserGroupsSetConfigurationRequest:#Exchange',
        ...data,
    };

    return result;
}
