// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type UpdateFavoriteFolderRequest from '../contract/UpdateFavoriteFolderRequest';

export default function updateFavoriteFolderRequest(
    data: UpdateFavoriteFolderRequest
): UpdateFavoriteFolderRequest {
    let result: UpdateFavoriteFolderRequest = {
        __type: 'UpdateFavoriteFolderRequest:#Exchange',
        ...data,
    };

    return result;
}
