// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type UpdateBirthdayEventRequest from '../contract/UpdateBirthdayEventRequest';

export default function updateBirthdayEventRequest(
    data: UpdateBirthdayEventRequest
): UpdateBirthdayEventRequest {
    let result: UpdateBirthdayEventRequest = {
        __type: 'UpdateBirthdayEventRequest:#Exchange',
        ...data,
    };

    return result;
}
