// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type UpdateItemJsonRequest from '../contract/UpdateItemJsonRequest';

export default function updateItemJsonRequest(data: UpdateItemJsonRequest): UpdateItemJsonRequest {
    let result: UpdateItemJsonRequest = {
        __type: 'UpdateItemJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
