// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type UpdateClientExtensionNotificationsRequest from '../contract/UpdateClientExtensionNotificationsRequest';

export default function updateClientExtensionNotificationsRequest(
    data: UpdateClientExtensionNotificationsRequest
): UpdateClientExtensionNotificationsRequest {
    let result: UpdateClientExtensionNotificationsRequest = {
        __type: 'UpdateClientExtensionNotificationsRequest:#Exchange',
        ...data,
    };

    return result;
}
