// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type UpdateItemRequest from '../contract/UpdateItemRequest';

export default function updateItemRequest(data: UpdateItemRequest): UpdateItemRequest {
    let result: UpdateItemRequest = {
        __type: 'UpdateItemRequest:#Exchange',
        ...data,
    };

    return result;
}
