// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type UserConfigurationDictionaryEntry from '../contract/UserConfigurationDictionaryEntry';

export default function userConfigurationDictionaryEntry(
    data: UserConfigurationDictionaryEntry
): UserConfigurationDictionaryEntry {
    let result: UserConfigurationDictionaryEntry = {
        __type: 'UserConfigurationDictionaryEntry:#Exchange',
        ...data,
    };

    return result;
}
