// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type UserConfigurationDictionaryObject from '../contract/UserConfigurationDictionaryObject';

export default function userConfigurationDictionaryObject(
    data: UserConfigurationDictionaryObject
): UserConfigurationDictionaryObject {
    let result: UserConfigurationDictionaryObject = {
        __type: 'UserConfigurationDictionaryObject:#Exchange',
        ...data,
    };

    return result;
}
