// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type UserConfigurationNameType from '../contract/UserConfigurationNameType';

export default function userConfigurationNameType(
    data: UserConfigurationNameType
): UserConfigurationNameType {
    let result: UserConfigurationNameType = {
        __type: 'UserConfigurationNameType:#Exchange',
        ...data,
    };

    return result;
}
