// This file is auto-generated by the "tsproxygen.exe" tool. Manual modification is not recommended.
import type ValidateUnifiedGroupPropertiesJsonRequest from '../contract/ValidateUnifiedGroupPropertiesJsonRequest';

export default function validateUnifiedGroupPropertiesJsonRequest(
    data: ValidateUnifiedGroupPropertiesJsonRequest
): ValidateUnifiedGroupPropertiesJsonRequest {
    let result: ValidateUnifiedGroupPropertiesJsonRequest = {
        __type: 'ValidateUnifiedGroupPropertiesJsonRequest:#Exchange',
        ...data,
    };

    return result;
}
