'use es6';

export var SET_AVAILABLE_INPUT_DEVICES = 'SET_AVAILABLE_INPUT_DEVICES';
export var SET_AVAILABLE_OUTPUT_DEVICES = 'SET_AVAILABLE_OUTPUT_DEVICES';
export var SET_INPUT_DEVICE = 'SET_INPUT_DEVICE';
export var SET_OUTPUT_DEVICE = 'SET_OUTPUT_DEVICE';
export var OUTPUT_DEVICE_NOT_SUPPORTED = 'OUTPUT_DEVICE_NOT_SUPPORTED';
export var INPUT_DEVICE_NOT_SUPPORTED = 'INPUT_DEVICE_NOT_SUPPORTED';